flexera-public/policy_templates

- README.md
> adding coming soon msg

- README.md
> Fixing readme formatting

- README.md
- security/security_groups/icmp_enabled/CHANGELOG.md
- security/security_groups/icmp_enabled/README.md
- security/security_groups/icmp_enabled/icmp_enabled.pt
- security/security_groups/rules_without_descriptions/CHANGELOG.md
- security/security_groups/rules_without_descriptions/README.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
> PSASSET-825-Security Groups with ICMP enabled

- security/storage/aws/public_buckets/CHANGELOG.md
- security/storage/aws/public_buckets/public_buckets.pt
Updating the severity of the security policy as per the spec. 
None
> AWS Public Buckets Policy: Updating the severity

- cost/downsize_instance/CHANGELOG.md
- cost/downsize_instance/downsize-instance.pt
Removing some default values from the input param of tag checker policy
None
> Removing some default values from the input param of tag checker policy

- security/storage/aws/public_buckets/CHANGELOG.md
- security/storage/aws/public_buckets/public_buckets.pt
Changes the location constraint region from EU to eu-west-1. 
> PSASSET-859, modifies EU region to eu-west-1, fixes #21

- compliance/tags/tag_checker/changelog.md
- compliance/tags/tag_checker/tag_checker.pt
- cost/aws/reserved_instances/expiration/CHANGELOG.md
- cost/aws/reserved_instances/expiration/expired_ris.pt
- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
- cost/downsize_instance/CHANGELOG.md
- cost/downsize_instance/downsize-instance.pt
- cost/volumes/CHANGELOG.md
- cost/volumes/uav_policy.pt
- security/security_groups/icmp_enabled/icmp_enabled.pt
- security/security_groups/rules_without_descriptions/CHANGELOG.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
- security/storage/aws/public_buckets/CHANGELOG.md
- security/storage/aws/public_buckets/public_buckets.pt
PHX-746 updating emails to list
> PHX-746 updating emails to list

- README.md
- security/storage/google/public_buckets/README.md
> Updating Root Readme

- README.md
> Updating readme with some tweaks

- README.md
Minor change to the readme file to make it a bit more pro. 
> Making some minor tweak to the messaging.

- README.md
Making it easier for folks to bring in templates to RS.
> Adding instructions to bring in policy templates in RS

- compliance/tags/tag_checker/README.md
- compliance/tags/tag_checker/tag_checker.pt
- cost/aws/reserved_instances/coverage/README.md
- cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
- cost/aws/reserved_instances/expiration/README.md
- cost/aws/reserved_instances/expiration/expired_ris.pt
- cost/aws/reserved_instances/utilization/README.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
- cost/downsize_instance/README.md
- cost/downsize_instance/downsize-instance-add-tags.pt
- cost/downsize_instance/downsize-instance.pt
- cost/volumes/README.md
- cost/volumes/old_snapshots/README.md
- cost/volumes/old_snapshots/old_snapshot.pt
- cost/volumes/uav_policy.pt
- operational/cloud_credentials/aws/README.md
- operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
- security/security_groups/high_open_ports/README.md
- security/security_groups/high_open_ports/open_ports.pt
- security/security_groups/icmp_enabled/README.md
- security/security_groups/icmp_enabled/icmp_enabled.pt
- security/security_groups/rules_without_descriptions/README.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
- security/storage/aws/public_buckets/README.md
- security/storage/aws/public_buckets/public_buckets.pt
- security/storage/google/public_buckets/README.md
- security/storage/google/public_buckets/public_buckets.pt
All README and user facing input params to be a bit more user friendly 
> Updating README and all user facing input params

- cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
- cost/aws/reserved_instances/expiration/expired_ris.pt
- cost/aws/reserved_instances/utilization/utilization_ris.pt
- cost/volumes/old_snapshots/old_snapshot.pt
- security/security_groups/high_open_ports/open_ports.pt
- security/security_groups/icmp_enabled/icmp_enabled.pt
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
- security/storage/aws/public_buckets/aws_public_buckets.pt
- security/storage/google/public_buckets/google_public_buckets.pt
> Syncing Versions for PSASSET-867

- operational/policy_sync/CHANGELOG.md
- operational/policy_sync/README.md
- operational/policy_sync/policy_sync.pt
> PSASSET-867 - Readme and min_length work. 

- operational/policy_sync/README.md
> Updating policy sync readme

- .travis.yml
- Dangerfile
- Gemfile
- Gemfile.lock
- README.md
- active-policy-list.json
- operational/snapshots/CHANGELOG.md
- operational/snapshots/README.md
- operational/snapshots/no_recent_snapshots.pt
No Recent Snapshots Policy Template
> PSASSET-830 No Recent Snapshots Policy Template

- cost/downsize_instance/CHANGELOG.md
- cost/downsize_instance/downsize-instance.pt
- cost/volumes/unattached_volumes/CHANGELOG.md
- cost/volumes/unattached_volumes/uav_policy.pt
Showing resource count in policies is an important way to create more attention. 
> Updating templates to add the resource count

- tools/policy_upload_scripts/CHANGELOG.md
- tools/policy_upload_scripts/README.md
- tools/policy_upload_scripts/policy_bootstrapper.py
The policy bootstrap script was using the force upgrade option which was actually counter productive. So that flag was removed from the script.
Also added support to specify a subset of accounts to upload the policy synch script to.
Also updated README to be more instructive.
https://github.com/rightscale/policy_templates/issues/65
- [ X] All tests pass.
- [ X] New functionality includes testing.
- [ X] New functionality has been documented in the README if applicable
> Policy bootstrap script enhancements and fixes

- active-policy-list.json
- cost/volumes/unattached_volumes/CHANGELOG.md
- cost/volumes/unattached_volumes/README.md
- cost/volumes/unattached_volumes/uav_policy.pt
Allows user to specify RightScale tags that if found on a volume excludes that volume from the policy.
https://github.com/rightscale/policy_templates/issues/40
- [ X] New functionality includes testing.
- [X ] New functionality has been documented in the README if applicable
> Added support for "exclusion" tags.

- Dangerfile
- compliance/tags/tag_checker/changelog.md
- compliance/tags/tag_checker/tag_checker.pt
Fix issue when account has no resources.
#53
- [ x] All tests pass.
> Psasset 833 - fix error with no resources

- Dangerfile
- active-policy-list.json
- cost/volumes/unattached_volumes/CHANGELOG.md
- cost/volumes/unattached_volumes/uav_policy.pt
The parameter for email or email and delete was changed to use upper and lower case and the related logic that decides to delete volumes was changed to support the new syntax.
- [ X] All tests pass.
> Uav support for new email and delete parameter

- security/security_groups/rules_without_descriptions/CHANGELOG.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
Severity was set too high for the value it provides to the user and the attention we want from the user. 
> Lowering the severity of the sec group policy

- tools/policy_upload_scripts/README.md
Updating policy upload tool instructions and typo.
> Updating policy upload tool instructions and typo

- cost/volumes/unattached_volumes/uav_policy.pt
- security/security_groups/high_open_ports/CHANGELOG.md
- security/security_groups/high_open_ports/open_ports.pt
- security/security_groups/icmp_enabled/CHANGELOG.md
- security/security_groups/icmp_enabled/icmp_enabled.pt
- security/security_groups/rules_without_descriptions/CHANGELOG.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
> Adding permissions required to run the policy

- cost/aws/reserved_instances/coverage/CHANGELOG.md
- cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
Adding permissions block to RI coverage policy - git issue 82
> Adding permissions block to RI coverage policy - git issue 82

- active-policy-list.json
- cost/schedule_instances/schedule_instances.pt
- cost/volumes/old_snapshots/CHANGELOG.md
- cost/volumes/old_snapshots/old_snapshot.pt
This fixes the bug in #93, by correctly subtracting and then doing a fail test. 
> PSASSET-874 - fixing check and updating versioning, fixes #93

- active-policy-list.json
- cost/schedule_instances/CHANGELOG.md
- cost/schedule_instances/schedule_instances.pt
Updating the policy with the correct link to the README
> update the readme link

- active-policy-list.json
- security/security_groups/rules_without_descriptions/CHANGELOG.md
- security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
Optimize Security Group Rules without Descriptions #45
#45
> PSASSET-860 - Security Group Rules without Descriptions

- active-policy-list.json
- security/storage/aws/public_buckets/CHANGELOG.md
- security/storage/aws/public_buckets/README.md
- security/storage/aws/public_buckets/aws_public_buckets.pt
Adds support for Slack channel notification when open buckets are found.
None
- [ X] All tests pass.
- [X ] New functionality includes testing.
- [X ] New functionality has been documented in the README if applicable
> Added support slack notification

- active-policy-list.json
- cost/volumes/old_snapshots/CHANGELOG.md
- cost/volumes/old_snapshots/old_snapshot.pt
> fixing a typo

- operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
- operational/cloud_credentials/aws/changelog.md
There was a typo in a call to log definition (missing a parameter)
None
- [X ] New functionality includes testing.
> Aws key rotation log typo

- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
> RI Utilization Policy - Fixes Email Formatting. 

- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
> Policy Sync, adding update for existing policies

- operational/dbaas/aws/rds_backup/CHANGELOG.md
- operational/dbaas/aws/rds_backup/README.md
- operational/dbaas/aws/rds_backup/aws_rds_backup.pt
AWS RDS Backup Settings - Initial Release
N/A
> AWS RDS Backup Settings - Initial Release

- README.md
Add RDS policy to top level README
> Fix Top Level README

- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/README.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
> RI Utilization Policy - Fix Rounding

- Rakefile
- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
> Policy Sync Tool: Adding in changelog url

- operational/cloud_credentials/aws/README.md
- operational/cloud_credentials/aws/aws_connection_key_rotation_policy.pt
- operational/cloud_credentials/aws/changelog.md
Addresses Issue 121
Also adds support for user-specified units for the rotation period.
https://github.com/rightscale/policy_templates/issues/121
- [ X] All tests pass.
- [ X] New functionality includes testing.
- [ X] New functionality has been documented in the README if applicable
> Aws key rotation issue 121

- cost/schedule_instances/CHANGELOG.md
- cost/schedule_instances/schedule_instances.pt
fix issue with stop/start functionality
- [ x] All tests pass.
> fix issue with stop

- operational/snapshots/CHANGELOG.md
- operational/snapshots/no_recent_snapshots.pt
> skip_excluded_resources_from_ds_volume_attachments_iteration

- README.md
- compliance/azure/azure_disallowed_regions/CHANGELOG.md
- compliance/azure/azure_disallowed_regions/README.md
- compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
- cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
Initial Release: Azure Disallowed Regions
> Initial Release: Azure Disallowed Regions

- README.md
- cost/billing_center_access_report/CHANGELOG.md
- cost/billing_center_access_report/README.md
- cost/billing_center_access_report/bc_access_report.pt
Initial Release of Billing Center Access Report policy
N/A
> Billing Center Access Report - Initial Release

- operational/snapshots/CHANGELOG.md
- operational/snapshots/no_recent_snapshots.pt
closes #104
Adding permissions block
#104 
- [ x] All tests pass.
> adding permissions declaration

- cost/aws/reserved_instances/coverage/CHANGELOG.md
- cost/aws/reserved_instances/coverage/reserved_instance_coverage.pt
closes #110
Updates coverage column with percent
#110 
- [ x] All tests pass.
> update coverage column to be percent.

- compliance/tags/tag_checker/CHANGELOG.md
- compliance/tags/tag_checker/README.md
- compliance/tags/tag_checker/tag_checker.pt
update readme with permissions statement
adding permissions and updated Readme
#141
> adding permissions for tags.multi_add

- compliance/azure/azure_disallowed_regions/README.md
- compliance/billing_center_access_report/README.md
- compliance/tags/tag_checker/README.md
- cost/aws/reserved_instances/coverage/README.md
- cost/aws/reserved_instances/expiration/README.md
- cost/aws/reserved_instances/report_by_bc/README.md
- cost/aws/reserved_instances/utilization/README.md
- cost/downsize_instance/README.md
- cost/schedule_instances/README.md
- cost/volumes/old_snapshots/README.md
- cost/volumes/unattached_volumes/README.md
- operational/cloud_credentials/aws/README.md
- operational/dbaas/aws/rds_backup/README.md
- operational/snapshots/README.md
- security/security_groups/high_open_ports/README.md
- security/security_groups/icmp_enabled/README.md
- security/security_groups/rules_without_descriptions/README.md
- security/storage/aws/public_buckets/README.md
- security/storage/google/public_buckets/README.md
Add Inputs and Actions to README's
#105
> Add Inputs and Actions to README's

- cost/azure/superseded_instance_types/CHANGELOG.md
- cost/azure/superseded_instance_types/README.md
- cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
Initial Release of Azure Superseded Instance Types policy
N/A
> Azure - Superseded Instance Types

- README.md
> Fix README URLs

- cost/azure/reserved_instances/utilization/CHANGELOG.md
- cost/azure/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
This adds a new policy for reporting on underutilized Azure Reserved Instances
none
> Azure Reserved Instances Policy

- README.md
- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/README.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
Initial release of the Azure HUB policy. Applies the Hybrid Use Benefit to all Windows VMs in a Azure Subscription
N/A
> Azure Hybrid Use Benefit Policy

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
Round actual spend and runrate spend to 2 decimals in Incident report
N/A
> Budget Alerts - Round Spend

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/scheduled_report.pt
Updates the version number in the policy template and changelog.
> Scheduled Report - Increment Version Identifier to 1.3

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
Update Budget Alerts policy to use new public Bill Analysis API
N/A
> Budget Alerts - Update to new API

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/README.md
- cost/scheduled_reports/scheduled_report.pt
Adds a chart that displays the last 6 months of utilization based on the category dimension.
N/A
> Scheduled Report - 6mo Utilization Chart

- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
Compares major/minor versions of RightScale catalog policies
https://github.com/rightscale/policy_templates/issues/171
> Policy Sync: Updating versioning - comparing major and minor versions

- compliance/billing_center_access_report/README.md
- cost/aws/reserved_instances/expiration/README.md
- cost/aws/reserved_instances/report_by_bc/README.md
- cost/aws/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/README.md
- cost/billing_center_cost_anomaly/README.md
- cost/budget_alerts/README.md
- cost/scheduled_reports/README.md
Add a disclaimer to Policies that should only be applied to the Master Account.
#187
> readme disclaimers

- cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
- cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
v1.1 = updated short description
Updated Description in UI
- [X ] New functionality includes testing.
- [X ] New functionality has been documented in the README if applicable
> Updating the  v1.1 = updated short description

- compliance/github/available_seats/CHANGELOG.md
- compliance/github/available_seats/available_seats.pt
> Github Licensed Seats: Updating short description

- .travis.yml
- tools/travis/build_docs.sh
Updates to Travis config to allow api call to docs repo to restart build job.
> Use Travis to build docs

- .travis.yml
Fix the path to the build_docs.sh script
> Update build docs script path

- compliance/tags/tag_checker/CHANGELOG.md
- compliance/tags/tag_checker/tag_checker.pt
- operational/dbaas/aws/rds_backup/CHANGELOG.md
- operational/dbaas/aws/rds_backup/aws_rds_backup.pt
> Removing Tag Checker Icon from Marketplace

- README.md
- operational/aws/subnet_name_sync/README.md
- operational/aws/subnet_name_sync/changelog.md
- operational/aws/subnet_name_sync/subnets_sync.pt
- operational/aws/vpc_name_sync/README.md
- operational/aws/vpc_name_sync/changelog.md
- operational/aws/vpc_name_sync/vpc_sync.pt
Policies that sync AWS VPC and Subnet names to Cloud Management
N/A
> AWS VPC and Subnet Name Sync

- cost/schedule_instances/CHANGELOG.md
- cost/schedule_instances/schedule_instances.pt
Removes the "Next Action" field from the email template
> Update email template schedule instance

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/README.md
- cost/scheduled_reports/currency_reference.json
- cost/scheduled_reports/scheduled_report.pt
Adds "Resource" Group as a dimension as well as "Cloud Vendor", "Cloud Vendor Account", and "Cloud Vendor Account Name"
Adds support for reporting on Child Billing Centers
Forces the Chart Legend to always display below the chart
Adds currency symbol and thousands separator based on the currency set in Optima.
Scheduled Report calculations off - #211
> Scheduled Report Enhancements

- cost/aws/elb/clb_unused/AWS_Delete_Unused_CLB.pt
- cost/aws/elb/clb_unused/CHANGELOG.md
Removed Competitor Reference
This policy checks all ELB (CLB) to determine if any are unused (have no healthy instances) and allows them to be deleted by the user after approval.
Removed Reference URL in the policy.
> POL-34-Removed Reference URL

- CODEOWNERS
This adds in CODEOWNERS into the repo to automate reviews. 
> adding in codeowners

- cost/azure/superseded_instance_types/CHANGELOG.md
- cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
Updates the link in the description
- [ x ] New functionality has been documented in CHANGELOG.MD
> bump version to update link

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
Reduces frequency of notifications due to constantly changing amounts 
N/A
- [ x ] New functionality has been documented in the README if applicable
- [ x ] New functionality has been documented in CHANGELOG.MD
> Reduce frequency of incident creation/email

- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
Add scope & type to incident report of RI Utilization policy
N/A
> RI Utilization Policy - add fields to incident report

- cost/volumes/old_snapshots/CHANGELOG.md
- cost/volumes/old_snapshots/old_snapshot.pt
Updating Old Snapshots and adding delete
> Updating Old Snapshots and adding delete

- .gitignore
- README.md
- cost/low_service_usage/CHANGELOG.md
- cost/low_service_usage/README.md
- cost/low_service_usage/low_service_usage.pt
> Low Service Usage Policy

- .gitignore
- README.md
- cost/low_account_usage/CHANGELOG.md
- cost/low_account_usage/README.md
- cost/low_account_usage/low_account_usage.pt
> Low Account Usage Policy

- README.md
- cost/google/unutilized_ip_addresses/CHANGELOG.md
- cost/google/unutilized_ip_addresses/README.md
- cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
A new policy to show unutilized google ips. 
> Google unutilized ip policy

- data/aws/regions.json
> Adding in Amazon Regions Datasource

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
Cheaper regions with Instance only data, and column cleanup
> Cheaper regions with Instance only data, and column cleanup

- README.md
> Adding JSON to Readme

- cost/terminate_policy/CHANGELOG.md
- cost/terminate_policy/instance_terminate.pt
> fixing short description link

- README.md
- cost/azure/instances_log_analitics_utilization/CHANGELOG.md
- cost/azure/instances_log_analitics_utilization/README.md
- cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
This policy captures CPU and Memory utilization metrics from Azure Log Analytics and compares those values to the CPU and Memory utilization parameters which define the thresholds to raise an incident for.
The escalation will tag all identified instances to later be resized by the Downsize Instances policy.
N/A
> Azure Instances Log Analytics Utilization

- operational/aws/instance_scheduled_events/AWS_Instance_Scheduled_Events
- operational/aws/instance_scheduled_events/CHANGELOG.md
- operational/aws/instance_scheduled_events/README.md
Initial release for POL-5
This policy checks for any scheduled event on EC2 instances that could cause operational issues, such as an instance reboot or termination.
The policy leverages the AWS EC2 API to discover any scheduled events on EC2 instances and provides the details in a report emailed to the specified users.
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5d1ae96c1cec7b0099a7c4af
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5d1b4dff19e62d009980a403
> POL-5 AWS Instance Scheduled Events

- README.md
- libraries/README.md
- libraries/cwf/google_authenticate.rcl.rb
> Adding in Libraries repro structure and google auth library. 

- README.md
- compliance/azure/subscription_access/CHANGELOG.md
- compliance/azure/subscription_access/README.md
- compliance/azure/subscription_access/azure_subscription_access.pt
Azure Subscription Access Policy
> POL-39 - Azure Subscription Access Policy

- README.md
- security/storage/aws/s3_buckets_without_server_access_logging/CHANGELOG.md
- security/storage/aws/s3_buckets_without_server_access_logging/README.md
- security/storage/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
AWS S3 Buckets without Server Access Logging
> POL-44 - AWS S3 Buckets without Server Access Logging

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
> Superseded Instance Policy - Fixing table in report

- cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
- cost/aws/instance_cloudwatch_utilization/README.md
- cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
> AWS Native Utilization - Adding windows

- cost/terminate_policy/CHANGELOG.md
- cost/terminate_policy/instance_terminate.pt
> Terminate actions dont need parents

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
> Fixing Cheaper Regions Billing Center

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/README.md
- cost/superseded_instance/superseded_instance.pt
> Superseded Instance Run Rate Change

- cost/schedule_instances/CHANGELOG.md
- cost/schedule_instances/README.md
Updating README with timezone list
- [ x New functionality has been documented in CHANGELOG.MD
> update readme with timezone list

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
> Cheaper Regions Add in Resource ID

- cost/volumes/old_snapshots/CHANGELOG.md
- cost/volumes/old_snapshots/old_snapshot.pt
> Old Snaphots - Email Always

- cost/terminate_policy/README.md
> updating docs for clarity

- README.md
- security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
- security/azure/sql_publicly_accessible_managed_instance/Check_for_publicly_accessible_Azure_SQL_Managed_Instance.pt
- security/azure/sql_publicly_accessible_managed_instance/README.md
pol-45_Check_for_publicly_accessible_Azure_SQL_Managed_Instance
Report and remediate any Azure SQL Managed instances that are publicly accessible.
This policy checks all Azure SQL Managed instances and reports on any that are publicly accessible. When such an instance is detected, the user can choose to delete it or remove the publicly accessible firewall rule(s).
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5d5a5940d732f600897e9e84
> pol-45_Check_for_publicly_accessible_Azure_SQL_Managed_Instance

- cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
- cost/aws/instance_cloudwatch_utilization/README.md
- cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
> AWS Cloudwatch Utilization - Fix documentation

- cost/volumes/old_snapshots/CHANGELOG.md
- cost/volumes/old_snapshots/old_snapshot.pt
> Snapshot email

- cost/google/instances_stackdriver_utilization/CHANGELOG.md
- cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
> Google Utilization fixing nil error

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
> Superseded Instances: Added region to output 

- README.md
Linked clients to community and update example testing against updated URL
Clients will follow new support flow via Community instead of Slack
> updating community link and rightscale policy template reference

- operational/vmware/instance_tag_sync/instance_tag_sync.pt
> fix readme link for vmware tag sync

- cost/volumes/old_snapshots/README.md
add vmware to support clouds in README
> update readme to include RCA-V

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
> fix readme link

- operational/fnms/schedule_fnms_reports/CHANGELOG.md
- operational/fnms/schedule_fnms_reports/README.md
- added version 1 to the change log
Minor doc changes and added to the ChangeLog
Was not published, it should be published now
> - Minor Doc changes

- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/README.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
> update policy name to reflect supported cloud.

- README.md
- cost/google/idle_compute_instances/CHANGELOG.md
- cost/google/idle_compute_instances/README.md
- cost/google/idle_compute_instances/google_idle_compute_instances.pt
- cost/google/idle_compute_instances/google_instances_stackdriver_utilization.pt
> Google Idle Compute Instances

- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/README.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
> AWS Idle Cleanup

- README.md
- cost/aws/object_storage_optimization/CHANGELOG.md
- cost/aws/object_storage_optimization/README.md
- cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
This Policy checks S3 buckets for older objects and can move the old object to 'glacier' or 'deep archive' after a given period of time. The user can choose to delete the old object by enabling 'delete action' option as mentioned in Enable delete action section in README.md.
- This policy identifies all S3 objects last updated outside of the specified time-frame
- For all objects identified as old, the user can choose to move the object to Glacier or Glacier Deep Archive after the specified time-frame.
-Delete action is disabled by default, user can choose to delete the old object by enabling 'delete action' option as mentioned in Enable delete action section in README.md.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5d7f85e40178e60089acb197
> Pol 104 aws object storage optimization

- cost/aws/object_storage_optimization/CHANGELOG.md
- cost/aws/object_storage_optimization/README.md
- cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
Fixed the Issue for POL-111.
404 Error while running AWS Object Optimization
- Found out that the ERROR is due to Bucket name where AWS has updated naming conventions for S3 buckets in the US East (N. Virginia) on March-1-2018, hence getting ERROR 404 for the buckets which contain ‘uppercase letters’ or ‘underscores’ in bucket name.
modified constructing S3 bucket endpoint.
Running template links:
- https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5d8387eaae2046008906edad
- https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5d8378dcf5e18800a1a79b67
- https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5d83811557843400a1caab86
> POL-104 modified constructing S3 bucket endpoint.

- cost/azure/reserved_instances/expiration/CHANGELOG.md
- cost/azure/reserved_instances/expiration/README.md
- cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Raises an incident when an Azure RI is expiring within `n` days
N/A
> Azure RI Expiration

- cost/google/unused_cloudsql_instances/CHANGELOG.md
- cost/google/unused_cloudsql_instances/README.md
- cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt
> Google Unused CloudSQL Instances

- README.md
- cost/azure/object_storage_optimization/CHANGELOG.md
- cost/azure/object_storage_optimization/README.md
- cost/azure/object_storage_optimization/azure_object_storage_optimization.pt
POL-105-Azure Blob Storage Optimization
Checks Azure Blob Storage for last updated time and moves the object to the Cool or Archive tier after user approval
- This policy identifies all Azure Blob Storage objects last modified outside of the specified time frame
- For all objects identified as old, the user can choose to move the object to Cool or Archived tiers 
after user approval
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5d82190d84fd710089f3b46f
> POL-105-Azure Blob Storage Optimization

- README.md
- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/reserved_instances/expiration/CHANGELOG.md
- cost/aws/reserved_instances/expiration/README.md
- cost/aws/reserved_instances/expiration/expired_ris.pt
- cost/azure/reserved_instances/expiration/CHANGELOG.md
- cost/azure/reserved_instances/expiration/README.md
- cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
- cost/google/cud_expiration/CHANGELOG.md
- cost/google/cud_expiration/Google_CUD_Expiration_Report.pt
- cost/google/cud_expiration/README.md
- cost/google/cud_report/CHANGELOG.md
- cost/google/cud_report/Google_Committed_UseDiscount_Report.pt
- cost/google/cud_report/README.md
- cost/google/idle_compute_instances/CHANGELOG.md
- cost/google/idle_compute_instances/google_idle_compute_instances.pt
remove "report" from policy name
making short_description consistent across common policies
> some minor clean up

- cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
- cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
> RDS RightSizing Fixing json path

- compliance/aws/ecs_unused/AWS_Unused_ECS_Clusters.pt
- compliance/aws/ecs_unused/CHANGELOG.md
- compliance/github/available_seats/available_seats.pt
- compliance/github/repository_admin_team/CHANGELOG.md
- compliance/github/repository_admin_team/repository_admin_team.pt
- compliance/github/repository_branch_protection/CHANGELOG.md
- compliance/github/repository_branch_protection/repository_branch_protection.pt
- compliance/github/repository_size/CHANGELOG.md
- compliance/github/repository_size/repository_size.pt
- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
- cost/google/instances_stackdriver_utilization/CHANGELOG.md
- cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt
> Fix readme links

- cost/aws/burstable_instance_cloudwatch_credit_utilization/CHANGELOG.md
- cost/aws/burstable_instance_cloudwatch_credit_utilization/README.md
- cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt
> Updating Burstable Template to fix items

- README.md
- cost/google/cloudsql_rightsizing/CHANGELOG.md
- cost/google/cloudsql_rightsizing/README.md
- cost/google/cloudsql_rightsizing/google_cloudsql_rightsizing.pt
1.  Google Rightsize Cloud SQL update the policy name and readme file
2. add Google Unused Cloud SQL to Root Readme
> update policy name and readme

- compliance/fnms/fnms_licenses_at_risk/CHANGELOG.md
- compliance/fnms/fnms_licenses_at_risk/fnms-at-risk-licenses.pt
Adjust version format an remove testing default values
> POL-69 Adjustment to version and default values

- Rakefile
skip adding policies to the active-policy-list if the policy is missing the version
Policies will be skipped if the policy long_description is  Version: 0.0 or Version is not included. 
> skip adding policies 

- cost/downsize_instance/README.md
> POL-123 fix broken links

- compliance/azure/subscription_access/CHANGELOG.md
- compliance/azure/subscription_access/README.md
- compliance/azure/subscription_access/azure_subscription_access.pt
Fixes a limitation in v1.0 that only returns the first 100 users.
n/a
> Azure Subscription Access - Fix for Users

- compliance/azure/azure_long_stopped_instances/CHANGELOG.md
- compliance/azure/azure_long_stopped_instances/README.md
- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
Squashes some bugs and enhances the decision logic.
Added section headers, updated detail_template, and cleaned up some formatting.
1. Fixes an undocumented requirement/expectation of the VM being tagged with the resource group name.
2. Fixes an exception that happens where an unexpected status is in the statuses array of the VM instance view.
> Azure Long Stopped Instances - Fix RG tag and missing time stamp

- cost/azure/reserved_instances/expiration/CHANGELOG.md
- cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Updates the policy to use the correct Optima endpoint.
n/a
> Azure Expiring RIs - Update Optima Endpoint

- README.md
- cost/budget_v_actual/CHANGELOG.md
- cost/budget_v_actual/README.md
- cost/budget_v_actual/monthly_budget_v_actual.pt
> Pol-103 - Monthly Actual v. Budgeted Spend Report

- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/README.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
POL-135-Updated Permission block
Unable to upload Azure Hybrid Use Benefit for Windows Server
Removed comma in the permission block
> POL-135-Updated Permission block

- README.md
- compliance/aws/disallowed_regions/CHANGELOG.md
- compliance/aws/disallowed_regions/README.md
- compliance/aws/disallowed_regions/aws_disallowed_regions.pt
Check for usage in disallowed regions
Report on any instances that are in a disallowed region with the option to Terminate them.
Reporting and terminating instances in disallowed region afte user approval.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5db03e460fe96800017d06ac
> POL-29 Check for usage in disallowed regions

- README.md
- cost/scheduled_reports_with_estimates/CHANGELOG.md
- cost/scheduled_reports_with_estimates/README.md
- cost/scheduled_reports_with_estimates/costs_forecasting.pt
Adds 3 months of estimated cost to scheduled report
N/A
> POL-125 Scheduled Report With Estimates

- README.md
- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/README.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Initial release
Policy template checks for Azure SQL Databases that are unused by reviewing the DB connections and delete them after user approval.
This policy gets a list of Azure SQL Databases and uses the DB Connection metric to check for successful connections over a 30-day period. If there are no successful DB Connections the policy will terminate the SQL databases after the user approval.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5daff371a075f60089bf53a2
> POL-113 Azure Unused SQL Databases

- cost/budget_v_actual/CHANGELOG.md
- cost/budget_v_actual/monthly_budget_v_actual.pt
> Remove budget input details from template short_description

- README.md
- compliance/azure/compliance_score/CHANGELOG.md
- compliance/azure/compliance_score/README.md
- compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
Azure Compliance Report initial release
> Pol 131 compliance scores

- README.md
- operational/compute_instance_migration/README.md
- operational/compute_instance_migration/changelog.md
- operational/compute_instance_migration/risc-compute-instance-migration-recos.pt
Initial Release of App Migration Recos
> Pol 134 migration recos

- compliance/azure/azure_long_stopped_instances/README.md
- cost/volumes/old_snapshots/README.md
- operational/vmware/instance_tag_sync/README.md
- adding missing inputs in readme
- update old snapshot readme with correct action
> include missing inputs

- README.md
- cost/rightlink_rightsize/CHANGELOG.md
- cost/rightlink_rightsize/README.md
- cost/rightlink_rightsize/rightlink-rightsize-add-tags.pt
- cost/rightlink_rightsize/rightlink_rightsize.pt
- data/vmware/instance_types.json
Rightlink rightsize recommendations
POL-126
> POL-126 Instance Utilization

- Dangerfile
fix some links that where not checked correctly
> fix issues with link check

- Dangerfile
urls w/ dynamically created hosts are ignored
> check for valid hosts

- Dangerfile
fix issue with lowercase check
> Lowercase check

- cost/billing_center_cost_anomaly/CHANGELOG.md
- cost/billing_center_cost_anomaly/README.md
- cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
Update the Billing Center Cost Anomalies to allow the user to create an incident for all Billing Centers in the Org or enter a list of billing centers
1-Added new parameter for Billing Center List
2-Updated readme to indicate the new input
3-Added parameters used to the Incident detail
4-Sorted by Billing Center Name
5-Right justifying the currency values
6-Format the values with currency symbols
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5ddcfe0cca13c9000134417a
> POL-152 update billing center cost anomalies

- compliance/azure/azure_long_stopped_instances/README.md
- compliance/azure/instances_without_fnm_agent/README.md
- cost/azure/idle_compute_instances/README.md
- operational/azure/azure_migrate/README.md
- operational/azure/vms_without_managed_disks/README.md
* update the Azure policies missing instructions for creds.
* fixing MD for lint compliance 
> POL-156 update azure readme

- Dangerfile
update danger file for correct  response.code check
> POL-159 Dangerfile http response code check

- README.md
- saas/fsm/suspicious_users/CHANGELOG.md
- saas/fsm/suspicious_users/README.md
- saas/fsm/suspicious_users/fsm-suspicious_users.pt
initial release of Suspicious Users policy
> POL-86 FSM Suspicious Users

- operational/fnms/schedule_fnms_reports/CHANGELOG.md
- operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
and the Readme
Version did not match the doc's and was the old one so it was not published.
Version changed to 1.5
> POL-157 Version changed to 1.5 to match the new changes

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
Date format defect fixed
Superseded Instances fails with incorrect date
Fixed the date format issue
I have added the new info field like below
info(
version: "1.5",
provider: "RightScale",
service: "",
policy_set: ""
)
I have left the service and policy_set as empty, since I don't know the value
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5df9d508372f7a0001f6d4ca
> POL-162-Date format defect fixed

- Dangerfile
* remove hostnames located in code.
* remove renamed files to prevent errors on non-existent filenames
> fix danger errors

- README_GUIDELINE.md
> add cred mgt details

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/scheduled_report.pt
This policy allows you to set up scheduled reports that will provide summaries of cloud cost across all resources in the billing centers you specify, delivered to any email addresses you specify. The policy will report the following:
Fix for Bug Dimension Information Missing for DAY and WEEK.
Billing Term: Day
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e259bf232401200016e0b80
Billing Term: Week
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e259c097abe69000112c988
Billing Term: Month
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e259bfe7abe69000112c987
> POL-179- 1965254 Dimension Information Missing for DAY and WEEK.

- cost/downsize_instance/README.md
update the permissions to run the actions.
fix the md formating
> Permissions

- cost/billing_center_cost_anomaly/CHANGELOG.md
- cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
> bump version and add info field

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/scheduled_report.pt
Date range calculation setting issue
Date range calculation
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e3801b84ec7b3000163f0f9
> Pol 179 1965254 dimension information missing

- compliance/aws/ecs_unused/aws_unused_ecs_clusters.pt
- operational/aws/vpc_name_sync/aws_vpc_name_sync.pt
- security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt
- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
* use the info field for the version
* remove the version from long description 
> remove version from long_description

- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
> Fix pol sync

- cost/aws/idle_compute_instances/README.md
- cost/aws/instance_cloudwatch_utilization/README.md
> POL-188 Updating IAM Policies. 

- cost/google/old_snapshots/CHANGELOG.md
- cost/google/old_snapshots/README.md
- cost/google/old_snapshots/google_delete_old_snapshots.pt
Initial Release of the Old Snapshots Policy
> POL-205 Google Old Snapshots

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/README.md
- cost/budget_alerts/budget_alert.pt
Budget Alert - Policy evaluation exceeded maximum time
- Fixed evaluation exceeded maximum time
- Removed param_budget_scope
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e563a04bee5580001a7e539
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e5638cf7676ab0001ce10fc
> Pol 218 budget alert policy evaluation exceeded maximum time

- .gitignore
- package-lock.json
- policy_templates.code-workspace
> POL-226 Adding in initial code workspace items. 

- README.md
- operational/aws/long_running_instances/CHANGELOG.md
- operational/aws/long_running_instances/README.md
- operational/aws/long_running_instances/long_running_instances.pt
> POL-32 AWS Long Running Instances

- tools/bin/convert_table
This is a sample tool to create the data table for you. Some caveats:
* This is meant to be a throwaway tool used once.
* This just does the data table, not the the selectable actions parts as well. Those can probably be done by hand or using mass search and replace in an editor or something as they're more rote
* This just gets you roughly there and tries to do the tedious and error prone parts for you, not meant to be super thorough or perfect. Lots of the more complicated tables didn't convert super well, I've left comments as needed with clarifications. Leave comments if you have any questions on that PR, will leave it open as a reference for a little bit.
I made a temporary PR with a run of the tool just for discussion purposes, no need to merge it. I'll leave it up to the policy …
> PHX-2039 Basic convert_table tool

- compliance/azure/azure_disallowed_regions/CHANGELOG.md
- compliance/azure/azure_disallowed_regions/README.md
- compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
Looking for indication that it failed to terminate the instances.
Error report will be logged to indicate that it has failed to terminate the instance.
Log Link:
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5e721399fa003e0001fd2533
> POL-177- Azure Disallowed Regions - terminate instance

- compliance/azure/subscription_access/CHANGELOG.md
- compliance/azure/subscription_access/README.md
- compliance/azure/subscription_access/azure_subscription_access.pt
Fixes an issue with incorrect provider tag
> fixs for Graphs/Azure AD API

- tools/bin/convert_table
> PHX-2039 Cherry Pick Tool

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
> POL-224 Updating for first day. 

- cost/billing_center_cost_anomaly/CHANGELOG.md
- cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
fixing no data table defect
Running the Billing Center Cost Anomaly policy on a billing center created an incident with no data in the tables.
No data table defect fixed
Incident not created if data is not available to display.
Incident created if data is available to display.
https://governance.rightscale.com/org/78/projects/30598/policy-incidents/5e8491c5c998f80001da60f2
> POL-219 - fixing no data table defect 

- compliance/github/repository_branch_protection/CHANGELOG.md
- compliance/github/repository_branch_protection/README.md
- compliance/github/repository_branch_protection/repository_branch_protection.pt
- Moves GitHub Branch Protection Policy to new credentials
- Adds escalation action
None
> CET-11 - Add branch protection escalation action

- cost/google/unattached_volumes/CHANGELOG.md
- cost/google/unattached_volumes/README.md
- cost/google/unattached_volumes/google_delete_unattached_volumes.pt
- If APIs and Services are not enabled for a project.
- If the project is shutdown.
> POL-260 Google unattached volumes unhandled errors when executing

- saas/fsm/renewal_reminder/CHANGELOG.md
- saas/fsm/renewal_reminder/README.md
- saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
- saas/fsm/suspicious_users/CHANGELOG.md
- saas/fsm/suspicious_users/README.md
- saas/fsm/suspicious_users/fsm-suspicious_users.pt
- saas/fsm/unsanctioned_spend/CHANGELOG.md
- saas/fsm/unsanctioned_spend/README.md
- saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
- saas/fsm/user_status_change/CHANGELOG.md
- saas/fsm/user_status_change/README.md
- saas/fsm/user_status_change/fsm-user_status_change.pt
Update FSM policies with Credential service and Endpoint
Update FSM policies with new endpoint and Credential Service
Update FSM policies with new endpoint and Credential Service
Update readme to replace credential instructions with instructions to use credential service
SaaS Manager - Suspicious Users:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e8d85b2e8dac600012ec324
SaaS Manager - User Status Change:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e8d87231ccef500019d6033
SaaS Manager - Unsanctioned Spend:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e8d865f1ccef500019d6032
SaaS Manager - Renewal Reminder:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e8d840ee8dac6000 …
> POL-190 - Update FSM policies with new endpoint

- cost/rightlink_rightsize/CHANGELOG.md
- cost/rightlink_rightsize/rightlink_rightsize.pt
- cost/unattached_addresses/CHANGELOG.md
- cost/unattached_addresses/unattached_addresses.pt
- cost/volumes/unattached_volumes/CHANGELOG.md
- cost/volumes/unattached_volumes/uav_policy.pt
README link was missing in the policy template
Included README link in the policy template
> Pol 267 case 02061648 readme missing from policy details

- saas/fsm/user_status_change/CHANGELOG.md
- saas/fsm/user_status_change/fsm-user_status_change.pt
Adds user dep't to policy output
Removed console.log statements
Sorted output by Dep't
Tested by substituting "magic org" 28010 for rs_org_id in code
https://jira.flexera.com/browse/POL-261
> POL-261 - Add department to user output

- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Skip resources that do not return a SKU value
> POL-270 - RightSize Azure SQL: bug fix 

- compliance/azure/compliance_score/CHANGELOG.md
- compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
Bug Fix: skip subscriptions with Azure Compliance disabled
> POL-269 - Azure Compliance Score: bug fix

- cost/aws/reserved_instances/expiration/CHANGELOG.md
- cost/aws/reserved_instances/expiration/expired_ris.pt
- cost/aws/reserved_instances/report_by_bc/CHANGELOG.md
- cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt
- cost/aws/reserved_instances/utilization/CHANGELOG.md
- cost/aws/reserved_instances/utilization/utilization_ris.pt
Change the datasource URI for policies that interact with Optima to retrieve AWS RI details
> POL-271 Fix AWS RI policies

- cost/google/old_snapshots/CHANGELOG.md
- cost/google/old_snapshots/google_delete_old_snapshots.pt
Rounded off the Age in Days column to Whole number, for preventing the policy to send too many mails.
> POL-272-Google Old Snapshots to many emails

- .travis.yml
> update secure env

- README.md
- saas/fsm/unsanctioned_apps_with_contract/CHANGELOG.md
- saas/fsm/unsanctioned_apps_with_contract/README.md
- saas/fsm/unsanctioned_apps_with_contract/fsm-unsanctioned_with_contract.pt
initial release of Unsanctioned SaaS Apps with Existing Contract policy
> POL-273 - Unsanctioned Apps with Managed Contract

- saas/fsm/inactive_users_by_dept/CHANGELOG.md
- saas/fsm/inactive_users_by_dept/README.md
- saas/fsm/inactive_users_by_dept/inactive_users_by_dept.pt
Add Param to filter inactive users by number days inactive
#529
> Add Param to Inactive Users By Dept policy

- saas/fsm/unsanctioned_spend/CHANGELOG.md
- saas/fsm/unsanctioned_spend/README.md
- saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
- support new incident table
- add parameter to target specific Applications
- cleanup unnecessary datasource
> POL-95 update FSM Unsanctioned Spend policy

- cost/instance_anomaly/CHANGELOG.md
- cost/instance_anomaly/instance_anomaly.pt
Fixes the UI rendering where the Cost category spacing is off.
> Fix UI Rendering of Policy Cards

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/scheduled_report.pt
Add "Billing Centers" graph dimension to report on child BCs
POL-280
> Scheduled Reports: add Billing Center graph dimension

- README.md
- operational/azure/sync_tags_with_optima/CHANGELOG.md
- operational/azure/sync_tags_with_optima/README.md
- operational/azure/sync_tags_with_optima/sync_azure_tags.pt
Initial release of Sync Azure Tags With Optima
POL-294
> POL-294: Sync Azure Tags with Optima

- README.md
- compliance/aws/scp_audit/CHANGELOG.md
- compliance/aws/scp_audit/README.md
- compliance/aws/scp_audit/aws_scp_audit.pt
Audits all accounts in an AWS account to check whether they have a specified Service Control Policy attached.
N/A
> POL-289: AWS SCP Audit

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
- cost/low_account_usage/CHANGELOG.md
- cost/low_account_usage/low_account_usage.pt
- cost/low_service_usage/CHANGELOG.md
- cost/low_service_usage/low_service_usage.pt
- cost/new_service_usage/CHANGELOG.md
- cost/new_service_usage/new_service_usage.pt
- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
- msp/compliance/orgs_and_cloud_accounts_report/CHANGELOG.md
- msp/compliance/orgs_and_cloud_accounts_report/orgs_and_cloud_accounts_report.pt
> Updating Bill Analysis Endpoint

- cost/azure/instances_log_analitics_utilization/CHANGELOG.md
- cost/azure/instances_log_analitics_utilization/azure_instance_log_analytics_utilization.pt
It resolves the 404 issue being faced intermittently by the user, while getting the details about resources.
> POL-311-Azure-Inefficient-Instance-Utilization-Using-Log-Analytics-unhandled-error

- compliance/azure/azure_long_stopped_instances/CHANGELOG.md
- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
The policy was running into a 404 error when the resource was not found. So, I updated the policy to handle the error.
> POL-310 Azure Long stopped instances unhandled error

- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
POL-309 Azure Idle compute instances unhandled error when executing
Azure Idle compute instances unhandled error when executing
Error fixed
> POL-309 Azure Idle compute instances unhandled error when executing

- README.md
- compliance/aws/iam_role_audit/CHANGELOG.md
- compliance/aws/iam_role_audit/README.md
- compliance/aws/iam_role_audit/aws_iam_role_audit.pt
The initial release of the AWS IAM Role audit policy
n/a
> POL-291 - AWS IAM Role Audit

- README.md
- compliance/azure/azure_policy_audit/CHANGELOG.md
- compliance/azure/azure_policy_audit/README.md
- compliance/azure/azure_policy_audit/azure_policy_audit.pt
The initial release of the Azure Policy Audit policy template.
n/a
> POL-290 Azure Policy Audit

- operational/azure/vms_without_managed_disks/CHANGELOG.md
- operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
Fixes resource table rendering
> POL-338 : Fix Resource Table Rendering Issue

- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
POL 336 Error on Azure unused SQL databases policy
Error on Azure unused SQL databases policy
Fixed null error in script
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5f05987c91d86c0001f903a8
> POL 336 Error on Azure unused SQL databases policy

- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/README.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
Add Estimated Monthly Savings to incident details
POL-322
> AWS Idle Instances: add Estimated Monthly Savings

- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/README.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Add Estimated Cost Savings to incident 
POL-313
> AWS UAV: add Estimated Cost Savings

- cost/azure/instances_log_analitics_utilization/README.md
Incorrect permission for log analytics
It solves the 403 issue being faced by the user.
> POL-340-Incorrect permission for log analytics

- cost/azure/instances_log_analitics_utilization/README.md
This PR removes the extra permission mentioned in the readme file.
> Copy-POL-340-Incorrect permission for log analytics

- cost/google/old_snapshots/CHANGELOG.md
- cost/google/old_snapshots/google_delete_old_snapshots.pt
Add logic to skip projects with Compute API disabled.
n/a
> POL-342: GCP Snapshots - Ignore 403/404 on disabled API

- cost/azure/object_storage_optimization/README.md
- cost/google/unutilized_ip_addresses/CHANGELOG.md
- cost/google/unutilized_ip_addresses/README.md
- cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Updated logic to only capture external IPs
n/a
> POL-343: Google Unused IPs - Filter on External IPs only

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/README.md
- cost/budget_alerts/budget_alert.pt
POL-344-Budget-Alerts-w/-Billing-Center-Unallocated
Added filter condition to get value only for Parent BC.
> POL-344-Budget-Alerts-w/-Billing-Center-Unallocated

- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Fixes the broken tag exclusion logic
n/a
> POL-350 update tag exclusion logic

- CODEOWNERS
> removing codeowners

- cost/aws/s3_bucket_size/CHANGELOG.md
- cost/aws/s3_bucket_size/aws_bucket_size.pt
- cost/aws/schedule_instance/CHANGELOG.md
- cost/aws/schedule_instance/aws_schedule_instance.pt
- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
Fix descriptions that are not hiding hyperlinks
> fix descriptions

- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
> Copy-POL-262-AWS-Unused-IP

- compliance/google/unlabeled_resources/CHANGELOG.md
- compliance/google/unlabeled_resources/unlabeled_resources.pt
- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Google Unlabeled Resources & Azure Unused IP Addresses- Fix Readme link and space issue respectively
> POL-359 Google Unlabeled Resources & Azure Unused IP Addresses- Fix Readme link and space issue respectively

- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Updated azure_rightsize_sql_instance.pt and CHANGELOG.md
Resolved No Recommended capacity for Azure SQL Databases
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5f3e8919a1dbf80001e01964
> Fix for bug ID: POL-369-No-Recommended-Capacity-Azure-Rightsize-SQL-Databases

- cost/aws/unused_volumes/README.md
- cost/azure/unattached_volumes/README.md
> add policy savings details to readme

- operational/snapshots/CHANGELOG.md
- operational/snapshots/no_recent_snapshots.pt
POL-371 No Recent Snapshots - add state running
Modified Instance resources filter to get running instances having attached volumes that do not have a snapshot
Modified Instance resources filter to get running instances having attached volumes that do not have a snapshot
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5f4f9f0ba27fde000158aba1
> POL-371 No Recent Snapshots - add state running

- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
POL-374-Case-02200747-Azure-Hybrid-Use-Benefit-policy-script-execution-error
> Pol 374 case 02200747 azure hybrid use benefit policy script execution error

- cost/aws/instance_cloudwatch_utilization/CHANGELOG.md
- cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
Bugfix on duplicate records was displayed in the detail template
Applied policy link: https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5f561450a27fde000158b487
> Pol 375 duplicate resources aws inefficient instance utilization using cloud watch

- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/README.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
POL-323-Add-Savings-Azure-Idle-Compute-Instances- Added savings for Azure instances
> POL-323-Add-Savings-Azure-Idle-Compute-Instances

- cost/aws/unused_rds/CHANGELOG.md
- cost/aws/unused_rds/README.md
- cost/aws/unused_rds/unused_rds.pt
POL-327-Add-Savings-AWS-Unused-RDS- added estimated monthly savings
> POL-327-Add-Savings-AWS-Unused-RDS

- cost/aws/elb/clb_unused/CHANGELOG.md
- cost/aws/elb/clb_unused/README.md
- cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/README.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/README.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/README.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
POL-376-Update-add-savings-policy-to-handle-error-occurred-when-user-is-not-having-access-to-Optima--  updated policy to handle and show the error if the user is not having permission for fetching cost data from Optima
> POL-376-Update-add-savings-policy-to-handle-error-occurred-when-user-is-not-having-access-to-Optima

- cost/aws/elb/clb_unused/CHANGELOG.md
- cost/aws/elb/clb_unused/README.md
- cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/README.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/README.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
- cost/aws/unused_rds/CHANGELOG.md
- cost/aws/unused_rds/README.md
- cost/aws/unused_rds/unused_rds.pt
- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/README.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/README.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/README.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/README.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
POL-377-Update-Add-savings-policy-detail-message-and-savings-format- Modified policies to show if there is not enough cost data to calculate savings
> POL-377-Update-Add-savings-policy-detail-message-and-savings-format

- cost/azure/instances_log_analytics_utilization/CHANGELOG.md
- cost/azure/instances_log_analytics_utilization/README.md
- cost/azure/instances_log_analytics_utilization/azure_instance_log_analytics_utilization.pt
POL-381-Case-02213464-Azure-Inefficient-Instance-Utilization-using-Log-Analytics-execution-failure
This PR solves the below issue reported by user:
Summary:
script execution failed
Detail:
execution failed: TypeError: Cannot access member 'workspaceId' of undefined
> POL-381-Case-02213464-Azure-Inefficient-Instance-Utilization-using-Log-Analytics-execution-failure

- cost/azure/instances_log_analytics_utilization/CHANGELOG.md
- cost/azure/instances_log_analytics_utilization/azure_instance_log_analytics_utilization.pt
Added 404 ignore to handle workspace not found errors
Mars is seeing errors as Azure returns 'Workspace not found'
POL-386
> Added 404 ignore

- Dangerfile
check uppercase for first character in category
check uppercase for first character in category
> Updated Dangerfile to check uppercase for first character in category

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
POL-393-Case-0223312-Unused-IP-Address-shows-N/A-for-savings
The policy now fetches cost for each resources under all the azure subscription ids available from Optima
> POL-393-Case-0223312-Unused-IP-Address-shows-N/A-for-savings

- operational/vmware/instance_tag_sync/README.md
- operational/vmware/instance_tag_sync/changelog.md
- operational/vmware/instance_tag_sync/instance_tag_sync.pt
POL-394-VMWare-Tags-Sync-Policy:
updated policy to capture logs
> POL-394-VMWare-Tags-Sync-Policy

- cost/azure/reserved_instances/utilization/CHANGELOG.md
- cost/azure/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
Update the check logic to ensure RIs with 100% utilization aren't incorrectly identified in the incident.
Added min and max values to the utilization parameter to ensure values below 1 and over 100 cannot be specified.
Added section headings and reorganized data sources and scripts.
Fixed a handful of formatting issues.
n/a
> POL-397 - Azure Expiring Reserved Instances - Fix for 100% False-positive

- cost/low_service_usage/CHANGELOG.md
- cost/low_service_usage/low_service_usage.pt
Fixed date format issue and undefined 'name' issue
- Updated date format logic which was causing Error in policy execution on specific date.
- Removed extra code which was causing Error in policy execution for some use cases.
- Changed label and description for "report_instances" escalation to maintaining the consistency.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5fa428156ffc6c0001662881
> POL 399 unable to configure low service usage policy

- compliance/azure/subscription_access/CHANGELOG.md
- compliance/azure/subscription_access/azure_subscription_access.pt
Incorrectly referencing an undefined variable/property.
> Azure Subscription Access: Fix Role Assignment ID bug

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/scheduled_report.pt
Removing tabs allow the markdown to be processed.
Markdown is currently processed as text because of tabbing in the template.
> removing tabs from markdown block

- cost/billing_center_cost_anomaly/CHANGELOG.md
- cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
The report variable was defined as an object, so when no report data is available, the policy evaluation fails as it is expecting an array.
Also added back in the detail template as there was too much information in the summary template.
n/a
> Billing Center Cost Anomaly - Fix for Incorrect Variable Type and Missing Detail Template

- cost/instance_anomaly/CHANGELOG.md
- cost/instance_anomaly/README.md
- cost/instance_anomaly/instance_anomaly.pt
Fix for bug POL-412 error message with Running Instance Count policy
Modified policy template to collect instance id and formatted the template and README files.
> POL-412 error message with Running Instance Count policy

- .travis.yml
> Fix NPM version

- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
Fixes a bug in the **Budget Alert by Cloud Account** policy where the policy would fail to run due to a change in the way was account names are returned from the cloud vendor account name call.
Also refactored the billing center index call to instead only return the highest level billing centers the user has access to.
#653
> Budget Alert by Cloud Account - Fix Cloud Vendor Account name bug

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
Very small change, just to fix a typo in one of the labels, more or less (the "Run Rate" one).
https://jira.flexera.com/browse/POL-416
> POL-416: Run Rate label fixed.

- compliance/azure/azure_untagged_resources/CHANGELOG.md
- compliance/azure/azure_untagged_resources/untagged_resources.pt
> fix readme

- cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
- cost/azure/hybrid_use_benefit_linux/README.md
- cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
- Removed 2.0 from headline
- Changed links in README.md pointing to the correct links in Flexera docs
> Ahub for linux fixes

- cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
- cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
The filter also returned **windows** vms with ahub activated. Modified the filters in js part so that only RHEL and SLES eligible vms are returned.
Returning windows vms with ahub enabled
> changes for filter

- compliance/azure/azure_untagged_resources/CHANGELOG.md
- compliance/azure/azure_untagged_resources/untagged_resources.pt
- cost/low_account_usage/low_account_usage.pt
This change fixes an error in the policy "Low Account Usage" cost formatting that prevented billing center account names being processed
Updated Policy test
https://app.flexera.com/orgs/1105/policy/projects/60073/applied-policies/607956565583ee000141ff13
Resolves the issue https://jira.flexera.com/browse/POL-426
> Pol 426 policy low account usage

- cost/superseded_instance/CHANGELOG.md
- cost/superseded_instance/superseded_instance.pt
URL was incorrect, and there was a bug when comparing costs' cloud vendor account name and the name field in the list of cloud vendor accounts. Now fixed.
https://jira.flexera.com/browse/POL-428
> POL-428: Fixing superseded instances policy template.

- cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
- cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
corrected link to readme and changed the version to 2.0, also updated changelog
> updated doc link and version

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
- cost/low_service_usage/CHANGELOG.md
- cost/low_service_usage/low_service_usage.pt
Replacing built in rightscale auth for FlexeraOne OAuth2 creds 
https://jira.flexera.com/browse/IND-4269
> IND-4269: OAuth creds for low service usage

- cost/budget_v_actual/CHANGELOG.md
- cost/budget_v_actual/monthly_budget_v_actual.pt
Fixed the alignment of the markdown heredoc in the validation block. Any space in front of the markdown breaks the conversion
to HTML, causing the issue reported in the JIRA ticket.
https://jira.flexera.com/browse/POL-429
> POL-429: Fixed alignment in markdown heredoc, in validation

- README.md
- security/azure/webapp_tls_version_support/CHANGELOG.md
- security/azure/webapp_tls_version_support/README.md
- security/azure/webapp_tls_version_support/azure_webapp_min_tls_version.pt
This policy identified all Web Apps where the minimum TLS version is less than the policy parameter specified.
n/a
> POL-434: Azure Web App Minimum TLS Version

- package-lock.json
- package.json
updating trim to fix vulnerability issue.
https://github.com/flexera/policy_templates/security/dependabot/package-lock.json/trim/open
The version of trim used is vulnerable.
> Fix trim vuln

- README.md
- security/aws/vpcs_without_flow_logs_enabled/CHANGELOG.md
- security/aws/vpcs_without_flow_logs_enabled/README.md
- security/aws/vpcs_without_flow_logs_enabled/aws_vpcs_without_flow_logs_enabled.pt
This creates a new policy for checking whether or not flow logs are enabled. 
> POL-400 Check for VPCs without flow logs enabled

- README.md
- operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
- operational/aws/lambda_functions_with_high_error_rate/README.md
- operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
Adds a new policy for Lambda functions with high error rate
> POL-435 Lambda Functions with High Error Rate

- cost/aws/elb/clb_unused/aws_delete_unused_clb.pt
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
- cost/aws/schedule_instance/aws_schedule_instance.pt
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/old_snapshots/azure_delete_old_snapshots.pt
- cost/azure/schedule_instance/azure_schedule_instance.pt
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
- cost/google/schedule_instance/google_schedule_instance.pt
The `rightscale` built-in auth can't work in the EU app. Replace it (temporarily) with FlexeraOne OAuth2 credentials.
+ a few other EU-specific tweaks for the (AWS|Azure|Google) Schedule Instance templates.
https://jira.flexera.com/browse/CMLS-69
> CMLS-69: rightscale auth to FlexeraOne OAuth2 credentials.

- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
fixed markdown to remove whitespace
HTML formatting correctly in emails  
CMLS-66
> Cmls 66 budget alerts by account

- README.md
- cost/azure/storage_account_lifecycle_management/CHANGELOG.md
- cost/azure/storage_account_lifecycle_management/README.md
- cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
Policy to detect if a lifecycle management policy is not present. 
> SEG-664 Azure Lifecycle Management Policy

- security/aws/iam_prevent_password_reuse/CHANGELOG.md
- security/aws/iam_prevent_password_reuse/README.md
- security/aws/iam_prevent_password_reuse/iam_prevent_password_reuse.pt
Adds policy for verifying that the AWS password policy enforces not reusing passwords.
> POL-461 AWS Prevent Password Reuse

- README.md
- cost/aws/FlexeraReadOnlyPolicy.template
> POL-457 Adding CFT for ReadOnly rights

- cost/google/recommender/CHANGELOG.md
- cost/google/recommender/README.md
- cost/google/recommender/recommender.pt
> POL-464 Adding in Google Recommender Policy

- security/aws/iam_hwmfa_enabled_for_root/CHANGELOG.md
- security/aws/iam_hwmfa_enabled_for_root/aws_iam_hwmfa_enabled.pt
- security/aws/iam_mfa_enabled_for_iam_users/CHANGELOG.md
- security/aws/iam_mfa_enabled_for_iam_users/iam_mfa_enabled_for_iam_users.pt
- security/aws/iam_min_password_length/CHANGELOG.md
- security/aws/iam_min_password_length/iam_min_password_length.pt
- security/aws/iam_no_root_access_keys/CHANGELOG.md
- security/aws/iam_no_root_access_keys/aws_iam_no_root_access_keys.pt
- security/aws/iam_no_root_for_tasks/CHANGELOG.md
- security/aws/iam_no_root_for_tasks/iam_no_root_for_tasks.pt
- security/aws/iam_prevent_password_reuse/CHANGELOG.md
- security/aws/iam_prevent_password_reuse/iam_prevent_password_reuse.pt
- security/aws/iam_rotate_access_keys/CHANGELOG.md
- security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Updated Changelogs and metadata for various AWS IAM policies.
> fixed version numbers and metadata

- cost/google/recommender/CHANGELOG.md
- cost/google/recommender/README.md
- cost/google/recommender/recommender.pt
> Google Recommender Policy - Updating short description

- security/aws/iam_rotate_access_keys/CHANGELOG.md
- security/aws/iam_rotate_access_keys/iam_rotate_access_keys.pt
Fixed a small issue in iam_rotate_access_keys.pt where the incident email contained text pasted from another policy that was not changed to fit this policy.
> IAM Rotate Access Keys - Fix Subject Header

- compliance/azure/azure_untagged_resources/README.md
Updating the readme with permissions details
> Update readme tag permissions

- README.md
- security/aws/s3_ensure_buckets_block_public_access/CHANGELOG.md
- security/aws/s3_ensure_buckets_block_public_access/README.md
- security/aws/s3_ensure_buckets_block_public_access/s3_ensure_buckets_block_public_access.pt
Adds CIS policy for AWS S3 Ensure 'Block Public Access' Configured For All Buckets
> Adds CIS policy for AWS S3 Ensure 'Block Public Access' Configured For All Buckets

- README.md
- security/aws/ebs_ensure_encryption_default/CHANGELOG.md
- security/aws/ebs_ensure_encryption_default/README.md
- security/aws/ebs_ensure_encryption_default/ebs_ensure_encryption_default.pt
Adds AWS CIS policy for 2.2.1 Ensure EBS volume encryption is enabled
> Adds AWS CIS policy for 2.2.1 Ensure EBS volume encryption is enabled

- Rakefile
- tools/policy_sync/CHANGELOG.md
- tools/policy_sync/policy_sync.pt
> POL-502 Adding branch feature to Policy Sync

- .github/workflows/update_eu_policies.yml
Adding a workflow to auto update eu branch. 
> Adding EU Update Action

- .github/workflows/update_eu_policies.yml
- cost/scheduled_reports/README.md
> recursive and fixes

- .github/workflows/update_eu_policies.yml
- cost/scheduled_reports/README.md
> Fix docs change merge

- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/README.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
> POL-513 Adding param_subscription_whitelist to Azure Unattached Volumes

- .gitattributes
- Gemfile
- Gemfile.lock
> Updating GitAttributes for binary files, and upgrading danger

- README.md
- security/aws/iam_one_active_key_per_user/CHANGELOG.md
- security/aws/iam_one_active_key_per_user/README.md
- security/aws/iam_one_active_key_per_user/iam_one_active_key_per_user.pt
Adds policy for AWS IAM CIS 1.13 Ensure One Active Key Per IAM User
> Adds policy for AWS IAM CIS 1.13 Ensure One Active Key Per IAM User

- README.md
- security/aws/iam_users_perms_via_groups_only/CHANGELOG.md
- security/aws/iam_users_perms_via_groups_only/README.md
- security/aws/iam_users_perms_via_groups_only/iam_users_perms_via_groups_only.pt
Policy for AWS CIS IAM 1.15 Ensure IAM Users Receive Permissions Only Through Groups
> Policy for AWS CIS IAM 1.15 Ensure IAM Users Receive Permissions Only Through Groups

- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/README.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
Added subscription filter option and ability to specify Azure API endpoint to the cost/azure/hybrid_use_benefit policy.
> cost/azure/hybrid_use_benefit: Added subscription filter option and ability to specify Azure API endpoint

- cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
- cost/azure/hybrid_use_benefit_linux/README.md
- cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
cost/azure/hybrid_use_benefit_linux: Added subscription filter option and ability to specify Azure API endpoint
> cost/azure/hybrid_use_benefit_linux: Added subscription filter option and ability to specify Azure API endpoint 

- cost/azure/old_snapshots/CHANGELOG.md
- cost/azure/old_snapshots/README.md
- cost/azure/old_snapshots/azure_delete_old_snapshots.pt
cost/azure/old_snapshots: Added subscription filter option and ability to specify Azure API endpoint
> cost/azure/old_snapshots: Added subscription filter option and ability to specify Azure API endpoint

- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/README.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
Add Subscription Filtering To cost/azure/rightsize_sql_instances
> Add Subscription Filtering To cost/azure/rightsize_sql_instances

- cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
- cost/azure/hybrid_use_benefit_sql/README.md
- cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
cost/azure/hybrid_use_benefit_sql: Added subscription filter option and ability to specify Azure API endpoint
> cost/azure/hybrid_use_benefit_sql: Added subscription filter option and ability to specify Azure API endpoint

- cost/azure/schedule_instance/CHANGELOG.md
- cost/azure/schedule_instance/README.md
- cost/azure/schedule_instance/azure_schedule_instance.pt
OOTB Policies: Add Subscription Filtering To cost/azure/schedule_instance
> OOTB Policies: Add Subscription Filtering To cost/azure/schedule_instance

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/README.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
POL-527 Add Subscription Whitelist to Unused IP Addresses
> POL-527 Add Subscription Whitelist to Unused IP Addresses

- cost/azure/storage_account_lifecycle_management/CHANGELOG.md
- cost/azure/storage_account_lifecycle_management/README.md
- cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
OOTB Policies: Add Subscription Filtering To cost/azure/storage_account_lifecycle_management
> POL-529 Add Subscription Filtering To cost/azure/storage_account_lifecycle_management

- cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
- cost/azure/reserved_instances/mca_recommendations/README.md
- cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
OOTB Policies: Add Subscription Filtering To cost/azure/reserved_instances/mca_recommendations
> OOTB Policies: Add Subscription Filtering To cost/azure/reserved_instances/mca_recommendations

- package-lock.json
- package.json
> Removing eclint per issue: https://github.com/jedmao/eclint/issues/226

- .github/workflows/update_eu_policies.yml
> Adding Labels

- operational/azure/azure_certificates/CHANGELOG.md
- operational/azure/azure_certificates/README.md
- operational/azure/azure_certificates/azure_certificates.pt
OOTB Policies: Add Subscription Filtering To operational/azure/azure_certificates
> POL-531: Add Subscription Filtering To operational/azure/azure_certificates

- operational/azure/azure_sql_using_elastic_pool/README.md
- operational/azure/azure_sql_using_elastic_pool/azure_sql_instances_without_elastic_pools.pt
- operational/azure/azure_sql_using_elastic_pool/changelog.md
OOTB Policies: Add Subscription Filtering To operational/azure/azure_sql_using_elastic_pool
> POL-532: Add Subscription Filtering To operational/azure/azure_sql_using_elastic_pool

- operational/azure/sync_tags_with_optima/CHANGELOG.md
- operational/azure/sync_tags_with_optima/README.md
- operational/azure/sync_tags_with_optima/sync_azure_tags.pt
OOTB Policies: Add Subscription Filtering To operational/azure/sync_tags_with_optima
> POL-533: Add Subscription Filtering To operational/azure/sync_tags_with_optima

- operational/azure/vms_without_managed_disks/CHANGELOG.md
- operational/azure/vms_without_managed_disks/README.md
- operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
OOTB Policies: Add Subscription Filtering To operational/azure/vms_without_managed_disks
> POL-534: Add Subscription Filtering To operational/azure/vms_without_managed_disks

- security/storage/azure/storage_account_https_enabled/CHANGELOG.md
- security/storage/azure/storage_account_https_enabled/README.md
- security/storage/azure/storage_account_https_enabled/azure_storage_account_https_enabled.pt
OOTB Policies: Add Subscription Filtering To security/storage/azure/storage_account_https_enabled
> OOTB Policies: Add Subscription Filtering To security/storage/azure/storage_account_https_enabled

- compliance/tags/azure_rg_tags/CHANGELOG.md
- compliance/tags/azure_rg_tags/README.md
- compliance/tags/azure_rg_tags/azure_resource_group_tags.pt
OOTB Policies: Add Subscription Filtering To compliance/tags/azure_rg_tags
> OOTB Policies: Add Subscription Filtering To compliance/tags/azure_rg_tags

- compliance/azure/subscription_access/CHANGELOG.md
- compliance/azure/subscription_access/README.md
- compliance/azure/subscription_access/azure_subscription_access.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/subscription_access
> OOTB Policies: Add Subscription Filtering To compliance/azure/subscription_access

- security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
- security/azure/sql_publicly_accessible_managed_instance/README.md
- security/azure/sql_publicly_accessible_managed_instance/check_for_publicly_accessible_azure_sql_managed_instance.pt
OOTB Policies: Add Subscription Filtering To security/azure/sql_publicly_accessible_managed_instance
> OOTB Policies: Add Subscription Filtering To security/azure/sql_publicly_accessible_managed_instance

- security/azure/resources_with_public_ip_address/CHANGELOG.md
- security/azure/resources_with_public_ip_address/README.md
- security/azure/resources_with_public_ip_address/azure_open_ip_address_policy.pt
OOTB Policies: Add Subscription Filtering To security/azure/resources_with_public_ip_address
> OOTB Policies: Add Subscription Filtering To security/azure/resources_with_public_ip_address

- security/azure/webapp_tls_version_support/CHANGELOG.md
- security/azure/webapp_tls_version_support/README.md
- security/azure/webapp_tls_version_support/azure_webapp_min_tls_version.pt
OOTB Policies: Add Subscription Filtering To security/azure/webapp_tls_version_support
> OOTB Policies: Add Subscription Filtering To security/azure/webapp_tls_version_support

- compliance/azure/ahub_manual/CHANGELOG.md
- compliance/azure/ahub_manual/README.md
- compliance/azure/ahub_manual/azure_ahub_utilization_with_manual_entry.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/ahub_manual
(Also fixed a couple bugs/issues with the existing policy. In particular, the export was not working properly)
> OOTB Policies: Add Subscription Filtering To compliance/azure/ahub_manual

- compliance/azure/azure_disallowed_regions/CHANGELOG.md
- compliance/azure/azure_disallowed_regions/README.md
- compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/azure_disallowed_regions
(Also cleaned up the policy a bit to match best practices)
> OOTB Policies: Add Subscription Filtering To compliance/azure/azure_disallowed_regions

- compliance/azure/azure_long_stopped_instances/CHANGELOG.md
- compliance/azure/azure_long_stopped_instances/README.md
- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/azure_long_stopped_instances
(Also some minor cleanup)
> OOTB Policies: Add Subscription Filtering To compliance/azure/azure_long_stopped_instances

- compliance/azure/compliance_score/CHANGELOG.md
- compliance/azure/compliance_score/README.md
- compliance/azure/compliance_score/azure_regulatory_compliance_report.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/compliance_score
(Also added 400 to the ignore_status on line 98 since this might be a valid API response)
> OOTB Policies: Add Subscription Filtering To compliance/azure/compliance_score

- compliance/azure/azure_policy_audit/CHANGELOG.md
- compliance/azure/azure_policy_audit/README.md
- compliance/azure/azure_policy_audit/azure_policy_audit.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/azure_policy_audit
> OOTB Policies: Add Subscription Filtering To compliance/azure/azure_policy_audit

- compliance/azure/azure_untagged_resources/CHANGELOG.md
- compliance/azure/azure_untagged_resources/README.md
- compliance/azure/azure_untagged_resources/untagged_resources.pt
OOTB Policies: Add Subscription Filtering To compliance/azure/azure_untagged_resources
> OOTB Policies: Add Subscription Filtering To compliance/azure/azure_untagged_resources

- .textlintrc
- compliance/azure/instances_without_fnm_agent/CHANGELOG.md
- compliance/azure/instances_without_fnm_agent/README.md
- compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent.pt
- package.json
[OOTB Policies: Add Subscription Filtering To compliance/azure/instances_without_fnm_agent
> OOTB Policies: Add Subscription Filtering To compliance/azure/instances_without_fnm_agent

- .travis.yml
> updating travis

- README.md
- security/aws/log_ensure_cloudtrail_multiregion/CHANGELOG.md
- security/aws/log_ensure_cloudtrail_multiregion/README.md
- security/aws/log_ensure_cloudtrail_multiregion/log_ensure_cloudtrail_multiregion.pt
Adds policy for AWS CIS Logging 3.1 Ensure CloudTrail is enabled in all regions
> AWS CIS Logging 3.1 Ensure CloudTrail is enabled in all regions

- README.md
- security/aws/kms_rotation/CHANGELOG.md
- security/aws/kms_rotation/README.md
- security/aws/kms_rotation/kms_rotation.pt
Adds a policy for AWS CIS 3.8 Ensure rotation for customer created CMKs is enabled
> AWS CIS 3.8 Ensure rotation for customer created CMKs is enabled

- README.md
- security/aws/log_ensure_cloudtrail_bucket_object_logging/CHANGELOG.md
- security/aws/log_ensure_cloudtrail_bucket_object_logging/README.md
- security/aws/log_ensure_cloudtrail_bucket_object_logging/log_ensure_cloudtrail_bucket_object_logging.pt
Adds policy that covers the following:
AWS CIS 3.10 Ensure that Object-level logging for write events is enabled for S3 bucket.
AWS CIS 3.11 Ensure that Object-level logging for read events is enabled for S3 bucket.
> POL-519 - AWS CIS Ensure that Object-level logging for read and write events is enabled for S3  bucket 

- cost/aws/gp3_volume_upgrade/CHANGELOG.md
- cost/aws/gp3_volume_upgrade/README.md
- cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt
- Improve savings calculations based on pricing from the AWS Pricing API
- Determine Enterprise Discount Program ratio based on Optima costs or a parameter
- Support upgrading from io2 volumes as well
FINOPS-119
> FINOPS-119 Improve AWS Upgrade to GP3

- .github/workflows/generate-policy-list.yaml
- .github/workflows/test-policies.yaml
- .github/workflows/upload-files.yaml
- .travis.yml
Trying to evaluate the migration to GitHub Actions.
> feat: Migrate to GitHub Actions

- .github/workflows/upload-files.yaml
> SEG-887 - Updating ACL

- compliance/google/long_stopped_instances/CHANGELOG.md
- compliance/google/long_stopped_instances/google_long_stopped_instances.pt
- policy_templates.code-workspace
SEG-788 Fixing Long-Stopped Instances to report instances with uptime
> SEG-788 Fixing Long-Stopped Instances to report instances with uptime

- compliance/azure/ahub_manual/CHANGELOG.md
- compliance/azure/ahub_manual/azure_ahub_utilization_with_manual_entry.pt
- cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
- cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
- cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
- cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/storage_account_lifecycle_management/CHANGELOG.md
- cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
- security/azure/sql_publicly_accessible_managed_instance/CHANGELOG.md
- security/azure/sql_publicly_accessible_managed_instance/check_for_publicly_accessible_azure_sql_managed_instance.pt
- security/azure/webapp_tls_version_support/CHANGELOG.md
- security/azure/webapp_tls_version_support/azure_webapp_min_tls_version.pt
> POL-557 - Update Azure Policies to ignore non-Azure Subscriptions

- saas/fsm/inactive_users_for_integrated_apps/CHANGELOG.md
- saas/fsm/inactive_users_for_integrated_apps/inactive_users_for_integrated_apps.pt
> POL-559 Update SaaS Manager Inactive Users for Integrated Apps

- .github/workflows/cfn-lint.yaml
- cost/aws/FlexeraReadOnlyPolicy.template
Adding pricing:GetProducts to ReadOnly cft
> Adding pricing:GetProducts to ReadOnly cft

- .vscode/settings.json
Added globbing for better WSL2 support for the .vscode folder.
> added WSL2 support

- saas/fsm/suspicious_users/CHANGELOG.md
- saas/fsm/suspicious_users/fsm-suspicious_users.pt
> POL-560 Update SaaS Manager - Suspicious Users - email field and pagination fix

- cost/aws/reserved_instances/recommendations/CHANGELOG.md
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
- cost/aws/savings_plan/recommendations/CHANGELOG.md
- cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
Patch to fix version number in .pt file
Fixed wrong version number in .pt file
> Lawrethao patch pol 554

- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
- Removed ds_session and synced ds_billing_center from budget alert
> POL-569 Removed ds_session and synced ds_billing_center

- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/README.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/old_snapshots/CHANGELOG.md
- cost/aws/old_snapshots/README.md
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
- cost/aws/unused_rds/CHANGELOG.md
- cost/aws/unused_rds/README.md
- cost/aws/unused_rds/unused_rds.pt
- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/README.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/README.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/old_snapshots/CHANGELOG.md
- cost/azure/old_snapshots/README.md
- cost/azure/old_snapshots/azure_delete_old_snapshots.pt
- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/README.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/README.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/README.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Updates fields for azure cost policies to make them ready for spend recommendations
These changes resolve issues with field mappings in certain Azure cost policy templates
> Pol 563 Make Azure policies ready for spend recommendations

- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
> Pol 569 correcting top level billing center

- README.md
- operational/bill_processing_errors_notification/CHANGELOG.md
- operational/bill_processing_errors_notification/README.md
- operational/bill_processing_errors_notification/bill_processing_errors_notification.pt
> POL-579 Bill Processing Status Policy

- README.md
- compliance/fnms/missing_active_machines/CHANGELOG.md
- compliance/fnms/missing_active_machines/README.md
- compliance/fnms/missing_active_machines/missing_active_machines.pt
> POL-585 ITAM Missing Active Machines

- operational/bill_processing_errors_notification/README.md
> Updated Documentation

- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
Fixes for Budget Alerts by Cloud Account policy
- Fixed issue with currentSpend subtracting 3 days unnecessarily
- Fixed issue with incorrect API endpoint
> Pol 589 budget alert issue

- README.md
- security/azure/guest_users/CHANGELOG.md
- security/azure/guest_users/README.md
- security/azure/guest_users/guest_users.pt
Azure CIS 1.3 Ensure guest users are reviewed on a monthly basis
> Azure CIS 1.3 Ensure guest users are reviewed on a monthly basis

- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
> Pol 596 rs optima host keyword

- README.md
- security/azure/security_contact_email/CHANGELOG.md
- security/azure/security_contact_email/README.md
- security/azure/security_contact_email/security_contact_email.pt
Azure CIS 2.13 Ensure 'Additional email addresses' is Configured with a Security Contact Email
(Tested and works)
> Azure CIS 2.13 Ensure 'Additional email addresses' is Configured with a Security Contact Email

- README.md
- security/azure/secure_transfer_required/CHANGELOG.md
- security/azure/secure_transfer_required/README.md
- security/azure/secure_transfer_required/secure_transfer_required.pt
Azure CIS 3.1 Ensure that 'Secure transfer required' is set to 'Enabled'
Tested and works.
> Azure CIS 3.1 Ensure that 'Secure transfer required' is set to 'Enabled'

- README.md
- security/azure/queue_storage_logging/CHANGELOG.md
- security/azure/queue_storage_logging/README.md
- security/azure/queue_storage_logging/queue_storage_logging.pt
Azure CIS 3.3 Ensure Storage Logging is Enabled for Queue Service for 'Read', 'Write', and 'Delete' requests
Tested and works as expected.
> Azure CIS 3.3 Ensure Storage Logging is Enabled for Queue Service for 'Read', 'Write', and 'Delete' requests

- README.md
- security/azure/private_blob_containers/CHANGELOG.md
- security/azure/private_blob_containers/README.md
- security/azure/private_blob_containers/private_blob_containers.pt
3.5 Ensure that 'Public access level' is set to Private for blob containers 
Tested and works fine.
> 3.5 Ensure that 'Public access level' is set to Private for blob containers 

- README.md
- security/azure/storage_trusted_services/CHANGELOG.md
- security/azure/storage_trusted_services/README.md
- security/azure/storage_trusted_services/storage_trusted_services.pt
Azure CIS 3.7 Ensure 'Trusted Microsoft Services' are Enabled for Storage Account Access
Tested and verified
> Azure CIS 3.7 Ensure 'Trusted Microsoft Services' are Enabled for Storage Account Access

- README.md
- security/azure/storage_soft_delete/CHANGELOG.md
- security/azure/storage_soft_delete/README.md
- security/azure/storage_soft_delete/storage_soft_delete.pt
Azure CIS 3.8 Ensure Soft Delete is Enabled for Azure Storage
tested and works
> POL-608 Azure CIS 3.8 Ensure Soft Delete is Enabled for Azure Storage

- operational/applied_policy_error_notification/CHANGELOG.md
- operational/applied_policy_error_notification/applied_policy_error_notification.pt
> POL-615 Adding rs_governance_host

- README.md
- security/azure/sql_server_auditing/CHANGELOG.md
- security/azure/sql_server_auditing/README.md
- security/azure/sql_server_auditing/sql_server_auditing.pt
Azure CIS 4.1.1 Ensure that 'Auditing' is set to 'On'
Tested and working
> Azure CIS 4.1.1 Ensure that 'Auditing' is set to 'On'

- cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
- cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
> Pol 619 adding subscription name

- README.md
- security/azure/sql_server_va/CHANGELOG.md
- security/azure/sql_server_va/README.md
- security/azure/sql_server_va/sql_server_va.pt
Azure CIS 4.2.2 Ensure that Vulnerability Assessment (VA) is enabled on a SQL server by setting a Storage Account
Tested and works
> Azure CIS 4.2.2 Ensure that Vulnerability Assessment (VA) is enabled on a SQL server by setting a Storage Account

- cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
- cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
Added 4 attributes to policy output: instanceFlexibilityGroup, instanceFlexibilityRatio, normalizedSize and recommendedQuantityNormalized
> POL-620 Update Azure RI Recommendations (Add Instance Group attributes)

- README.md
- security/azure/sql_server_va_admins/CHANGELOG.md
- security/azure/sql_server_va_admins/README.md
- security/azure/sql_server_va_admins/sql_server_va_admins.pt
- security/azure/sql_server_va_emails/CHANGELOG.md
- security/azure/sql_server_va_emails/README.md
- security/azure/sql_server_va_emails/sql_server_va_emails.pt
4.2.4 Ensure that VA setting 'Send scan reports to' is configured for a SQL server
4.2.5 Ensure that Vulnerability Assessment Setting 'Also send email 
notifications to admins and subscription owners' is Set for Each SQL 
Server
Both in the same pull request because they are extremely similar. Both tested and working.
> Azure CIS 4.2.4 4.2.5

- README.md
- security/azure/sql_ad_admin/CHANGELOG.md
- security/azure/sql_ad_admin/README.md
- security/azure/sql_ad_admin/sql_ad_admin.pt
Azure CIS 4.5 Ensure that Azure Active Directory Admin is configured
tested and working
> Azure CIS 4.5 Ensure that Azure Active Directory Admin is configured

- README.md
- security/azure/mysql_ssl/CHANGELOG.md
- security/azure/mysql_ssl/README.md
- security/azure/mysql_ssl/mysql_ssl.pt
Azure CIS 4.4.1 Ensure 'Enforce SSL connection' is set to 'Enabled' for Standard MySQL Database Server
Tested and working
> Azure CIS 4.4.1 Ensure 'Enforce SSL connection' is set to 'Enabled' for Standard MySQL Database Server

- README.md
- security/azure/pg_infra_encryption/CHANGELOG.md
- security/azure/pg_infra_encryption/README.md
- security/azure/pg_infra_encryption/pg_infra_encryption.pt
Azure CIS 4.3.8 Ensure 'Infrastructure double encryption' for PostgreSQL Database Server is 'Enabled'
Tested and working.
> Azure CIS 4.3.8 Ensure 'Infrastructure double encryption' for PostgreSQL Database Server is 'Enabled'

- cost/azure/instances_log_analytics_utilization/CHANGELOG.md
- cost/azure/instances_log_analytics_utilization/README.md
- cost/azure/instances_log_analytics_utilization/azure_instance_log_analytics_utilization.pt
Adds parameter for setting Timespan of query
Removes the hardcoded timespan that currently exists in the template
> POL-663 Update Azure Inefficient Instance Utilization using Log Analytics

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
added new check to verify that natGateway field is also null
Fixes issue of pulling used IP resources as if they were unused and deleting them
> POL-667 update with new check for non-empty ips

- cost/aws/savings_plan/expiration/CHANGELOG.md
- cost/aws/savings_plan/expiration/README.md
- cost/aws/savings_plan/expiration/aws_savings_plan_expiration.pt
- cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
Creates new policy that creates an incident and notifies if a savings plan expires will expire within a set period of time
fixes issue of no policy with this functionality
> Pol 582 aws sp expiration

- cost/aws/savings_plan/recommendations/CHANGELOG.md
- cost/aws/savings_plan/recommendations/README.md
- cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
add SageMaker option to savings plan recommendations
Resolves issue of not being able to run policy for SageMaker
> Pol 652 Savings Plan SageMaker

- cost/aws/idle_compute_instances/idle_compute_instances.pt
- Fixes Linux Memory Metrics Collection
- Removes `body_string` and instead converts body to string when building request object
> fix linux memory

- cost/aws/old_snapshots/CHANGELOG.md
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
- Modified Image (AMI) datasource collection to improve policy efficiency
- Modified "Delete Snapshots" Escalation Action to improve execution efficiency
> AWS Old Snapshots v3.4 - Improve efficiency

- operational/aws/total_instance_vcpus/README.md
Updated "What it does" section - replaced "Total Instance Hours" with "Total Instance vCPUs"
> POL-678 Update AWS Number of Instance vCPUs Used README

- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
This change updates the Azure Unused volumes policy to reduce the time and number of api calls to azure insights
This fixes issues of timeouts for clients past the 2 hour mark
> POL-675 - Optimize Azure Unattached Volumes

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Optimize policy to make fewer API calls to Azure. Also, add a new ipAddress field to the policy incident export. 
> POL-677 Optimize Azure Unused IP Addresses 

- cost/azure/reserved_instances/utilization/CHANGELOG.md
- cost/azure/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
updated template to
- add a parameter for 7/30 days utilization lookback
- get details on reservation amounts from Azure
- add description in policy incident summary to show total wasted spend
- changed default frequency to weekly
> POL-682 Update Azure Reserved Instance Utilization

- cost/aws/savings_plan/utilization/CHANGELOG.md
- cost/aws/savings_plan/utilization/README.md
- cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
- cost/aws/savings_realized/CHANGELOG.md
- cost/aws/savings_realized/README.md
- cost/aws/savings_realized/aws_savings_realized.pt
- cost/azure/savings_realized/CHANGELOG.md
- cost/azure/savings_realized/README.md
- cost/azure/savings_realized/azure_savings_realized.pt
- cost/forecasting/commitment_forecast/CHANGELOG.md
- cost/forecasting/commitment_forecast/README.md
- cost/forecasting/commitment_forecast/commitment_forecast.pt
- cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md
- cost/forecasting/straight_line_forecast/linear_regression/README.md
- cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt
- cost/forecasting/straight_line_forecast/simple/CHANGELOG.md
- cost/forecasting/straight_line_forecast/simple/README.md
- cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
- operational/aws/total_instance_hours/CHANGELOG.md
- operational/aws/total_instance_hours/README.md
- operational/aws/total_instance_hours/number_of_hours_per_instance_family.pt
- operational/aws/total_instance_hours_forecast/CHANGELOG.md
- operational/aws/total_instance_hours_forecast/README.md
- operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt
- operational/aws/total_instance_vcpus/CHANGELOG.md
- operational/aws/total_instance_vcpus/README.md
- operational/aws/total_instance_vcpus/number_of_vcpus_per_instance_family.pt
- operational/aws/total_instance_vcpus_forecast/CHANGELOG.md
- operational/aws/total_instance_vcpus_forecast/README.md
- operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
> POL-697 Deprecate Authentication - Forecast and Usage Report policies

- cost/aws/reserved_instances/recommendations/CHANGELOG.md
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
- cost/aws/savings_plan/recommendations/CHANGELOG.md
- cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
- cost/google/cud_recommendations/CHANGELOG.md
- cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
- cost/google/idle_ip_address_recommendations/CHANGELOG.md
- cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
- Update google policies with correct policy_set
- Update the AWS RI and Savings Plan recommendations to have consistency with the Credential auth_flexera. 
> Google policy set & correct auth_rs -> auth_flexera

- .github/workflows/cfn-publish.yaml
- .github/workflows/cfn-test.yaml
- Dangerfile
- tools/cloudformation-template/FlexeraAutomationPolicies.template
- tools/cloudformation-template/README.md
- tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.1.0.template
Adds CloudFormation Template which can be used to create IAM Role and IAM Permission resources used by Flexera Automation Policies
Preview Docs/Template here: [./tools/cloudformation-template/](https://github.com/flexera-public/policy_templates/tree/feat/bk/add_cloudformation_template/tools/cloudformation-template)
> feat: Add CloudFormation Template

- cost/billing_center_cost_anomaly/CHANGELOG.md
- cost/billing_center_cost_anomaly/billing_center_cost_anomaly.pt
- cost/cloud_cost_anomalies/README.md
updates documentation to reflect policies state more accurately for cloud cost anomalies and billing center anomalies
fixes issues of UI deprecation display and for more uniform readme documentation
> cloud cost anomalies readme update & billing cost anomalies update

- README.md
- cost/cloud_cost_anomalies/CHANGELOG.md
- cost/cloud_cost_anomaly_alerts/CHANGELOG.md
- cost/cloud_cost_anomaly_alerts/README.md
- cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
fixes an issue with duplicate dimension parameter and removes a non-standard dimension parameter in operating system
fixes erroring due to unavailable dimension parameter and issues of being unable to query with Cloud Vender Account
> POL-724 Cloud Cost Anomaly bugfixes

- cost/cloud_cost_anomaly_alerts/CHANGELOG.md
- cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
change incident field cost metric to more readable value
makes incident reports more redable
> POL-711 Cost Anomaly alerts cost metric update

- .github/workflows/cfn-publish.yaml
Fixes error when more than one release exists: https://github.com/flexera-public/policy_templates/actions/runs/3568760946
> fix: .github/workflows/cfn-publish.yaml

- README.md
- cost/azure/rightsize_compute_instances/CHANGELOG.md
- cost/azure/rightsize_compute_instances/README.md
- cost/azure/rightsize_compute_instances/azure_compute_rightisizing.pt
> POL-692 Azure Instance Rightsizing - Merge Idle Instances and Inefficient Instance Utilization

- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/README.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
This change updates the logic for determining if a volume is being unused in the activity log datasource call
fixes issue of flagging volumes incorrectly as unused
> POL-730 Azure Unused Volumes bugfix

- cost/google/cud_recommendations/CHANGELOG.md
- cost/google/cud_recommendations/README.md
- cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
changes recommendation type from usage reduction to a rate reduction recommendation
Solves issue of incorrect categorization of policy
> Ind 5643 Google CUD recommendation type change

- cost/azure/reserved_instances/utilization/CHANGELOG.md
- cost/azure/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
> POL-716 Update Azure Reserved Instance Utilization

- README.md
- cost/azure/azure_china_cbi/CHANGELOG.md
- cost/azure/azure_china_cbi/README.md
- cost/azure/azure_china_cbi/azure_china_cbi.pt
Add new policy for Azure Chine Common Bill Ingestion
> POL-714 Add Azure China Common Bill Ingestion

- .idea/inspectionProfiles/Project_Default.xml
- data/aws/instance_types.json
HCLIND-22 added aws instance types
> HCLIND-22 added aws instance types

- tools/cloudformation-template/FlexeraAutomationPolicies.template
- tools/cloudformation-template/README.md
- tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.2.0.template
- [feat: Add paramPermsAttachExistingPolicies](https://github.com/flexera-public/policy_templates/commit/71923a0dbca38409a1bbfb34c62feb0b79cd4f76)
- [feat: Add support for app.flexera.au](https://github.com/flexera-public/policy_templates/commit/a44f9f81cd5b1a95edc0ae2ee9c54dae39918060)
- [feat: Add new RDS perms for AWS Old Snapshots PT](https://github.com/flexera-public/policy_templates/commit/161053b6ed31404b8b4989cce2fe40c0c92b82ca)
Delivers https://flexera.atlassian.net/browse/POL-749
> POL-749 - feat: Attach existing IAM Policy Permissions

- cost/aws/rds_instance_cloudwatch_utilization/README.md
Credential information in README.md was incorrect, so I fixed it. No changes to the policy itself.
> README.md Fix

- compliance/azure/azure_long_stopped_instances/CHANGELOG.md
- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
- compliance/azure/azure_untagged_resources/CHANGELOG.md
- compliance/azure/azure_untagged_resources/untagged_resources.pt
- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
- cost/azure/hybrid_use_benefit_linux/CHANGELOG.md
- cost/azure/hybrid_use_benefit_linux/ahub_linux.pt
- cost/azure/hybrid_use_benefit_sql/CHANGELOG.md
- cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/old_snapshots/CHANGELOG.md
- cost/azure/old_snapshots/azure_delete_old_snapshots.pt
- cost/azure/schedule_instance/CHANGELOG.md
- cost/azure/schedule_instance/azure_schedule_instance.pt
- cost/azure/unattached_volumes/CHANGELOG.md
- cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
- cost/azure/unused_sql_databases/CHANGELOG.md
- cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
- operational/azure/vms_without_managed_disks/CHANGELOG.md
- operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks.pt
Ignore status 400, 403, and 404 which can be returned in certain (legacy) types of Azure Subscriptions
https://flexera.atlassian.net/browse/POL-754
> POL-754 - Improve exception handling azure

- README.md
- operational/azure/azure_long_running_instances/CHANGELOG.md
- operational/azure/azure_long_running_instances/README.md
- operational/azure/azure_long_running_instances/azure_long_running_instances.pt
Added Azure Long Running Instances policy equivalent to AWS.
Feature parity; customer (HMRC) requested but only available for AWS
> HCLIND-3 Add Azure long running instances

- README.md
Update toplevel README to update link to CloudFormation Template
> docs: update link to CloudFormation Template

- cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
Added Meta Policy for new AWS Rightsize Compute Instances policy, see https://github.com/flexera-public/policy_templates/pull/1140 
> POL-693 AWS Instance Rightsizing - Add Meta Policy

- cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
- cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
> HCLIND-48 Fix SubscriptionName empty

- compliance/azure/instances_without_fnm_agent/CHANGELOG.md
- compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent.pt
Added conversions of names to a single character case before comparison
[[HCLIND-21] Policy Incident including instances with an agent installed](https://flexera.atlassian.net/browse/HCLIND-21)
> HCLIND-21 Case-insensitive matching of computerName from report with Azure VM name

- README.md
- cost/aws/rightsize_ebs_volumes/CHANGELOG.md
- cost/aws/rightsize_ebs_volumes/README.md
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
Add first iteration of rightsizing policy for AWS EBS Volumes
Adds functionality for optimizing gp2 volumes by providing recommendation and dollar saving amount for moving to gp3 volume type
> POL-752 Add AWS Rightsize Disks (EBS Volumes)

- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
initial commit
Adds new meta policy for new AWS Rightsize EBS Volumes policy
Allows new AWS Rightsize EBS Volumes policy to be run across multiple AWS accounts that a customer may have
> POL-752 AWS Rightsize EBS Volumes - Add Meta Policy

- data/azure/azure_vm_pricing.py
Fixed issue where many Linux instance types were missing
> Azure price fix

- README.md
- security/azure/sql_server_va_scans/CHANGELOG.md
- security/azure/sql_server_va_scans/README.md
- security/azure/sql_server_va_scans/sql_server_va_scans.pt
Azure CIS 4.2.3 Ensure that VA setting 'Periodic recurring scans' to 'on' for each SQL server
Tested and working
> Azure CIS 4.2.3 Ensure that VA setting 'Periodic recurring scans' to 'on' for each SQL server

- README.md
- security/azure/pg_conn_throttling/CHANGELOG.md
- security/azure/pg_conn_throttling/README.md
- security/azure/pg_conn_throttling/pg_conn_throttling.pt
Azure CIS 4.3.5 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server
Tested and working
> Azure CIS 4.3.5 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server

- cost/azure/rightsize_compute_instances/CHANGELOG.md
- cost/azure/rightsize_compute_instances/azure_compute_rightisizing.pt
Fixes bug with the check for underutilized instances
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=640b90e77b2db10001f84d7c
[[List any existing issues this PR resolves]](https://flexera.atlassian.net/browse/POL-783)
> POL-783: fix azure compute rightsizing check underutilized

- compliance/azure/azure_untagged_resources/CHANGELOG.md
- compliance/azure/azure_untagged_resources/README.md
- compliance/azure/azure_untagged_resources/untagged_resources.pt
- Added the ability to check for key=value pairs or key= or just keys.
- Added the ability to select a resource in the incident and enter a tag in key=value format to add to the specific resource
> POL-726 update azure untagged resources

- compliance/aws/untagged_resources/CHANGELOG.md
- compliance/aws/untagged_resources/README.md
- compliance/aws/untagged_resources/aws_untagged_resources.pt
Following on from issues SEs were facing with using the Untagged Resources policies, we did some work to improve their usability. This was addressed with POL-684 but these changes must be added to Catalog
POL ticket - https://flexera.atlassian.net/browse/POL-725
Policy now has a parameter where the user enters a Tag Key to check resources against. Policy produces a list of untagged resources, where the resources are either missing the Tag Keys specified, or resources where the Tag Key exists but is missing a Tag Value.
Applied policy tested - https://app.flexera.com/orgs/32567/automation/applied-policies/projects/133743?policyId=6401cd44952e4d00015f3940 
Applied policy incident - https://app.flexera.com/orgs/32567/automation/incidents/projects/133743?incidentId=6401cd514bc8580001a35a94 …
> POL-725 Update AWS Untagged Resources

- cost/aws/old_snapshots/CHANGELOG.md
- cost/aws/old_snapshots/README.md
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
- tools/cloudformation-template/FlexeraAutomationPolicies.template
- tools/cloudformation-template/README.md
- tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.3.0.template
Add RDS support to AWS Old Snapshots
https://flexera.atlassian.net/browse/POL-715
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=63ff7f197b2db10001f84c4f
> POL-715 - Add RDS support to AWS Old Snapshots

- .github/workflows/generate-azure-pricing-json.yaml
- data/azure/requirements.txt
Automates the updates to Azure Pricing JSON
> feat: automate generate azure pricing json

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
- cost/budget_alerts_by_account/CHANGELOG.md
- cost/budget_alerts_by_account/budget_alerts_by_account.pt
Budget Alerts
- Only skips last 3 days if user selects Forecasted Spend (this brings it in line with Budget Alerts by Cloud Account)
- Improvements to how dates are calculated. In particular, issues related to February and leap years are resolved.
- General code cleanup/modernization
Budget Alerts by Cloud Account
- Improvements to how dates are calculated. In particular, issues related to February and leap years are resolved.
- General code cleanup/modernization
Both policies tested and work fine.
> Pol 747 Budget Alerts

- compliance/fnms/fnms_licenses_at_risk/CHANGELOG.md
- compliance/fnms/fnms_licenses_at_risk/README.md
- compliance/fnms/fnms_licenses_at_risk/fnms-at-risk-licenses.pt
- compliance/fnms/fnms_low_licenses_available/CHANGELOG.md
- compliance/fnms/fnms_low_licenses_available/README.md
- compliance/fnms/fnms_low_licenses_available/fnms-low-available-licenses.pt
Deprecates FlexNet Manager policies affected by the [Flexera One ITAM SOAP APIs Transitioning to Flexera One 
IAM](https://community.flexera.com/t5/Flexera-One-Blog/Flexera-One-ITAM-SOAP-APIs-Transitioning-to-Flexera-One-IAM/ba-p/229399)
https://flexera.atlassian.net/browse/POL-788
> POL-788 - Deprecate FlexNet Manager Policies

- cost/cloud_cost_anomaly_alerts/CHANGELOG.md
- cost/cloud_cost_anomaly_alerts/README.md
- cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Policy now receive a key-value pair for filter dimension from API Endpoint
The list from the user cant be filtered before, now the user can inputs a key-value pair to filter anomalies for the report
> HCLIND-59 - Filter on dimensions

- operational/fnms/schedule_fnms_reports/CHANGELOG.md
- operational/fnms/schedule_fnms_reports/README.md
- operational/fnms/schedule_fnms_reports/schedule-fnms-report.pt
Example Applied Policy:
https://app.flexera.com/orgs/28010/automation/applied-policies/projects/123559?policyId=642362caff3f0400013d1e73&noIndex=1
Update Scheduled FlexNet Manager Report to use Flexera One API endpoints and authentication.
Full details for related change https://community.flexera.com/t5/Flexera-One-Blog/Flexera-One-ITAM-SOAP-APIs-Transitioning-to-Flexera-One-IAM/ba-p/229399
https://flexera.atlassian.net/browse/POL-787
> POL-787 Update PT to use Flexera One APIs

- compliance/aws/instances_without_fnm_agent/CHANGELOG.md
- compliance/aws/instances_without_fnm_agent/README.md
- compliance/aws/instances_without_fnm_agent/aws_instances_not_running_flexnet_inventory_agent.pt
- compliance/azure/instances_without_fnm_agent/CHANGELOG.md
- compliance/azure/instances_without_fnm_agent/README.md
- compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent.pt
Update Scheduled FlexNet Manager Report to use Flexera One API endpoints and authentication.
Full details for related change https://community.flexera.com/t5/Flexera-One-Blog/Flexera-One-ITAM-SOAP-APIs-Transitioning-to-Flexera-One-IAM/ba-p/229399
AWS Instances without FlexNet Manager Agent:
https://app.flexera.com/orgs/28010/automation/incidents/projects/123559?incidentId=64235af13c13fd000131aa00&noIndex=1
Azure Instances without FlexNet Manager Agent:
https://app.flexera.com/orgs/28010/automation/incidents/projects/123559?incidentId=64235d3b3c13fd000131aa05&noIndex=1
https://flexera.atlassian.net/browse/POL-791
> POL-791 Update AWS+Azure "Instances without FlexNet Manager Agent" for Flexera One

- cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
- cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
This policy has poor performance and needs to be refactored, some clients like Bayer and Shwartz IT are reporting that their policies timeout despite having a limit of 2 hours, also, currently it has a bug related with zone names.
- Fixed error getting zone name as region
- Adding missing fields for policy logs
- Filtering data before requests to avoid unnecessary requests to `/aggregated/disks` and `/recommenders/google.compute.disk.IdleResourceRecommender/recommendations` APIs
> FOPTS-198 Optimize Google Idle Persistent Disk Recommender policy

- .github/workflows/cfn-test.yaml
- tools/cloudformation-template/FlexeraAutomationPolicies.template
- tools/cloudformation-template/README.md
- tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.4.0.template
Adds permissions and mappings for 7 additional policy templates that are frequently deployed during the Inform and Optimize phases
- AWS Reserved Instances Recommendation
- AWS Object Storage Optimization
- AWS Expiring Savings Plans
- AWS Savings Plan Recommendations
- AWS Savings Plan Utilization
- AWS Tag Cardinality Report
- AWS Untagged Resources
https://flexera.atlassian.net/browse/POL-804
> POL-804 - Add perms for 7 additional policy templates to CloudFormation Template

- tools/cloudformation-template/README.md
Adds Template S3 URL to header so it's more visible
> docs: Add Latest S3 URL to README header

- cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
Adds a meta policy for AWS Object Storage Optimization
Intended to function correctly once the following pull request is approved:
https://github.com/flexera-public/policy_templates/pull/1229
> Meta Policy Support for AWS Object Storage Optimization

- cost/google/idle_ip_address_recommendations/CHANGELOG.md
- cost/google/idle_ip_address_recommendations/README.md
- cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
This policy has poor performance and needs to be refactored, some clients like Bayer and Shwartz IT are reporting that their policies timeout despite having a limit of 2 hours.
- Changed list API to aggregatedList API to get addresses
- Modified filters, previously applied in code, now those are applied in request
- Fix: Wrong number of rows in incident
> FOPTS-200 Optimize Google Idle IP Recommender policy

- cost/aws/FlexeraReadOnlyPolicy.template
- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/README.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- tools/cloudformation-template/FlexeraAutomationPolicies.template
- tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.5.0.template
The policy has been updated to detect attached volumes, unattached, or both based on customer preference, dictated by a new parameter Volume Status. A new field to the export statement, Status, was added to show the volume's current status.
Appropriate CWF code was added to ensure that attached volumes are detached before being deleted (and this has been tested; poor vol-0dc3f4692c6a6d88d never saw it coming). Detaching happens before both snapshot and deletion.
I also cleaned up some of the policy code to modernize it and improve readability. Basic functionality is unchanged apart from the above.
Finally, the CWF template was modified to add DetachVolume to the permissions for this policy, since that is now needed for full functionality.
N/A. This is to add functionality. I did review …
> POL-785 - Add support for attached volumes to the `AWS Unused Volumes` Policy Template

- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Do not merge until the following is merged
https://github.com/flexera-public/policy_templates/pull/1246
> AWS Unused Volumes: Updating meta policy to support changes in child policy

- cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
- cost/google/idle_vm_recommendations/CHANGELOG.md
- cost/google/idle_vm_recommendations/google_vm_recommendations.pt
[FOPTS-199](https://flexera.atlassian.net/browse/FOPTS-199) Optimize Google Idle VM Recommender policy
Replace GCP endpoints by aggregated endpoints to make policy run faster
- Policy was timing out despite having more than 2 hours to run.
Previous version (v2.4):
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=6438478dbbe0ca00013e6352
New version (v2.5):
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=643ec4bcbbe0ca00013e6381
> FOPTS-199 Optimize Google Idle VM Recommender policy

- cost/azure/rightsize_compute_instances/CHANGELOG.md
- cost/azure/rightsize_compute_instances/README.md
- cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
- Added parameter `param_threshold_statistic` to allow selecting between minimum, maximum and average statistics to base rightsizing and idle recommendations on.
https://app.flexera.com/orgs/32567/automation/applied-policies/projects/133743?policyId=6442d93e94f003000154d63a
> adding parameter threshold, updates to use it in evaluations

- cost/budget_alerts/CHANGELOG.md
- cost/budget_alerts/budget_alert.pt
Added Deprecated Message
https://flexera.atlassian.net/browse/FOPTS-698)
> FOPTS-698 Deprecated Message

- cost/turbonomics/allocate_virtual_machines_recommendations/aws/turbonomics_allocate_virtual_machines.pt
- cost/turbonomics/allocate_virtual_machines_recommendations/azure/turbonomics_allocate_virtual_machines.pt
- cost/turbonomics/allocate_virtual_machines_recommendations/gcp/turbonomics_allocate_virtual_machines.pt
- cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
- cost/turbonomics/buy_reserved_instances_recommendations/azure/turbonomics_buy_reserved_instances.pt
- cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
To facilitate Turbonomic integration demos, we need to publish Turbonomic policies to the automation catalog.
Flag "publish: false" is removed from info block of the Turbonomic policies
N/A
> FOPTS-761 Publish Turbonomic Policies To Catalog

- cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md
- cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
- cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_databases_recommendations/gcp/CHANGELOG.md
- cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/CHANGELOG.md
- cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/CHANGELOG.md
- cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/CHANGELOG.md
- cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
- cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/azure/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
Updrade Turbonomic Policies Version Number.
Policies published at Automation Catalog appear with links to documentation.
> FOPTS-761 Updrade Turbonomic Policies Version Number

- cost/azure/rightsize_compute_instances/CHANGELOG.md
- cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
One letter change to resolve error with using param_subscription_allowlist
Example error from this issue:
https://app.flexera.com/orgs/35153/automation/applied-policies/projects/136993?policyId=645bd639a9fd7a0001534aa6
https://app.flexera.com/orgs/35153/automation/applied-policies/projects/136993?policyId=645bd8e0a9fd7a0001534ab2
> quick fix to change results to result

- cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md
- cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
- cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/azure/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/azure/turbonomics_scale_virtual_machines.pt
- cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md
- cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
> FOPTS-829 FIX Broken Readme Links

- cost/kubecost/sizing/CHANGELOG.md
- cost/kubecost/sizing/README.md
- cost/kubecost/sizing/kubecost_resizing_recommendation.pt
The Kubecost Request Sizing Recommendations Policy Template is used to get recommendations for resizing instances controlled with Kubecost
[Jira Ticket FOPTS-182](https://flexera.atlassian.net/browse/FOPTS-182)
Applied policy
[Applied policy on Flexera test](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/105882?policyId=6452bce67b2db10001f8553d)
> FOPTS-182 Kubecost request sizing recommendations policy template

- cost/kubecost/cluster/CHANGELOG.md
- cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
Kubecost generates recommendations to optimize Kubernetes cluster
Policy can be used to bring these cluster sizing recommendations.
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=645ec83cd4f90e00019637d0
> FOPTS-180 Corrected Kubecost Cluster Sizing Recommendations Policy

- cost/kubecost/sizing/CHANGELOG.md
- cost/kubecost/sizing/README.md
- cost/kubecost/sizing/kubecost_resizing_recommendation.pt
[FOPTS-846](https://flexera.atlassian.net/browse/FOPTS-846)
[Applied policy](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=645eb06f75202d0001bc9fcd)
> FOPTS-846 Kubecost request rightsizing policy - unable to apply with default parameter values

- cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
- cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
- cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
- cost/aws/unused_rds/unused_rds_meta_parent.pt
- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Updates meta policies to include most up to date version of policy parameters.
> Update Meta Policy Parameters

- README_META_POLICIES.md
- cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
- cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
- cost/aws/unused_rds/unused_rds_meta_parent.pt
- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Meta policies are showing up in the catalog due to a typo. This fixes the typo.
> Meta Policy Publish Fix

- cost/aws/old_snapshots/CHANGELOG.md
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
- cost/azure/unused_volumes/CHANGELOG.md
- cost/azure/unused_volumes/azure_unused_volumes.pt
Update and standardize usage reduction policies (Azure Unused Volumes and AWS Old Snapshots).
Standardized Azure Unused Volumes policy template and AWS Old Snapshots template.
Azure Unused volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=648522d0622f6e000119021c
AWS old snapshots: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64853b194466b10001e2033a
> FOPTS-1079 Update Usage Reduction Policies (Azure Unused Volumes and AWS old snapshots)

- README_META_POLICIES.md
- cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
- cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
- cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
- cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
- cost/aws/unused_rds/unused_rds_meta_parent.pt
- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Unpublishes rightsize compute meta policy which was published in error due to typo
> Meta typo fix

- cost/azure/unused_volumes/CHANGELOG.md
- cost/azure/unused_volumes/azure_unused_volumes.pt
Added logic required for "Meta Policy" use-cases
https://flexera.atlassian.net/browse/FOPTS-1082
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=648a0ba24466b10001e20962
> FOPTS-1082 - Add MetaPolicy logic to Azure Unused Volumes policy

- cost/azure/idle_compute_instances/CHANGELOG.md
- cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Both Policies are updated and using  hash_exclude, to avoid excessive triggering 
[Jira Ticket FOPTS-710](https://flexera.atlassian.net/browse/FOPTS-710)
> FOPTS-710 Excessive escalation triggering

- cost/aws/reserved_instances/recommendations/CHANGELOG.md
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
- cost/azure/reserved_instances/mca_recommendations/CHANGELOG.md
- cost/azure/reserved_instances/mca_recommendations/azure_reserved_instance_recommendations.pt
- cost/azure/savings_plan/recommendations/CHANGELOG.md
- cost/azure/savings_plan/recommendations/azure_savings_plan_recommendations.pt
Update and standardize rate reduction policies:  (AWS and Azure RI Recommendations, and Azure Savings Plan)
Standardize AWS Reserved Instances Recommendations, Azure Reserved Instances Recommendations and Azure Savings Plan policy templates
- AWS RI Recommendations: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6489428f49169e000142fdb7
- Azure RI Recommendations: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=648946f9622f6e0001190252
- Azure Savings Plan: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64895fcb622f6e0001190254
> FOPTS-1035 Update Rate Reduction Policies (AWS and Azure RI Recommendations, and Azure Savings Plan)

- cost/aws/idle_compute_instances/CHANGELOG.md
- cost/aws/idle_compute_instances/idle_compute_instances.pt
- cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt
- cost/aws/unused_rds/CHANGELOG.md
- cost/aws/unused_rds/unused_rds.pt
- cost/aws/unused_rds/unused_rds_meta_parent.pt
- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
Update and standardize AWS Usage Reduction Policies:
- AWS Idle Compute Instances
- AWS Unused RDS Instance
- AWS Unused IP Addresses
- AWS Unused Volumes
[FOPTS-1122 - AWS Usage Reduction Policies (Jira)](https://flexera.atlassian.net/browse/FOPTS-1122)
[AWS Idle Compute Instances](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=649143454466b10001e21822)
[AWS Unused RDS Instance](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64911f734466b10001e217ff)
[AWS Unused IP Addresses](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6491077c4466b10001e217ea)
[AWS Unused Volumes](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=649102dd4466b10001e21 …
> FOPTS-1122 Update AWS Usage Reduction Policies (Unused Resources)

- cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
Add parent meta policy for azure unused volumes
https://flexera.atlassian.net/browse/FOPTS-1083
Parent:
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64917fd249169e0001430d0e
Child:
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?noIndex=1&policyId=64917ff949169e0001430d0f
> FOPTS-1083 - Add parent meta policy for azure unused volumes

- cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md
- cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
- cost/aws/rightsize_compute_instances/CHANGELOG.md
- cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
- cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt
- cost/aws/rightsize_ebs_volumes/CHANGELOG.md
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
Update and standardize AWS Usage Reduction Policies:
AWS Rightsize EBS Volumes
AWS Rightsize RDS Instances
AWS Rightsize Compute Instances
[FOPTS-1122 - AWS Usage Reduction Policies (Jira)](https://flexera.atlassian.net/browse/FOPTS-1122)
[AWS Rightsize RDS Instances](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6495bdfb4466b10001e22bc0)
[AWS Rightsize Compute Instances](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6495d42d49169e0001431fa2)
[AWS Rightsize EBS Volumes](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6495be824466b10001e22bc2)
> FOPTS-1122 Update AWS Usage Reduction Policies (Rightsize)

- cost/billing_center_cost_anomaly/README.md
The Billing Center Cost Anomaly Detection Policy has a broken link to a new policy version and its readme file.
The readme is updated to supply the correct link to the new policy version: https://github.com/flexera-public/policy_templates/tree/master/cost/cloud_cost_anomaly_alerts
Not Applicable
> FOPTS-1064 Billing Center Cost Anomaly Detection Policy - broken link in readme

- cost/aws/unused_rds/README.md
- tools/cloudformation-template/FlexeraAutomationPolicies.template
Readme show current permissions used for this policies for aws credentials 
[Jira Ticket FOPTS-807](https://flexera.atlassian.net/browse/FOPTS-807)
> FOPTS-807 AWS Unused RDS Policy Github pre-requisites update request

- compliance/aws/long_stopped_instances/CHANGELOG.md
- compliance/aws/long_stopped_instances/README.md
- compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
- compliance/aws/long_stopped_instances/aws_long_stopped_instances_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Added logic to original AWS Long-Stopped Instances policy that is required for "Meta Policy" use-cases
Adds meta policy functionality to the policy template
https://app.flexera.com/orgs/30105/automation/applied-policies/projects/133807?policyId=64b51ca1fbdef500017290bc
> POL-880 AWS Long-Stopped Instances - Create Meta Parent - Update Child Policy

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
This fixes an issue where the policy would error out when trying to raise an incident. 
This fixes an issue where the policy would error out when trying to raise an incident. 
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=64b9309f1268830001678fb1
> POL-886 Azure Unused IP Policy Fix

- operational/aws/lambda_functions_with_high_error_rate/CHANGELOG.md
- operational/aws/lambda_functions_with_high_error_rate/README.md
- operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate.pt
- operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a change that adds meta policy functionality to the AWS Lambda Function High Error Rate policy template.
Resolves issue in all customer tenants where the Lambda Function High Error Rate policy must be ran individually on each linked account and master account.
https://app.flexera.com/orgs/30105/automation/applied-policies/projects/133807?policyId=64bfb4b6fbdef500017291e6
> POL-887 Meta Policy for AWS Lambda Function high error rate

- operational/bill_processing_errors_notification/CHANGELOG.md
- operational/bill_processing_errors_notification/README.md
- operational/bill_processing_errors_notification/bill_processing_errors_notification.pt
This is a general update to this policy to add it back into the catalog and remove the deprecated "auth_rs" authentication method. This is a breaking change; the policy now requires a valid Flexera credential.
I also gave both the policy itself and the README a bit of a spit shine to align it more closely to our other policies and bring it up to catalog standards.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=64ca65b91c05c900018b4269
> POL-896 Update "Bill Processing Errors" Policy And Add To Catalog

- cost/currency_conversion/CHANGELOG.md
- cost/currency_conversion/README.md
- cost/currency_conversion/currency_conversion.pt
- Removed requirement for dedicated xe.com credential
- Added Oracle Cloud support
- Added support for user-specified sources of cloud cost
- All parameters now have a default value
- Improvements to underlying policy code
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=64c7bd681c05c900018b3d4c
Note: I have also run the policy multiple times to ensure that it does not remove existing adjustments or create duplicate adjustments.
> POL-894 Currency Conversion API Update & Tweaks

- cost/azure/idle_compute_instances/README.md
- cost/azure/old_snapshots/README.md
- cost/azure/savings_plan/recommendations/README.md
- cost/azure/unused_ip_addresses/README.md
- cost/azure/unused_sql_databases/README.md
- cost/azure/unused_volumes/README.md
This PR updates the READMEs for several Azure cost policies to more accurately reflect the permissions needed for those policies to function.
N/A. These are just README modifications.
> POL-861 Azure Readme Permissions Updates

- cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/CHANGELOG.md
- cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt
Azure Rightsize Volumes policy needs to show the following information: current and new storage access IOPs, current and new storage amount, VM volume is attached to, action nature: disruptive or not, reversible or not, current and new throughput capacity, IOPs utilization, disk utilization, throughput utilization, system details URL.
- Azure Turbonomic Rightsize Volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64d50e5e53379b0001babd32
> FOPTS-1328 Turbonomic Rightsize Volumes (Azure)

- cost/aws/old_snapshots/CHANGELOG.md
- cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Fixes issue related to tags not appearing as expected in the resulting incident.
https://app.flexera.com/orgs/34608/automation/incidents/projects/136331?incidentId=64e629a96e42ff00014b3c74
> POL-906: fix `ds_describe_snapshots` tag collect

- cost/turbonomics/rightsize_databases_recommendations/azure/CHANGELOG.md
- cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt
Turbonomic Right size DBs ( Azure ) Need to add request to check Price Model
[FOPTS-1584](https://flexera.atlassian.net/browse/FOPTS-1584)
[Turbonomic Rightsize Databases Recommendations Azure - Applied Policy Template](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64dd5dc17dac9c0001ef8aff)
> FOPTS-1584 Turbonomic Right size DBs ( Azure ) Need to add request to check Price Model

- .github/workflows/update-active-policy-list.yaml
Renames the Workflow to be more appropriate for the work it does.
> task: update active policy list json

- cost/aws/unused_rds/README.md
Updated Policy Name in the README.md file from AWS Unused RDS Policy to AWS Unused RDS Instances
Policy Name Updated
Policy wasn't applied, it's just a README update
> FOPTS-1577 AWS Unused RDS Instances: update policy name in the README

- cost/turbonomics/buy_reserved_instances_recommendations/aws/CHANGELOG.md
- cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt
AWS Buy RI policy needs to show the following information: projected RI utilization and RI coverage, system details URL.
- Turbonomic Buy Reserved Instances Recommendations AWS: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64ffa022beb3db00016c2e1e
> FOPTS-1336 Turbonomic Buy RI (AWS)

- cost/low_account_usage/CHANGELOG.md
- cost/low_account_usage/low_account_usage.pt
The policy template can be optimized to reduce evaluation time. Currently there's a timeout happening.
Policy template code is reviewed and optimized to improve performance.
- Low Account Usage Policy: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=650245280105d50001c4d17e
> FOPTS-1815 Low Account Usage Policy optimization

- cost/low_account_usage/CHANGELOG.md
- cost/low_account_usage/low_account_usage.pt
The policy template can be optimized to reduce evaluation time. We're still getting a timeout happening.
Policy template code is reviewed and optimized to improve performance. More code was removed with same functionality.
- Low Account Usage Policy: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=651328286a972a0001e51857
> FOPTS-2108 Rework Low Account Usage Policy Optimization

- cost/cheaper_regions/CHANGELOG.md
- cost/cheaper_regions/cheaper_regions.pt
added vendor type for Azure MCA CSP's
Was excluding this vendor type due to it not being included.
https://app.flexera.com/orgs/34193/automation/applied-policies/projects/135696?policyId=650c7b21656c530001e17a92
> cheaper regions update

- .github/workflows/generate-azure-pricing-json.yaml
- data/azure/requirements.txt
Fixing issues where remote execution of the Azure pricing script results in bad data. Mainly did this by making the workflow roughly equivalent to my local workstation in terms of OS, python version, etc. since I know the script executes as intended there.
https://github.com/flexera-public/policy_templates/actions/runs/6470185374/job/17565807813
> POL-939 Azure Pricing Workflow Fix

- cost/aws/reserved_instances/recommendations/CHANGELOG.md
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
Fixed issue where policy would fail to do proper currency conversion
> AWS Reserved Instances Recommendation Currency Conversion Fix

- cost/azure/superseded_instances/CHANGELOG.md
- cost/azure/superseded_instances/azure_superseded_instances.pt
- cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt
This fixes a broken link to the README in the incident description
> POL-946 Azure Superseded Compute Instances - Fix Broken Link

- cost/aws/reserved_instances/recommendations/CHANGELOG.md
- cost/aws/reserved_instances/recommendations/aws_reserved_instance_recommendations.pt
Fixed an issue where we would get an error on empty array for currency conversion check
> fix bug in ds_currency check

- compliance/google/unlabeled_resources/CHANGELOG.md
- compliance/google/unlabeled_resources/README.md
- compliance/google/unlabeled_resources/unlabeled_resources.pt
Policy shows missing label keys, but it also needed to show label values as AWS and Azure do in Untagged policies.
Policy shows missing label keys and values
- [Applied policy](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6538634855d35d0001a84cd6)
- [Applied policy with mock data](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=65385fcc55d35d0001a84cd5)
> FOPTS-842 Google Unlabeled Resources Policy

- cost/azure/instances_log_analytics_utilization/CHANGELOG.md
- cost/azure/instances_log_analytics_utilization/README.md
- cost/azure/instances_log_analytics_utilization/azure_instance_log_analytics_utilization.pt
CPU and memory usage data can now be obtained from Azure resources without the need for Log Analytics. The Azure Rightsize Compute Instances policy now includes this functionality and is the recommended policy for getting recommendations for inefficient instance utilization. As a consequence, the Azure Inefficient Instance Utilization using Log Analytics policy is now being deprecated.
Not needed. Changes do not affect policy functionality or execution.
> POL-963 Deprecate "Azure Inefficient Instance Utilization using Log Analytics" Policy

- cost/email_recommendations/CHANGELOG.md
- cost/email_recommendations/README.md
- cost/email_recommendations/email_recommendations.pt
This is a new policy that retrieves recommendations from the Flexera API and emails them to the specified list of email users. This offers functionality that can't currently be obtained within individual policies, such as the ability to send recommendations from multiple source policies in a single email, and the ability to email recommendations from child policies at any cadence the user wishes.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=65452f9a99745e0001587f6f
> POL-964 Email Cost Optimization Recommendations

- .github/workflows/generate-azure-pricing-json.yaml
- data/azure/requirements.txt
This is intended to fix the issue with the Azure pricing Github action failing. It also contains an updated version of the pricing.
https://github.com/flexera-public/policy_templates/actions/runs/7037783051/job/19153310297
> POL-976 Fix Azure Pricing Action

- compliance/aws/disallowed_regions/README.md
- cost/aws/savings_plan/expiration/README.md
This fixes the permissions listed in two AWS policy READMEs to match the policies in question.
N/A. This is just README changes.
> POL-984 Fix AWS README Permissions

- cost/azure/reserved_instances/utilization/CHANGELOG.md
- cost/azure/reserved_instances/utilization/README.md
- cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt
We are currently migrating customers' bill configurations to the new Azure method, however this policy still uses legacy EA APIs, which will be deprecated as part of the migration.
This is a change to update the policy to move away from the legacy EA APIs and utilize the modern Azure APIs.
Moving the modern Azure APIs resolves the issue of having a dependency on the Azure EA Key as an Automation Credential.
https://app.flexera.com/orgs/33693/automation/applied-policies/projects/135064?policyId=6570714a55d35d0001a9053c
> POL-971 Azure Reserved Instances Utilization - update to use Modern Azure APIs

- cost/aws/schedule_instance/CHANGELOG.md
- cost/aws/schedule_instance/README.md
- cost/aws/schedule_instance/aws_schedule_instance.pt
- cost/google/schedule_instance/CHANGELOG.md
- cost/google/schedule_instance/README.md
- cost/google/schedule_instance/google_schedule_instance.pt
Improved logging and error handling in the Scheduled Instance Policy Templates (AWS, Google)
> feat: improved logging error handling schedule instance PTs

- cost/scheduled_reports/CHANGELOG.md
- cost/scheduled_reports/README.md
- cost/scheduled_reports/currency_reference.json
- cost/scheduled_reports/scheduled_report.pt
This is a revamp of the Scheduled Report policy that streamlines it and extends functionality. From the CHANGELOG:
- Added ability to specify custom dimensions for the graph in the report
- Added ability to filter costs in report by any user-specified dimension
- Improved incident output for readability and removed references to Optima
- Incident table now shows the raw data used to create the graph in the report
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6581d9c0530963000172984c
> POL-1010 Scheduled Report Policy Revamp

- cost/aws/unused_volumes/CHANGELOG.md
- cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
This updates the policy actions to follow current conventions and have better error logging outside of NAM. Functionality is unchanged.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=6595c5b97cc18300018b587e
> POL-988 AWS Unused Volumes Policy Action Revamp

- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
This updates the policy actions to follow current conventions and have better error logging outside of NAM. Functionality is unchanged.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65941b569f8a200001eccfe1
> POL-990 Azure Rightsize SQL Policy Action Revamp

- cost/azure/old_snapshots/CHANGELOG.md
- cost/azure/old_snapshots/azure_delete_old_snapshots.pt
- cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt
This updates the policy actions to follow current conventions and have better error logging outside of NAM. Functionality is unchanged.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=6594150a9f8a200001eccfdb
> POL-989 Azure Old Snapshots Policy Action Revamp

- cost/azure/databricks/rightsize_compute/CHANGELOG.md
- cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute.pt
- cost/azure/databricks/rightsize_compute/azure_databricks_rightsize_compute_meta_parent_cluster.pt
- Add `param_databricks_cluster_list` for filtering to a specific Databricks Cluster within a Databricks Workspace
- Add `p90`,`p95`,`p99` Threshold Statistic choices
- Fixed subscription ID and Name output in recommendation
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6596fc79d1dc74000182cef0
> feat: add cluster id filtering for databricks PT

- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
- compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent_meta_parent.pt
- cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume_meta_parent.pt
- cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
- operational/aws/lambda_functions_with_high_error_rate/lambda_functions_with_high_error_rate_meta_parent.pt
- operational/azure/azure_certificates/azure_certificates_meta_parent.pt
- security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes_meta_parent.pt
- security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances_meta_parent.pt
The script for generating meta policies has been updated. This is just a PR to regenerate some of the meta policies using this script.
> POL-1043 Update Meta Policies

- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
- cost/azure/reserved_instances/recommendations/CHANGELOG.md
- cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
This fixes an issue where the policy was returning all reservation recommendations instead of either 1 year or 3 year based on the parameter.
(Tested in client environment successfully. Not able to easily test in a test environment due to lack of recommendations in those environments)
> POL-1045 Azure Reserved Instances Recommendations: Term Parameter Fix

- cost/azure/reserved_instances/recommendations/CHANGELOG.md
- cost/azure/reserved_instances/recommendations/README.md
- cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations.pt
- cost/azure/reserved_instances/recommendations/azure_reserved_instance_recommendations_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
We were receiving reports of 429 rate limiting errors from the Azure APIs when attempting to use this policy. The following has been done to try to alleviate this issue:
- A forced 5 second delay between requests to the Microsoft.Consumption/reservationRecommendations API endpoint has been added.
- Information has been added to the README recommending that the policy be applied once for each resource type for large cloud estates.
- Meta policy support has been added.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=65a822cf0620ac00011a9496
> POL-1047 Azure Reserved Instances Recommendations Scaling Fixes

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
Add aws_rightsize_rds_instances.pt
> Add aws_rightsize_rds_instances.pt

- cost/aws/unused_ip_addresses/README.md
- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
[add aws_unused_ip_addresses.pt](https://github.com/flexera-public/policy_templates/commit/eba36a515201f17847cca1cec709a168fe4a69c2)
> add aws_unused_ip_addresses.pt

- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
> POL-918 add azure unused sql to list

- cost/azure/rightsize_compute_instances/README.md
- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
[add azure_delete_old_snapshots.pt](https://github.com/flexera-public/policy_templates/commit/446a4bfbc1dbe2d1460a8481e7786d0db42c1a60)
> add azure_delete_old_snapshots.pt

- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
[add azure_savings_plan_recommendations.pt](https://github.com/flexera-public/policy_templates/commit/015caac115b08fda7295276d0b632f9baaf3e774)
> add azure_savings_plan_recommendations.pt

- compliance/aws/untagged_resources/CHANGELOG.md
- compliance/aws/untagged_resources/README.md
- compliance/aws/untagged_resources/aws_untagged_resources.pt
- compliance/aws/untagged_resources/aws_untagged_resources_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a complete revamp and overhaul of the AWS Untagged Resources policy. Both the policy code and actions have been revamped. From the CHANGELOG:
- Added ability to filter resources by tag key, tag key==value, or using regex
- Added ability to use all filters as an allow list or a deny list
- Meta policy support added
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65aae340246c29000155c2c8
> POL-1042 AWS Untagged Resources Revamp

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/generate_policy_master_permissions.rb
- tools/policy_master_permission_generation/validated_policy_templates.yaml
Adds Google CUD Recommender policy permissions to the Policy Master Permissions artifact.
Permissions have been validated
> NVF/POL-918 1705958339 - Validate Google CUD Recommender permissions

- compliance/azure/azure_long_stopped_instances/long_stopped_instances_azure.pt
- compliance/google/long_stopped_instances/CHANGELOG.md
- compliance/google/long_stopped_instances/README.md
- compliance/google/long_stopped_instances/google_long_stopped_instances.pt
- compliance/google/long_stopped_instances/google_long_stopped_instances_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a revamp similar to other revamps we've done. This revamps both the policy itself and the policy actions. It also changes the name of the policy to better conform to standards established elsewhere in the catalog and adds meta policy support.
- Added more robust ability to filter resources by project
- Added ability to filter resources by region
- Meta policy support added
- Policy now …
> POL-995 Google Long Stopped Instances Revamp

- cost/azure/object_storage_optimization/CHANGELOG.md
- cost/azure/object_storage_optimization/README.md
- cost/azure/object_storage_optimization/azure_object_storage_optimization.pt
- cost/azure/object_storage_optimization/azure_object_storage_optimization_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a revamp of the Azure Blob Storage Optimization that brings its functionality more in line with the equivalent AWS policy while also ensuring that policy actions have been revamped for better error reporting outside of NAM. From the CHANGELOG:
- Added ability to assess blobs in multiple storage accounts
- Added ability to filter storage accounts by subscription
- Added ability to filter storage accounts by region
- Added ability to filter storage accounts by multiple tag key:value pairs
- Added ability to delete blobs
- Policy no longer …
> POL-999 Azure Blob Storage Optimization Revamp

- automation/aws/aws_rbd_from_tag/CHANGELOG.md
- automation/aws/aws_rbd_from_tag/README.md
- automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
- automation/azure/azure_rbd_from_rg_tag/CHANGELOG.md
- automation/azure/azure_rbd_from_rg_tag/README.md
- automation/azure/azure_rbd_from_rg_tag/azure_rbd_from_rg_tag.pt
- automation/azure/azure_rbd_from_tag/CHANGELOG.md
- automation/azure/azure_rbd_from_tag/README.md
- automation/azure/azure_rbd_from_tag/azure_rbd_from_tag.pt
- automation/google/google_rbd_from_label/CHANGELOG.md
- automation/google/google_rbd_from_label/README.md
- automation/google/google_rbd_from_label/google_rbd_from_label.pt
- cost/aws/schedule_instance/aws_schedule_instance.pt
This adds the ability for the user to specify the names of the created dimensions via a parameter in the unpublished RBD creation policies. The new parameter is a list, and if this parameter is left blank, the existing functionality will occur instead.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65bcf831874bcc00017b8709
(Note: The change is small and identical across all of the affected policies)
> POL-1053 Custom Dimension Names in RBD Policies

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 - Add AWS Rightsize RDS Instances and Azure Rightsize SQL Instances

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 Add AWS Rightsize EBS Volumes and Azure Rightsize Managed Disks

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 Add Azure Reserved Instances Utilization

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 Add Untagged Resources (AWS and Azure)

- compliance/google/unlabeled_resources/README.md
- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 Add Google Unlabeled Resources

- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 Add Long Running Instances (AWS and Azure), AWS Long Stopped EC2 Instances

- compliance/google/long_stopped_instances/README.md
- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/policy_master_permission_generation/validated_policy_templates.yaml
> NVF/POL-918 (POL-1059) Add Google Long Stopped VM Instances

- cost/aws/rightsize_ebs_volumes/CHANGELOG.md
- cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt
- cost/aws/superseded_instances/CHANGELOG.md
- cost/aws/superseded_instances/aws_superseded_instances.pt
- cost/aws/unused_ip_addresses/CHANGELOG.md
- cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
- cost/azure/hybrid_use_benefit/CHANGELOG.md
- cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
- cost/azure/superseded_instances/CHANGELOG.md
- cost/azure/superseded_instances/azure_superseded_instances.pt
- cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md
- cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
- cost/google/cud_recommendations/CHANGELOG.md
- cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
- cost/google/idle_ip_address_recommendations/CHANGELOG.md
- cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt
- cost/google/idle_persistent_disk_recommendations/CHANGELOG.md
- cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
- cost/google/rightsize_vm_recommendations/CHANGELOG.md
- cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
An error was found in the currency conversion implementation in some policies. This is the fix for it.
Code was tested in AHUB policy and is identical in the other modified policies.
> Currency Conversion Fixes

- cost/azure/unused_ip_addresses/CHANGELOG.md
- cost/azure/unused_ip_addresses/README.md
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
- cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt
This adds more filtering options to the policy:
- Added IP allocation type (Dynamic or Static) to incident output
- Added ability to filter results by allocation type via parameter
- Added ability to filter results by minimum savings via parameter
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65de3a061b78750001a4d094
> POL-973 Azure Unused IPs Better Filtering

- operational/azure/byol_report/CHANGELOG.md
- operational/azure/byol_report/README.md
- operational/azure/byol_report/azure_byol_report.pt
- Refactored to no longer require Azure credential
- Removed parameter for Azure API endpoint since it is no longer needed
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=65df663930ca310001db0cb5
> POL-1117 Azure Bring-Your-Own-License (BYOL) Report Improvements

- .dangerfile/general_tests.rb
- .dangerfile/github_tests.rb
- .dangerfile/policy_tests.rb
- Dangerfile
- cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
This improves the Dangerfile with new tests:
- Check that indentation in policy code is correct
- Lint Ruby files for errors
- Check title of Github Pull Request as well as READY-FOR-REVIEW label
> POL-1151 Github Dangerfile: Check Spacing in Policy Code

- .github/workflows/update-active-policy-list.yaml
- Rakefile
- data/active_policy_list/active_policy_list.json
> Rakefile Fix Pt 2

- automation/aws/aws_missing_regions/CHANGELOG.md
- automation/aws/aws_missing_regions/README.md
- automation/aws/aws_missing_regions/aws_missing_regions.pt
- automation/aws/aws_missing_regions/aws_missing_regions_meta_parent.pt
- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
- tools/policy_master_permission_generation/validated_policy_templates.yaml
This adds a new unpublished policy to test for AWS regions that are returned as enabled by the AWS API but that we can't actually make requests to.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=660466f37566c288f2dac3f7
(No incident because our test account has access to everything enabled.)
> POL-1182 New Policy: AWS Missing Regions

- .dangerfile/general_tests.rb
- Dangerfile
- cost/azure/old_snapshots/README.md
New Dangerfile test: Raises warnings if references to RightScale or Optima are present in a file and recommends alternative terminology. This is a warning, not an error, due to edge cases where it might make sense to reference these technologies directly in a historical context.
> POL-1181 Dangerfile Test: Outdated Terminology

- .github/workflows/update-change-history.yaml
- tools/change_history/generate_change_history.rb
This adds a new Github Action to generate two files every time a pull request is merged:
- `data/change_history/change_history.json`: A JSON file containing a full merge history for this repository, with the newest merges listed first.
- `HISTORY.md`: A human readable version of the same data for more general, non-programmatic use.
This is to make it easier for both internal and external stakeholders to see what changes have been made, and to make it easier to provide meaningful regular updates about new policies, features, etc.
> POL-1186 Change History Generation

- cost/azure/savings_realized/CHANGELOG.md
- cost/azure/savings_realized/azure_savings_realized.pt
- The current policy does not support MCA accounts, with this change supporting MCA CBI accounts is implemented.
- The currency code that this policy shows is always USD, despite the org using EUR or other currency, this PR fixes that.
- https://flexera.atlassian.net/browse/SQ-7053
- https://flexera.atlassian.net/browse/SQ-7228
- https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=661d88e7e6626311ea1adbe5
> FOPTS-3624 Add support for MCA accounts

- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Bug was present causing all recommendations to return 0$
Line 743 changed subscriptionId to subscriptionID
https://app.flexera.com/orgs/34088/automation/incidents/projects/135557?incidentId=663b898562db364ad98e80d2
> POL-1224 Azure RightsizeSQL bug fix

- .dangerfile/readme_tests.rb
- cost/flexera/cco/budget_v_actual_spend_report/README.md
Update Flexera Cred in Read Me file.
We need Optima cred as we call API.
> FOPTS-4009 Revert Flexera Cred Changes in Update README.md

- cost/azure/rightsize_managed_disks/CHANGELOG.md
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
This PR fixes an issue with the disk name calculation. In case of error, we'd want to log the disk details and continue processing
- [ X] New functionality includes testing.
- [ X] New functionality has been documented in the README if applicable
> Fixing issue with disk name calculation

- cost/azure/rightsize_managed_disks/CHANGELOG.md
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Fixed premium ssd price calculation
https://flexera.atlassian.net/browse/SQ-8064
@midir99 - We have tested the policy template in a customer environment and successfully created more incidents then before
> FOPTS-4199 Fixing calculation of the Premium SSD price

- cost/azure/rightsize_synapse_sql_pools/CHANGELOG.md
- cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools.pt
- cost/azure/rightsize_synapse_sql_pools/azure_rightsize_synapse_sql_pools_meta_parent.pt
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
Fix syntax errors from the meta parent policy of Azure Synapse
- https://flexera.atlassian.net/browse/POL-1282
Meta parent template was able to be compiled:
>  Fix syntax erros from the meta parent policy of Azure Synapse

- automation/flexera/outdated_applied_policies/CHANGELOG.md
- automation/flexera/outdated_applied_policies/outdated_applied_policies.pt
Updated incident message to be more relative for this policy template
> fix: minor wording fix on incident detail template

- cost/aws/schedule_instance/CHANGELOG.md
- cost/aws/schedule_instance/README.md
- cost/aws/schedule_instance/aws_schedule_instance.pt
- cost/azure/schedule_instance/CHANGELOG.md
- cost/azure/schedule_instance/README.md
- cost/azure/schedule_instance/azure_schedule_instance.pt
- cost/google/schedule_instance/CHANGELOG.md
- cost/google/schedule_instance/README.md
- cost/google/schedule_instance/google_schedule_instance.pt
- remove next_stop, next_start tag requirements
- remove static zone to region mapping
- add task_labels and debugging for CWF actions
- add error capture, graceful timeout handling
https://flexera.atlassian.net/browse/POL-1347
Applied Policy:
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=66e3244ba0dc2874b49bb87d
(Org27018, Project "Flexera-Sales" 116186, Name "Google Schedule Instance")
VM:
https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-a/instances/instance-1-ip-test?project=sales-engineering-buyer
Login through Okta > `Google Cloud` App first
> POL-1347 - feat: refactor AWS, Azure, and Google Schedule Instance Policy Templates

- cost/flexera/cco/cloud_cost_anomaly_alerts/CHANGELOG.md
- cost/flexera/cco/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
> SQ-9955 Fix Cloud Cost Anomaly Alerts Policy

- compliance/flexera/fnms/overused_licenses/CHANGELOG.md
- compliance/flexera/fnms/overused_licenses/overused_licenses.pt
An issue with consumption percentage calculation was fixed.
[SQ-11024](https://flexera.atlassian.net/browse/SQ-11024)
[FOPTS-5505](https://flexera.atlassian.net/browse/FOPTS-5505)
- [*] New functionality has been documented in CHANGELOG.MD
> FOPTS-5505 Fixed consumption calculation for ITAM Overused Licenses

- tools/meta_parent_policy_compiler/google_meta_parent.pt.template
There is a bug in meta parent compiler changes for adding hide-skip-approval fields that is fixed.
> FLEX-5397 - Fix Google Meta Parent Template

- cost/azure/data_lake_optimization/CHANGELOG.md
- cost/azure/data_lake_optimization/README.md
- cost/azure/data_lake_optimization/data_lake_optimization.pt
- cost/azure/data_lake_optimization/data_lake_optimization_meta_parent.pt
- data/policy_permissions_list/master_policy_permissions_list.json
- data/policy_permissions_list/master_policy_permissions_list.yaml
- tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
- tools/policy_master_permission_generation/validated_policy_templates.yaml
Initial implementation of a Policy (Azure Data Lake Optimization) which enables customers to run efficiently for Azure Data Lake. The policy type is Usage Reduction and provide the recommendations with Potential savings.
https://flexera.atlassian.net/browse/FLEX-5165
https://app.flexera.com/orgs/34088/automation/applied-policies/projects/135557?policyId=6761dfcc0f8449d761662eff
> FLEX-5165 Add datalake optimization policy template

- operational/aws/tag_cardinality/CHANGELOG.md
- operational/aws/tag_cardinality/aws_tag_cardinality.pt
- operational/aws/tag_cardinality/aws_tag_cardinality_meta_parent.pt
This PR represents the first step in enabling Batch Processing for prioritized policies—those with the highest overall and cross-organizational usage, as well as those consuming the most memory.
In this update, the `AWS Tag Cardinality Report` policy has been refactored to implement batch processing for data sources that handle large datasets.
Related Task : https://flexera.atlassian.net/browse/FOPTS-6829
Epic : https://flexera.atlassian.net/browse/FOPTS-6341
**1- Consistency Testing (Original vs. Updated Version)**:
The objective was to verify that the updated version with Batch Processing using EFS returns the same results as the original by running both versions on a small staging use case, expecting identical results.
Proof:
Original : [Applied …
> FOPTS-6829 - Batch Proccessing Adoption for AWS Tag Cardinality Report Policy

- cost/azure/rightsize_compute_instances/CHANGELOG.md
- cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
- cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
- cost/azure/rightsize_managed_disks/CHANGELOG.md
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
- cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
- cost/azure/rightsize_sql_instances/CHANGELOG.md
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt
- cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
This represents the second step in enabling Batch Processing for prioritized policies. The selected policies are the ones with the highest overall and cross-organizational usage, as well as those consuming the most memory.
In this PR, the identified policies have been refactored to leverage Batch Processing. Specifically, the datasource operations that involve large datasets have been optimized to use EFS (Elastic File System) instead of in-memory processing. This change ensures that **memory usage is reduced** while **maintaining** or improving **execution times**
- Note : excluded Azure Rightsize Compute Instance  as the refactored version (enable batch processing) result in considerable increase in execution time)
For each policy these steps got taken : 
-  **Investigate Memory and …
> FOPTS-6833 - Batch Processing Adoption for Azure RightSize Policies

- cost/aws/rightsize_ebs_volumes/CHANGELOG.md
- cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt
- cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt
This represents the last step in enabling Batch Processing for prioritized policies. The selected policies are the ones with the highest overall and cross-organizational usage, as well as those consuming the most memory.
In this PR, AWS Rightsize EBS Volumes has been refactored to leverage Batch Processing. Specifically, the datasource operations that involve large datasets have been optimized to use EFS (Elastic File System) instead of in-memory processing. This change ensures that **memory usage is reduced** while **maintaining** or improving **execution times**
Please check the policies and applied policy links here:
https://flexera.atlassian.net/browse/FOPTS-7713?focusedCommentId=2717833
[Grafana link](https://g-1cda041840.grafana-workspace.us-east-1.amazonaws.com/d/6r9N9ysIk/evaluatio …
> FOPTS-6901 - Batch Processing Adoption for AWS Rightsize EBS Volumes

- .github/workflows/cfn-lint.yaml
- .github/workflows/cfn-publish.yaml
- .github/workflows/cfn-test.yaml
- .github/workflows/generate-aws-cloudformation-template.yaml
- .github/workflows/generate-aws-ec2-instance-types-json.yaml
- .github/workflows/generate-aws-ec2-pricing-json.yaml
- .github/workflows/generate-aws-rds-pricing-json.yaml
- .github/workflows/generate-azure-compute-instance-types-json.yaml
- .github/workflows/generate-azure-db-storage-pricing-json.yaml
- .github/workflows/generate-azure-md-pricing-json.yaml
- .github/workflows/generate-azure-sqlmi-storage-pricing-json.yaml
- .github/workflows/generate-azure-vm-pricing-json.yaml
- .github/workflows/generate-meta-parent-policy-templates.yaml
- .github/workflows/generate-policy-master-permission-missing-templates.yaml
- .github/workflows/generate-policy-master-permissions-json.yaml
- .github/workflows/generate-policy-release-notifications.yaml
- .github/workflows/generate-readme-policy-table-of-contents.yaml
- .github/workflows/test-policies.yaml
- .github/workflows/update-active-policy-list.yaml
- .github/workflows/update-aws-cloudformation-template.yaml
- .github/workflows/update-change-history.yaml
Updates broken GitHub Workflow permissions to ensure they can make pushes while still following GitHub best security practices.
> POL-1476 Fix Github Workflow

- operational/flexera/cco/rbds_from_csv_in_policy_template/csv_for_rbds_from_csv.pt
- operational/flexera/cco/rbds_from_csv_in_policy_template/rbds_from_csv.pt
Adding `publish: "false",` for new PTs merged
> task: add `publish: "false",`

- cost/aws/schedule_instance/CHANGELOG.md
- cost/aws/schedule_instance/README.md
- cost/aws/schedule_instance/aws_schedule_instance.pt
- cost/azure/schedule_instance/CHANGELOG.md
- cost/azure/schedule_instance/azure_schedule_instance.pt
- cost/google/schedule_instance/CHANGELOG.md
- cost/google/schedule_instance/README.md
- cost/google/schedule_instance/google_schedule_instance.pt
- Remove `next_stop`, `next_start` label requirements
- Add task labels to improve status updates and debugging for CWF actions
- Enhanced start/stop functions with retry logic that attempts each operation up to 3 times
- Added robust state verification to ensure instances reach the desired state
- Add error capture, graceful timeout handling for triggered actions
- Added detailed logging for troubleshooting failed operations
https://flexera.atlassian.net/browse/POL-1508
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954
> POL-1508 - AWS and Google Scheduled Policy Enhancements

- cost/azure/rightsize_netapp/CHANGELOG.md
- cost/azure/rightsize_netapp/azure_rightsize_netapp.pt
Fixes a typo in policy template's Short Description
None, less typos = more professional
N/A
> POL-1527 Azure Rightsize NetApp Resources - Correct Typo in Template Description

- operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md
- operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
Add support for Azure CSP and Azure MCA Enterprise accounts to Bill Processing Errors Notification policy.
- https://flexera.atlassian.net/browse/SQ-16235
The applied policy was executed by the customer and they confirmed it worked:
https://flexera.atlassian.net/browse/SQ-16235?focusedCommentId=2818064
> SQ-16235 | Bill Processing Errors Notification | Add support for Azure CSP and Azure MCA Enterprise

- STYLE_GUIDE.md
Adds some additional incident design info to the Style Guide
> POL-1563 Style Guide: Incident Design

- cost/flexera/cco/percentage_cost_cbi/README.md
Fixes a couple of typos in the `Percentage Cost Common Bill Ingestion` README.
> POL-1575 Percentage Cost Common Bill Ingestion README Fixes
