compliance/tags/tag_checker/tag_checker.pt, cost/volumes/uav_policy.pt
changed tag checker email parameter label to remove mention of comma
separated
Fixes UAV policy to support email list.
Cleaned up tag policy to remove mention of providing emails as a comma separated list.
Support for email lists.
=> changed uav policy email parameter to be a list.

security/security_groups/rules_without_descriptions/CHANGELOG.md, security/security_groups/rules_without_descriptions/security_group_rules_without_descriptions.pt
This makes the JavaScript for the `Security Group Rules without Descriptions` policy template execute in less than a second rather than in some unreasonable time over 5 minutes by populating maps of the security groups and networks by their HREFs instead of exhaustively search 
This resolves JavaScript timing out for the `Security Group Rules without Descriptions` policy template.
=> PHX-781 Optimize JavaScript and datasources for Security Group Rules without Descriptions policy

active-policy-list.json, cost/downsize_instance/CHANGELOG.md, cost/downsize_instance/downsize-instance.pt
Fixes a bug described in issue 59
The root cause was that accounts with clouds other than AWS, Google, Azure would have issues because the instance types (e.g. "small" in a VMware env) are not found in instance_types.json.
Change the @clouds datasource to only include AWS, Google and Azure.
Also added the current instance type to the output report so that a user can see what instance type is being used currently.
=> Downsize Policy: Specify working clouds

Dangerfile
Make the Dangerfile actually use `fail` instead of `raise` so it doesn't complain that it is invalid.
None
=> Make Dangerfile actually valid

cost/schedule_instances/README.md
The README for the schedule instances policy shows colons between the time and days and days and timezone fields in the tag.
These need to be changed to semi-colons .
None
- [X ] New functionality has been documented in the README if applicable
=> Tag example needs to use semi-colons instead of colons

cost/volumes/unattached_volumes/CHANGELOG.md, cost/volumes/unattached_volumes/README.md, cost/volumes/unattached_volumes/uav_policy.pt
Handles error when deleting volumes.
Now if a volume can't be deleted (e.g. it has a lock on it), the volume is tagged with the cloudexception error if applicable and then moves on to the next volume.
The applied policy will try to delete volumes each time it is run so that if the issue causing the deletion failure is removed, the policy will delete the volume on the next scheduled or on-demand run.
https://github.com/rightscale/policy_templates/issues/126
- [X ] New functionality includes testing.
- [ X] New functionality has been documented in the README if applicable
=> Issue 126 uav delete error handling

cost/downsize_instance/CHANGELOG.md, cost/downsize_instance/README.md, cost/downsize_instance/downsize-instance.pt
Skips any operational vm that is not sending cpu or memory monitoring data back to the platform.
https://github.com/rightscale/policy_templates/issues/151
=> Update js to skip servers without monitoring data

cost/scheduled_reports/CHANGELOG.md, cost/scheduled_reports/README.md, cost/scheduled_reports/scheduled_report.pt
Only show top 10 categories (+Other) in chart
Allows for the report dimension to be selected from any of the "standard" dimensions
Changes the chart to only show the top 10 values with all other data grouped into "Other" (like the UI does)
N/A
=> Allow for chart dimension to be selectable

tools/travis/build_docs.sh
These changes add a commit message to the build of rightscale/docs on merge to master.
N/A
=> Repo Maintenance: Add Travis commit message to docs build

README.md, cost/aws/elb/clb_unused/AWS_Delete_Unused_CLB.pt, cost/aws/elb/clb_unused/CHANGELOG.md, cost/aws/elb/clb_unused/README.md
This policy checks all  ELB (CLB) to determine if any are unused (have no healthy instances) and allows them to be deleted by the user after approval.
When an unused  ELB (CLB) is detected, an email action is triggered automatically to notify the specified users of the incident. Users then have the option to delete the  ELB (CLB) after manual approval if needed.
- https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5c9ca28c1e88c80088e2ad4d
=> Pol 34 AWS delete unused ELB(CLB)

README.md, compliance/aws/ecs_unused/AWS_Unused_ECS_Clusters.pt, compliance/aws/ecs_unused/CHANGELOG.md, compliance/aws/ecs_unused/README.md
initial version for POl-4 AWS_Unused_ECS_Clusters
This policy checks all ECS clusters to determine if any are unused (no registered instances, no running tasks, no pending tasks, no active services) and offers the option to delete the cluster after manual approval.
When an unused ECS cluster is detected, an email action is triggered automatically to notify the specified users of the incident. Users then have the option to delete the cluster after manual approval if needed.
- https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5cc1c7f39940ee0089ff1761
Screenshot:
=> POL-4 AWS_Unused_ECS_Clusters

README.md, security/aws/rds_publicly_accessible/AWS_Publicly_Accessible_RDS_Instances.pt, security/aws/rds_publicly_accessible/CHANGELOG.md, security/aws/rds_publicly_accessible/README.md
Initial release for POL-35 AWS Publicly Accessible RDS Instances
This policy checks all Relational Database Service (RDS) instances and reports on any that are publicly accessible. When such an instance is detected, the user can choose to disable the publicly accessible option and the user can also choose to delete by enabling 'delete action' option as mentioned in Enable delete action section below.
When a publicly accessible RDS instance is detected, an email action is triggered automatically to notify the specified users of the incident. Users then have an option to modify configuration after manual approval, and even Users can perform delete action if required. 
- *remove public access rule* - modifies the configuration of the RDS instance by disabling the public access rule …
=> POL-35 AWS Publicly Accessible RDS Instances

compliance/azure/azure_disallowed_regions/CHANGELOG.md, compliance/azure/azure_disallowed_regions/azure_disallowed_regions.pt, compliance/tags/azure_rg_tags/CHANGELOG.md, compliance/tags/azure_rg_tags/azure_resource_group_tags.pt, cost/azure/hybrid_use_benefit/CHANGELOG.md, cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt, cost/azure/superseded_instance_types/CHANGELOG.md, cost/azure/superseded_instance_types/azure_superseded_instance_types.pt
For the Azure specific policies that have escalations that interact with the Azure API, auth may fail if the client secret includes characters that should be URL encoded.
=> Fix for Azure API Client Secret Encoding

cost/cheaper_regions/CHANGELOG.md, cost/cheaper_regions/cheaper_regions.pt
tag_instance_name dimension is unused and unnecessary. 
=> Cheaper Regions Remove tag_instance_name dimension

README.md, cost/google/object_storage_optimization/CHANGELOG.md, cost/google/object_storage_optimization/README.md, cost/google/object_storage_optimization/google_object_storage_optimization.pt
This Policy checks Google buckets for older objects and can move the old object to 'nearline' or 'coldline' after a given period of time. The user can choose to delete the old object by enabling 'delete action' option as mentioned in Enable delete action section below.
- This policy identifies all Google storage objects last updated outside of the specified timeframe
- For all objects identified as old, the user can choose to move the object to 'nearline' or 'coldline' after the specified timeframe.
- The user can choose to delete the old object by enabling 'delete action' option as mentioned in Enable delete action section below.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5d822e430178e60089acb7da
=> POL-106 Google Object Storage Optimization

cost/aws/s3_bucket_size/CHANGELOG.md, cost/aws/s3_bucket_size/aws_bucket_size.pt, security/aws/rds_publicly_accessible/AWS_Publicly_Accessible_RDS_Instances.pt, security/aws/rds_publicly_accessible/CHANGELOG.md, security/aws/rds_unencrypted/AWS_Unencrypted_RDS_Instances.pt, security/aws/rds_unencrypted/CHANGELOG.md, security/storage/aws/s3_buckets_without_server_access_logging/CHANGELOG.md, security/storage/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
Updated region datasources to use github data list
Identified AWS policies that used  hard coded list of regions and replaced it with the region list file in github.
Referring Regions from github and removed datasource which we were not using internally. I tested policies and are working fine.
=> POL-118 Update region datasources to use github data list

compliance/azure/subscription_access/CHANGELOG.md, compliance/azure/subscription_access/README.md, compliance/azure/subscription_access/azure_subscription_access.pt
Adds a filter to the role assignment call to only gather assignments from the root of the subscription.
n/a
=> AzureRM Subscription Access - Root Level Assignments

cost/scheduled_reports/CHANGELOG.md, cost/scheduled_reports/README.md, cost/scheduled_reports/scheduled_report.pt
More flexibility on date ranges in scheduled report policy
This policy allows you to set up scheduled reports that will provide summaries of cloud cost across all resources in the billing centers you specify, delivered to any email addresses you specify
Provided option to display chart with different granularity.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5db933858f333d000126269b
=> POL-78 More flexibility on date ranges in scheduled report policy

README.md, compliance/aws/long_stopped_instances/CHANGELOG.md, compliance/aws/long_stopped_instances/README.md, compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt
POL-26-AWS - Check for long-stopped instances
Check for instances that have been stopped for a long time.
Terminate AWS instances that are stopped for a long time.
Running Link:
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5dcbe0813202b80001bc4c4d
=> POL-26-AWS - Check for long-stopped instances

security/storage/aws/s3_buckets_without_server_access_logging/CHANGELOG.md, security/storage/aws/s3_buckets_without_server_access_logging/README.md, security/storage/aws/s3_buckets_without_server_access_logging/aws_s3_buckets_without_server_access_logging.pt
Fix for bug POL-176
This policy checks for any S3 buckets that don't have Server Access logging enabled and allows the user to enable logging after approval.
- Changes to support the Credential Service
- Changed Http method to PUT for define enable_logging.
https://governance.rightscale.com/org/1105/projects/60073/policy-incidents/5e2967bf4ec7b300014e6b55
=> POL-176-AWS-S3-Buckets-without-Server-Access-Login

msp/cost/master_org_cost_policy/CHANGELOG.md, msp/cost/master_org_cost_policy/README.md, msp/cost/master_org_cost_policy/master_org_cost_policy.pt
Some users have access to hundreds of orgs, so the org exclude list can be quite big as well. This PR adds a new optional parameter, param_exclude_organizations_ids which has the same functionality as param_exclude_organizations just that using org id's instead of org names.
=> SRE1-194_add_exclude_org_id_parameter_to_master_org_cost_policy

msp/cost/master_org_cost_policy/CHANGELOG.md, msp/cost/master_org_cost_policy/master_org_cost_policy.pt
This will allow to use the policy without using any exclude parameters
This pr fix the case when any of param_exclude_organizations or param_exclude_organizations_ids parameters are used.
Example of new case fixed:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e622efa5af98600017a5843
param_exclude_organizations=[]
param_exclude_organizations_ids=[]
=> SRE1-668_fix_excudled_orgs_js

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Subscription Name was not getting replicated in the final response from Azure Idle Compute Instances
Subscription Name issue has been resolved
Log link:
https://governance.rightscale.com/org/1105/projects/60073/applied-policies/5e6607e4daa77500017519f4
=> POL-227-Subscription Name is missing from Policies

operational/azure/azuread_group_sync/CHANGELOG.md, operational/azure/azuread_group_sync/README.md, operational/azure/azuread_group_sync/azuread_group_sync.pt
Enhancement to the policy to remove the need for a CMP refresh token and instead use inherited auth.
N/A
=> POL-307: Azure AD - Remove need for refresh token

cost/aws/unused_volumes/README.md
The sample AWS IAM policy JSON for the AWS Unused Volumes policy template had an incorrect version and was two separate documents with confusing formatting.
=> Fix sample IAM policy documents for AWS Unused Volumes

cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/README.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt, cost/aws/unused_volumes/aws_delete_unused_volumes.pt
The AWS Unused IP Addresses policy template had a typo in the parameter name `param_exlude_tags` which should be `param_exclude_tags`. Also, the AWS IAM policy document for Credentials for the policy template was not formatted correctly in the README.
=> Fix parameter name typo and IAM policy formatting in AWS Unused IP Addresses policy template

cost/aws/schedule_instance/CHANGELOG.md, cost/aws/schedule_instance/README.md, cost/aws/schedule_instance/aws_schedule_instance.pt
modified the policy to handle start or stop time values without minute value.
=> Pol 356 aws schedule instances action not working

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt
Changed the default deregister image action from Yes to No.
=> POL-384 Updated AWS Old snapshots deregister image action.

compliance/aws/ecs_unused/aws_unused_ecs_clusters.pt, compliance/aws/instances_without_fnm_agent/aws_instances_not_running_flexnet_inventory_agent.pt, compliance/aws/long_stopped_instances/aws_long_stopped_instances.pt, compliance/aws/untagged_resources/aws_untagged_resources.pt, cost/aws/burstable_instance_cloudwatch_credit_utilization/aws_burstable_instance_cloudwatch_credit_utilization.pt, cost/aws/elb/clb_unused/aws_delete_unused_clb.pt, cost/aws/idle_compute_instances/idle_compute_instances.pt, cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt, cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt, cost/aws/rds_instance_license_info/rds_instance_license_info.pt, cost/aws/schedule_instance/aws_schedule_instance.pt, cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt, cost/aws/unused_rds/unused_rds.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt, operational/aws/instance_scheduled_events/aws_instance_scheduled_events.pt, operational/aws/long_running_instances/long_running_instances.pt, operational/aws/subnet_name_sync/aws_subnet_name_sync.pt, operational/aws/vpc_name_sync/aws_vpc_name_sync.pt, operational/dbaas/aws/rds_backup/aws_rds_backup.pt, policy_templates.code-workspace, security/aws/clb_unencrypted/aws_clb_encryption.pt, security/aws/ebs_unencrypted_volumes/aws_unencrypted_volumes.pt, security/aws/elb_unencrypted/aws_elb_encryption.pt, security/aws/loadbalancer_internet_facing/aws_internet-facing_elbs.pt, security/aws/rds_publicly_accessible/aws_publicly_accessible_rds_instances.pt, security/aws/rds_unencrypted/aws_unencrypted_rds_instances.pt
- Update the AWS Unused Volumes, AWS Old Snapshots, and AWS Unused IP
Addresses policy templates to use the actual calls to determine if
each region is available via SCP since we have discovered that using
`DescribeRegions` in each particular region does not work reliably
(the `DescribeRegions` call could be enabled for all regions while
other calls are not).
- Add the Code Spell Checker extension to the suggested VS Code
extensions and fix up some misspellings it found.
- Removed confusing ignored `host "ec2.amazonaws.com"` lines from all of
the `ds_regions` datasources.
=> Fix AWS Regions with SCP for FinOps Policies

cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
The AWS Unused IP Addresses policy template was detecting EIPs attached to NAT gateways as if they were not attached because it did not check the `associationId` field.
=> Check association ID in AWS Unused IP Addresses policy template

operational/vmware/instance_tag_sync/README.md
removed insecure flag from readme file
=> Copy-POL-394-VMWare-Tags-Sync-Policy

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- Add `min_value`s to the age parameters in the AWS Old Snapshots and AWS Unused Volumes policy templates
I believe the policies may work fine with other non-negative values, but I would think that `1` is a reasonable minimum.
=> Use Policy Templates on a few parameters

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt, cost/azure/unattached_volumes/CHANGELOG.md, cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt
POL-398-Display-cost-for-each-resources-under-all-the-azure-subscription-ids-available-from-Optima-in-Azure-policies-for-Savings
- Updated the policy to fetch and display cost for each resource under all the subscription ids from Optima
=> POL-398-Display-cost-for-each-resources-under-all-the-azure-subscription-ids-available-from-Optima-in-Azure-policies-for-Savings

data/aws/instance_types.json
Updated Superseded value for m4.16xlarge from m5.24xlarge to  m5.16xlarge
Right size for m4.16xlarge
=> Updated JSON file with "m5.16xlarge" instead of m5.24xlarge

compliance/aws/scp_audit/CHANGELOG.md, compliance/aws/scp_audit/aws_scp_audit.pt
Fixes pagination to add the `NextToken` to the body instead of query params
N/A
=> AWS Service Control Policy - Pagination Fix

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/README.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/README.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Adds a parameter to the AWS Old Snapshots and AWS Unused Volumes policy templates to override the Flexera One org ID to use when querying Optima for cases when the project is not in the same org where the AWS bill is registered in Optima. The default value for this new parameter is `current` which duplicates the old behavior of using the `rs_org_id` keyword to get the current org ID, so the new behavior will only be triggered if a different org ID value is entered in the parameter. This behaviour is needed in order to get useful cost/savings estimates from these policies for the Flexera FinOps Team's use case where various engineering Flexera One projects that are associated with AWS accounts are not in the same org where we have the AWS bill registered in Optima.
None
=> Configurable Optima org for AWS Old Snapshots and AWS Unused Volumes

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt, policy_templates.code-workspace
- Improve the error handling and debug logging of the AWS Old Snapshots, AWS Unused IP Addresses, and AWS Unused Volumes policy templates so that errors from CWF actions are actually surfaced.
- Add a `param_log_to_cm_audit_entries` parameter to control whether action debug logging is sent to CM Audit Entries; this should be left turned off on Flexera EU.
=> Improve action error handling and debug logging for FinOps

cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt
- Increase the sleep time between calls to AWS for snapshot status in order to decrease the likelihood of hitting a Cloud Workflow event limit
=> AWS Unused Volumes: Sleep more to be friendly to CWF

compliance/github/repository_branch_protection/CHANGELOG.md, compliance/github/repository_branch_protection/README.md, compliance/github/repository_branch_protection/repository_branch_protection.pt
Current issues:
- **GitHub Api Rate limit**: Running current version every hour or less will consume too many calls from the limit.
- **Default Branch**: In the current version is not possible to protect the default branch, it only accept a list of branches which can be different from the real default branch.
- **Minimum configuration**: Current version doesn't change the protection configuration if it doesn't match the parameters, it only checks if there is a branch protection
This PR is fixing the top two issues by using GitHub GraphQL API to grab the data with less api calls (e.g.: 6 calls for flexera with 550 repos) and also to check the default branch instead of using a branch list.
Mentioned above.
=> CET-977 Use GitHub GraphQL for enforcing branch protection

cost/scheduled_reports/CHANGELOG.md, cost/scheduled_reports/scheduled_report.pt
The scheduled report policy template was building a list of top 10 values (categories) for the considered dimension by cost, but based on the current month only, not all months in the data. If there was no data for the current months, that top 10 list would be empty => everything ended up lumped into the "Other" bucket.
The fix is to considered all the data to build that top 10 list by cost, and not just the current month.
https://jira.flexera.com/browse/POL-417
=> POL-417: top 10 cost categories not just for current month.

compliance/azure/azure_untagged_resources/CHANGELOG.md, compliance/azure/azure_untagged_resources/untagged_resources.pt
In the Flexera EU application, no CM will be available; any (cost/compliance) policy that we want to roll out there and is currently logging to CM Audit Entries needs to be revised. For instance, add a param to switch those logs on/off (default: off).
* compliance/azure/azure_untagged_resources/untagged_resources.pt: template had a `sys_log` function (to log to CM audit entries) that is actually not used, so I just removed it.
See: https://jira.flexera.com/browse/IND-4243
=> IND-4243: Policies can't log to CM audit entries in EU, so disable that (e.g. via param).

cost/google/old_snapshots/CHANGELOG.md, cost/google/old_snapshots/google_delete_old_snapshots.pt
Fields `start_date` and `end_date` added by script `js_time`, and datasource `ds_time` were actually never used in the policy, and all can be removed without affecting the functionality of the template.
In relation to https://jira.flexera.com/browse/POL-424.
=> POL-424: Cleaning up "deadwood" code.

cost/budget_alerts/CHANGELOG.md, cost/budget_alerts/budget_alert.pt
Fixed the alignment in the HERE doc for the markdown that gets added to the email.
The extra whitespace at the start of lines was causing the conversion to HTML to fail for the email.
https://jira.flexera.com/browse/IND-4219
=> IND-4219: Fixed HERE doc markdown alignment.

compliance/azure/azure_untagged_resources/CHANGELOG.md, compliance/azure/azure_untagged_resources/untagged_resources.pt
In the "Tag Resources" action, drop the provider's namespace from the resource type when looking up supported API versions,
since the resource types in the provider object don't have that namespace prepended.
https://jira.flexera.com/browse/POL-425
=> POL-425: Drop namespace from resource type when looking up API versions.

cost/google/old_snapshots/CHANGELOG.md, cost/google/old_snapshots/google_delete_old_snapshots.pt
See also corresponding ticket below. The pagination was missing from the request for all snapshots, which meant only one page was retrieved, and therefore quite a few snapshots were being missed.
This fix adds the pagination to the request, so that all pages and therefore all snapshots get retrieved.
https://jira.flexera.com/browse/POL-424
=> POL-424: Added missing pagination to GCP request for snapshot list.

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
When retrieving the Monitor/Metrics, use the right API version, and the biggest possible interval to minimise the number of data points (that's one day, ie "P1D" in ISO 8601 duration notation).
https://jira.flexera.com/browse/POL-427
=> POL-427: for metrics, right api-version, and one-day interval.

README.md, cost/azure/hybrid_use_benefit_sql/CHANGELOG.md, cost/azure/hybrid_use_benefit_sql/README.md, cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
Initial release for an AHUB for SQL policy
This is a new policy for checking eligible SQL instances (SQL VM, SQL DB and SQL Managed Instance) in Azure for using the AHUB benefit for SQL. After identification AHUB can be automatically applied on selected instances.
=> Initial release AHUB for SQL

cost/superseded_instance/CHANGELOG.md, cost/superseded_instance/superseded_instance.pt
Using the current month to pull cost fails to pick up enough (or any) data at the beginning of the month: make sure at least one month of costs is retrieved to make sure we have a workable dataset.
https://jira.flexera.com/browse/CMLS-9
=> CMLS-9 POL-418: ensure >= 1 mo cost data retrieved

cost/azure/schedule_instance/CHANGELOG.md, cost/azure/schedule_instance/azure_schedule_instance.pt
The `delete schedule` action wasn't actually removing any tags; fixed that, to now remove the `schedule`, `next_start` and `next_stop` tags.
https://jira.flexera.com/browse/CMLS-8
=> CMLS-8: Fix the "delete schedule" action to actually delete the schedule tag (and related tags).

cost/aws/reserved_instances/report_by_bc/CHANGELOG.md, cost/aws/reserved_instances/report_by_bc/ri_report_by_bc.pt, cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt, cost/azure/schedule_instance/CHANGELOG.md, cost/azure/schedule_instance/azure_schedule_instance.pt
... for templates Azure Expiring RIs and (AWS) RI report by billing center.
(For the EU region, I can't use the built-in rightscale auth anymore; that's why it's replaced by a OAuth2 credentials (for now, until Phoenix implements a new built-in one).
All those changes are only done into a specific branch, EU_Policies (since this is kind of a temporary work-around, probably until ~Q4 when Phoenix gets their bit done), and not master.
The bit in my PR about the Azure scheduled instances is a merge from master into EU_Policies that I "piggy-backed" onto this PR.)
https://jira.flexera.com/browse/CMLS-26
https://jira.flexera.com/browse/CMLS-27
=> CMLS-26 CMLS-27: Use OAuth2 FlexeraOne creds in EU region, and use rs_optima_host

cost/budget_v_actual/monthly_budget_v_actual.pt, cost/instance_anomaly/instance_anomaly.pt, cost/superseded_instance/superseded_instance.pt
Temporarily replace rightscale built-in auth with FlexeraOne OAuth2 credentials (until proper built-in F1 creds are available).
No updating the CHANGELOG: this is a specific branch (`EU_Policies`), temp workaround just for EU, avoid potential merge
conflicts with other changes in the main branch.
https://jira.flexera.com/browse/CMLS-31
https://jira.flexera.com/browse/CMLS-32
=> CMLS-31 CMLS-32 CMLS-34: RightScale auth to FlexeraOne OAuth2

cost/budget_alerts/CHANGELOG.md, cost/budget_alerts/README.md, cost/budget_alerts/budget_alert.pt
Adds a new parameter for budget threshold so customers can be alerted based on percentage of budget met. 
=> POL-442 Adding Budget Alert Threshold

cost/cheaper_regions/CHANGELOG.md, cost/cheaper_regions/cheaper_regions.pt
Added check that AWS account array is not empty before assigning it
Bug with error "Cannot access member 'name' of undefined" from trying to access an empty array
=> POL-430 add check that AWS account array name exists before assigning it

data/aws/instance_types.json
Updates the instance size mapping table to support db.m6g.*, db.r6g.*,  and db.t1.micro
=> July 7th 2021 - Add Missing RDS Instance Sizes

cost/aws/rds_instance_cloudwatch_utilization/CHANGELOG.md, cost/aws/rds_instance_cloudwatch_utilization/rds_instance_cloudwatch_utilization.pt
This update fixes the logic in the policy that calculates the next instance size to reflect "N/A" as opposed to failing if the next instance size is not captured in the instance_types.json mapping file.
=> POL-445: RDS Rightsizing Policy: Update next instance size logic to account for missing size

cost/google/old_snapshots/CHANGELOG.md, cost/google/old_snapshots/google_delete_old_snapshots.pt
Add checks on the `labels` field: it may be `null`, or `undefined`.
https://jira.flexera.com/browse/CMLS-83
=> CMLS-83: Add checks on labels field

compliance/azure/azure_untagged_resources/CHANGELOG.md, compliance/azure/azure_untagged_resources/untagged_resources.pt
Microsoft is not consistent with the case of its resource types; work around this by converting to lower case when|
comparing types from various sources across Microsoft.
https://jira.flexera.com/browse/POL-449
=> POL-449: Convert resource type to lowercase for comparisons

cost/google/recommender/CHANGELOG.md, cost/google/recommender/README.md, cost/google/recommender/recommender.pt
Adds functionality to the Google Recommender policy. Specifically, it adds Cost and Currency fields to the incident output so that the user knows how much money is at stake, and it allows (optionally) the policy to filter by specific projects if desired by the end user. 
I have tested these changes and found no errors or problems.
=> Pol 508 add cost to google recommender

cost/aws/elb/clb_unused/CHANGELOG.md, cost/aws/elb/clb_unused/aws_delete_unused_clb.pt, cost/aws/gp3_volume_upgrade/CHANGELOG.md, cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt, cost/aws/idle_compute_instances/CHANGELOG.md, cost/aws/idle_compute_instances/idle_compute_instances.pt, cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/unused_rds/CHANGELOG.md, cost/aws/unused_rds/unused_rds.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt, cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt, cost/azure/old_snapshots/CHANGELOG.md, cost/azure/old_snapshots/azure_delete_old_snapshots.pt, cost/azure/unattached_volumes/CHANGELOG.md, cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt, cost/azure/unused_ip_addresses/CHANGELOG.md, cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
- A number of Policy Templates for cost were looping through all of the costs they have retrieved from Optima on each iteration in order to find the costs relevant for each particular resource. This is inefficient and potentially causes evaluation timeouts that could be avoided. Instead, a map of only the relevant costs to resource IDs is constructed and used for fast lookups during iteration.
- Cleaned up some whitespace and spelling issues.
POL-515
=> Fix non-optimal array searching for costs

security/aws/log_ensure_cloudtrail_bucket_not_public/CHANGELOG.md, security/aws/log_ensure_cloudtrail_bucket_not_public/README.md, security/aws/log_ensure_cloudtrail_bucket_not_public/log_ensure_cloudtrail_bucket_not_public.pt
Adds a policy for AWS CIS 3.3 Ensure the S3 bucket used to store CloudTrail logs is not publicly accessible
Policy has been tested and works as expected.
=> AWS CIS 3.3 Ensure the S3 bucket used to store CloudTrail logs is not publicly accessible

.vscode/settings.json, cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/README.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
- Improve savings calculations by using the AWS Pricing API which is significantly faster and more memory efficient than retrieving the AWS price sheet JSON file
FINOPS-112
=> FINOPS-112 Use AWS Pricing API for AWS Unused IP Addresses

README.md, compliance/fnms/vms_missing_hostid/CHANGELOG.md, compliance/fnms/vms_missing_hostid/README.md, compliance/fnms/vms_missing_hostid/vms_missing_hostid.pt
ITAM Policy to find VMs without a Host ID. Policy has been tested and works as expected.
=> ITAM Policy: VMs Without Host ID

README.md, security/azure/blob_storage_logging/CHANGELOG.md, security/azure/blob_storage_logging/README.md, security/azure/blob_storage_logging/blob_storage_logging.pt, security/azure/table_storage_logging/CHANGELOG.md, security/azure/table_storage_logging/README.md, security/azure/table_storage_logging/table_storage_logging.pt
Azure CIS 3.10/3.11 Ensure Storage logging is Enabled for Blob/Table Service for 'Read', 'Write', and 'Delete' requests
tested and working
(Two policies in one pull request because they are extremely similar to one another)
=> Azure CIS 3.10/3.11 Ensure Storage logging is Enabled for Blob/Table Service for 'Read', 'Write', and 'Delete' requests

compliance/aws/disallowed_regions/CHANGELOG.md, compliance/aws/disallowed_regions/README.md, compliance/aws/disallowed_regions/aws_disallowed_regions.pt
This is a modification of the AWS Disallowed Regions Policy. The user now has to specify a list of regions to allow rather than a list of regions to disallow. There's also been some general cleanup to bring the policy more in line with our current best practices.
Tested and works as expected.
=> POL-611 Invert AWS Disallowed Regions Policy

cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md, cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt, cost/google/cud_recommendations/CHANGELOG.md, cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt, cost/google/idle_ip_address_recommendations/CHANGELOG.md, cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt, cost/google/idle_persistent_disk_recommendations/CHANGELOG.md, cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt
Re-adding missing savings field to google spend policies
Fixes issue of spend data not showing in app.flexera.com
=> IND-5216 updated fields for savings and updated changelog

.github/workflows/update_eu_policies.yml
Modifies the GitHub Actions workflow that creates a "Release Candidate" Pull Request to sync changes from `master` branch into `EU_Policies` branch.
Disabling random branch creation will reduce the amount of Pull Requests that are created by this automation and disable the amount of manual cleanup necessary.  Using alternative branching strategies like random is also [not recommended by the actions developer](https://github.com/peter-evans/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch).
=> Fix: Disable random branch suffix on Actions Workflow

tools/policy_sync/CHANGELOG.md, tools/policy_sync/policy_sync.pt
Adds `auth: $$auth_rs` to the Flexera API requests in CWF definition.  Currently actions are receiving unauthorized and this is the reason EU Policies are not being published/updated as expected.
=> Fix: Add `auth: $$auth_rs` for authentication to policy sync template

.github/workflows/update_eu_policies.yml
Reverts changes from #1066 .  This is required because we can't resolve conflicts with a `master` -> `EU_Policies` PR (Example in https://github.com/flexera-public/policy_templates/pull/1067 )
=> Revert #1066

cost/azure/storage_account_lifecycle_management/CHANGELOG.md, cost/azure/storage_account_lifecycle_management/README.md, cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management.pt
Added functionality to allow requests to be delayed to avoid having the Azure API throttle the user. I've tested the policy and it works as expected. No other functionality was added.
(Change was made to accommodate PepsiCo but I saw no reason not to just make it available to everyone)
=> Throttling - Azure Storage Accounts without Lifecycle Management Policies

cost/aws/FlexeraReadOnlyPolicy.template
Added condition for sts:AssumeRole action
FlexeraReadOnly CloudFormation template was not working previously. This PR is to fix this.
=> POL-669 Update FlexeraReadOnly cft

README.md, operational/aws/tag_cardinality/CHANGELOG.md, operational/aws/tag_cardinality/README.md, operational/aws/tag_cardinality/aws_tag_cardinality.pt, operational/azure/tag_cardinality/CHANGELOG.md, operational/azure/tag_cardinality/README.md, operational/azure/tag_cardinality/azure_tag_cardinality.pt
Adds policies for AWS and Azure to generate tag cardinality reports. These policies have been tested.
Does not currently include GCP; this is TBD due to difficulties with the GCP API.
=> Tag cardinality

cost/azure/schedule_instance/CHANGELOG.md, cost/azure/schedule_instance/README.md, cost/azure/schedule_instance/azure_schedule_instance.pt
- Modified cloud workflow Azure API to change `powerOff` to `deallocate` to release resources and start savings
- Mofified Azure API version to most updated `2022-08-01`
Scheduled instances was using /powerOff api command but this did not allow for savings for shut off.
=> POL-713-changing-powerOff-deallocate

.github/workflows/cfn-test.yaml, cost/aws/idle_compute_instances/README.md, cost/aws/unused_rds/README.md, tools/cloudformation-template/FlexeraAutomationPolicies.template, tools/cloudformation-template/README.md, tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.1.1.template
Policies were refactored to use GetMetricData but the README was not updated at that time.  This fixes that issue.
The CF Template that is used to create Roles for IAM had it's permissions updated as well to include GetMetricData.
=> Fix: CF Template and README to add `cloudwatch:GetMetricData`

cost/azure/unused_ip_addresses/CHANGELOG.md, cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt
Bug fixes - 
- added `ignore_status` for 400 and 404 error codes on Azure APIs to prevent policy from failing when iterating over certain subscriptions
- added condition to handle `resourceType` field where it is equal to null, again to prevent policy from failing
=> POL-731 Update Azure Unused IP Addresses

cost/aws/savings_realized/CHANGELOG.md, cost/aws/savings_realized/aws_savings_realized.pt, cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
This is a PR to resolve a mistake with the Azure and AWS Savings Realized from Reservations policies which make reference to "Fastly Billing" in description
See https://flexera.atlassian.net/browse/POL-741 for more info
=> POL-741 Update AWS/Azure Savings Realized - period start/end parameters showing Fastly

cost/scheduled_reports/CHANGELOG.md, cost/scheduled_reports/scheduled_report.pt
Fixed issue with incorrectly-rendered graph when selecting "Week" for the Billing Term parameter
=> For for Graph when using "Week"

compliance/fnms/fnms_licenses_expiring/CHANGELOG.md, compliance/fnms/fnms_licenses_expiring/expiring_licenses.pt, compliance/fnms/ignored_recent_inventory_dates/CHANGELOG.md, compliance/fnms/ignored_recent_inventory_dates/ignored_recent_inventory_dates.pt, compliance/fnms/missing_active_machines/CHANGELOG.md, compliance/fnms/missing_active_machines/missing_active_machines.pt, compliance/fnms/overused_licenses/CHANGELOG.md, compliance/fnms/overused_licenses/overused_licenses.pt, compliance/fnms/vms_missing_hostid/CHANGELOG.md, compliance/fnms/vms_missing_hostid/vms_missing_hostid.pt
Replaced hardcoded host in all ds using f1_app_host as base.
ITAM policies are hardcoded for NAM, more info: [Here](https://flexera.atlassian.net/browse/HCLIND-47).
=> HCLIND-47 Fix: ITAM policies are hardcoded for NAM

cost/azure/reserved_instances/expiration/CHANGELOG.md, cost/azure/reserved_instances/expiration/azure_reserved_instance_expiration.pt
Now already expired instances are filtered from the final report.
- [HCLIND-7 issue was addressed:](https://flexera.atlassian.net/browse/HCLIND-7) Expired instances were being included in the report sent to the user, now those instances are being filtered (filter instance from final report if already expired).
=> HCLIND-7 Remove already expired instances from the report generated by Azure Expiring Reserved Instances PT

cost/cloud_cost_anomaly_alerts/CHANGELOG.md, cost/cloud_cost_anomaly_alerts/README.md, cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Get dynamic TLD depending of current "rs_governance_host".
Link to the report seems to be hardcoded to US shard.
=> HCLIND-4 Fix: Hardcoded TLD in cloud_cost_anomaly_alerts.pt to US

cost/forecasting/moving_average/CHANGELOG.md, cost/forecasting/moving_average/moving_average_forecast.pt, cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md, cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt, cost/forecasting/straight_line_forecast/simple/CHANGELOG.md, cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt, operational/aws/total_instance_hours_forecast/CHANGELOG.md, operational/aws/total_instance_hours_forecast/aws_total_instance_hrs_forecast.pt, operational/aws/total_instance_vcpus_forecast/CHANGELOG.md, operational/aws/total_instance_vcpus_forecast/aws_total_instance_vcpus_forecast.pt
This is to fix a bug in the forecasting policies where the Start Date and End Date used to call the Aggregated Costs API clash. See details of the identified error below:
The logic in the “js_generate_past_month_list” script must be rewritten to prevent this problem from happening
Link to Jira ticket - https://flexera.atlassian.net/browse/POL-756 
=> POL-756 Update Forecasting Policies - fix start/end date clash

README.md, cost/aws/rightsize_compute_instances/CHANGELOG.md, cost/aws/rightsize_compute_instances/README.md, cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
As part of this PR - produce one policy for rightsizing that includes a threshold for idle (default <5%) and underutilized (default <40%) - options for both CPU and RAM stats (if available from log sources).  Cost savings for idle as per current policy.  Cost savings for rightsizing = 50% of idle calculation (i.e. assumption next instance size down = 50% cheaper).  Bring in instance size recommendations from current Inefficient Utilization policies.
=> POL-693 AWS Instance Rightsizing - Merge Idle Instances and Inefficient Instance Utilization

cost/forecasting/commitment_forecast/CHANGELOG.md, cost/forecasting/commitment_forecast/commitment_forecast.pt
Vendor Commitment Forecast policy has incident fields however the fields are not populating.
Linked to this ticket - https://flexera.atlassian.net/browse/SQ-1379
Removal of URI Encoding on Spend Data means that Vendor Commitment Forecast policy incident now populates with data
=> POL-765 Vendor Commitment Forecast fix: incident table not populating

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Actions were not working with this policy due to CWF referring to subscriptionID instead of accountID. I have corrected this and confirmed that actions now work as expected.
=> POL-771 azure idle compute CWF fix

cost/aws/elb/clb_unused/CHANGELOG.md, cost/aws/elb/clb_unused/aws_delete_unused_clb.pt, cost/aws/gp3_volume_upgrade/CHANGELOG.md, cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt, cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/unused_rds/CHANGELOG.md, cost/aws/unused_rds/unused_rds.pt, cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt, cost/azure/old_snapshots/CHANGELOG.md, cost/azure/old_snapshots/azure_delete_old_snapshots.pt, cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightisizing.pt, cost/azure/unattached_volumes/CHANGELOG.md, cost/azure/unattached_volumes/azure_delete_unattached_volumes.pt, cost/azure/unused_ip_addresses/CHANGELOG.md, cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt, cost/azure/unused_sql_databases/CHANGELOG.md, cost/azure/unused_sql_databases/azure_unused_sql_databases.pt
Raised the limit field from 10000 to 100000 for several policies to ensure that they work correctly when more than 10000 line items are involved. 100000 is the maximum that the API currently supports.
=> POL-764 limit raise

cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt, cost/turbonomics/rightsize_databases_recommendations/azure/turbonomics_rightsize_databases_recommendations.pt, cost/turbonomics/rightsize_databases_recommendations/gcp/turbonomics_rightsize_databases_recommendations.pt, cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt, cost/turbonomics/rightsize_virtual_volumes_recommendations/azure/turbonomics_rightsize_virtual_volumes_recommendations.pt, cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
Currently this two policies are published on Automation Catalog:
_cost/turbonomics/rightsize_databases_recommendations/*/turbonomics_rightsize_databases_recommendations.pt_
_cost/turbonomics/rightsize_virtual_volumes_recommendations/*/turbonomics_rightsize_virtual_volumes_recommendations.pt_
This isn't the expected behavior, so we added `publish: false` on info block to prevent it.
Undesired policies published on Automation Catalog.
=> HCLIND-62 Fix: Prevent publish Turbonomic Rightsize Databases/Virtual Volumes policies

.idea/inspectionProfiles/Project_Default.xml, cost/turbonomics/buy_reserved_instances_recommendations/aws/CHANGELOG.md, cost/turbonomics/buy_reserved_instances_recommendations/aws/README.md, cost/turbonomics/buy_reserved_instances_recommendations/aws/turbonomics_buy_reserved_instances.pt, cost/turbonomics/buy_reserved_instances_recommendations/azure/CHANGELOG.md, cost/turbonomics/buy_reserved_instances_recommendations/azure/README.md, cost/turbonomics/buy_reserved_instances_recommendations/azure/turbonomics_buy_reserved_instances.pt
Allows to review in Flexera CCO the cost savings due to Buy RI recommendations, so I can slice and dice them by billing centers.
Create a new automation policy to retrieve Buy RI recommendations for cloud environments via Turbonomic APIs.
Aws : https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=6411b4829f94b400016e18d9
Azure : https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=6411b5199f94b400016e18da
=> HCLIND-39 Turbonomics Buy Reserved Instances Recommendations.

cost/google/idle_persistent_disk_recommendations/CHANGELOG.md, cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt
This change addresses https://flexera.atlassian.net/browse/FOPTS-198
Previously, the policy had to do a lot of API calls to get all the volumes from all the GCP accounts and its zones, now those API calls were reduced to only one thanks to aggregated GCP endpoints.
https://flexera.atlassian.net/browse/FOPTS-198
Link to applied policy v2.4: https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=641b676d94f0030001544aa1
Link to applied policy v2.5: https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=641b632dff3f0400013d12ae
=> FOPTS-198 Performance Boost for Google Idle Persistent Disk Recommender

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
This policy was incorrectly including idle resources in both the idle incident and the underutilized incident.
I have adjusted the check statement for each incident to fix this and ensure that the policy does not have duplicate resources in both incidents, and to ensure it functions identically to what the README says it does.
=> Azure Rightsize Compute Instances Fix

cost/aws/object_storage_optimization/CHANGELOG.md, cost/aws/object_storage_optimization/README.md, cost/aws/object_storage_optimization/aws_object_storage_optimization.pt
This just adds the additional code needed for this policy to work as a child policy.
Functionality as a regular policy is unchanged apart from the addition of a Flexera credential, since this is needed for the child policy functionality but was not present in the original policy.
The version is also bumped from 2.9 to 3.0, so even if the above is considered a "breaking change" (I imagine most customers have a Flexera credential at this point), the major version number also changed.
=> Add Child Policy Code to AWS Object Storage Optimization Policy

cost/azure/hybrid_use_benefit_sql/CHANGELOG.md, cost/azure/hybrid_use_benefit_sql/ahub_sql.pt
Added a filter to exclude SQL Developer & Express Server Edition instances that Microsoft Azure Virtual Machines provides as free
Costs were being added for virtual machines that are currently free by the provider, a filter was made on those instances to exclude them from the benefits for the client
=> FOPTS-228 Added a filter at instances for free SQL Developer & Express versions in Azure VM

operational/aws/tag_cardinality/CHANGELOG.md, operational/aws/tag_cardinality/aws_tag_cardinality.pt
Fixes an issue causing the AWS Tag Cardinality to sometimes not work correctly.
For more information on why this error, which should have caused it to NEVER work correctly, only causes it to randomly sometimes not work correctly, hit me up because it is very strange.
=> Fix for AWS Tag Cardinality

cost/aws/unused_volumes/CHANGELOG.md, cost/aws/unused_volumes/aws_delete_unused_volumes.pt
Changed "Id" field in incident output to "ID" to match other policies and ensure proper reporting. 
I suspect this is causing the "ids" field to not appear in the action status for actions taken by this policy, which can impact someone's ability to use the policy API to see which specific resources were actioned.
The change is so minor, it is very unlikely to break the policy and it matches code in other policies.
There is no new functionality of note.
=> AWS Unused Volumes: Minor Incident Fix

data/aws/instance_types.json
Support for M6a was called out by generali as being missing from our rightsizing recommendations.  See attached list of all instance types in use by Generali, we ideally need to be able to provide alternatives for all of these instance types.
Details of instance types are here: https://aws.amazon.com/ec2/instance-types/
https://flexera.atlassian.net/browse/FOPTS-714
=> FOPTS-714 Add instance types to EC2 reference file

cost/budget_report_alerts/CHANGELOG.md, cost/budget_report_alerts/README.md, cost/budget_report_alerts/budget_report_alerts.pt
Threshold currently allows up to 100%. This parameter doesn’t accept an input that is above 100% (i.e. max budget). For many customers they are comfortable with a budget over run of up to 105% or 110%. Suggestion is to allow values over 100% to be entered by the user while applying the policy
https://flexera.atlassian.net/browse/FOPTS-717
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/105882?policyId=644a9a3a7b2db10001f85483
=> FOPTS-717 Remove limit for the threshold parameter for Budget Alert Policy

cost/aws/savings_plan/utilization/CHANGELOG.md, cost/aws/savings_plan/utilization/README.md, cost/aws/savings_plan/utilization/aws_savings_plan_utilization.pt
Improves usability of AWS Savings Plan Utilization policy for the `Inform` phase:
- Parameter `Savings Plan ARN` is now optional.  If not provided, the policy will return utilization for all Savings Plans in the account.
- Default threshold changed from `70` to `100`.  This policy template will send an e-mail for all Savings Plans by default now.
- Payer Account ID added to the Incident Summary.  This is helpful for users with multiple AWS Payer Accounts.
https://flexera.atlassian.net/browse/POL-809
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6446e2b67b2db10001f85426
=> POL-809: Enhancements for AWS Savings Plan Utilization

data/azure/mysql_flexible_tier_types.json
Adds Azure MySQL Instance Size Data for use with policies that need it. Data was produced manually, so long term we probably want to rely on an API to gather this data.
=> Adds Azure MySQL Instance Size Data (Related to POL-793)

data/azure/mysql_flexible_tier_types.json
mysql_flexible_tier_types.json has been updated with the following fixes and improvements:
- up_sku and down_sku keys have been added, since not every sku cleanly upscales or downscales to something with the same name.
- Lists were resorted to be more logical and readable.
- Standard_E80ids_v4 is no longer listed as a recommended SKU size for any of the other SKUs, since it is an odd one-off SKU. There are upsize/downsize recommendations for this SKU though.
=> mysql_flexible_tier_types.json Updates/Fixes

cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md, cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt, cost/google/idle_ip_address_recommendations/CHANGELOG.md, cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt, cost/google/idle_persistent_disk_recommendations/CHANGELOG.md, cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt
The current method we use to match data is producing duplicated entries because the resource name attribute is being used to match recommendations data and resource data, a more unique identifier such as an id needs to be used instead.
- The method to match resource data and cost data was changed in the policies:
- Google Idle VM Recommender
- Google Idle IP Address Recommender
- Google Idle Persistent Disk Recommender
- Google Cloud SQL Idle Instance Recommender
- The method to calculate savings using cost_nano and combine was changed.
- [Google Idle VM Recommender](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=645e1102d4f90e00019637c2)
- [Google Idle IP Address Recommender](https://app.flexeratest.com/orgs/1105/automation/applied-policies/proj …
=> FOPTS-805 Fix the method used to match recommendation and resource data at GCP Recommender policies

data/aws/instance_types.json
X2iedn instance types were added to our EC2 reference file. This work was done using the following documents:
- https://aws.amazon.com/ec2/instance-types/
- https://aws.amazon.com/blogs/aws/new-instance-size-flexibility-for-ec2-reserved-instances/
- https://aws.amazon.com/ec2/previous-generation/
According to those, X2iedn.* instances have the following features:
- They are NOT compatible with EC2 classic (`"ec2_classic": false`)
- They all have enhanced networking(`"enhanced_networking: true`)
- They do NOT have an upgrade path (`"superseded": null`)
Here are some screenshots:
- https://flexera.atlassian.net/browse/FOPTS-843
This change only adds data to a JSON file.
=> FOPTS-834 Add X2iedn AWS instance types

cost/azure/unused_volumes/CHANGELOG.md, cost/azure/unused_volumes/azure_unused_volumes.pt
Two bugs were discovered when attempting to use this policy with a client. First, the subscription filtering was not working and would generate an error. Second, the policy was not properly reporting savings (which also would sometimes cause the policy to generate an error). 
Additionally, because the tags were stored as an object in the incident, they were not properly visible in the incident output. This has been changed so that the tags are presented as a string.
The above described issues are resolved.
No example policy but I did test the fixes in the client's environment and both work as expected.
No README changes since functionality of the policy has not changed. These are just bug fixes.
=> Azure Unused Volumes - Bug Fixes

cost/forecasting/straight_line_forecast/linear_regression/CHANGELOG.md, cost/forecasting/straight_line_forecast/linear_regression/straight_line_forecast_linear_regression.pt, cost/forecasting/straight_line_forecast/simple/CHANGELOG.md, cost/forecasting/straight_line_forecast/simple/straight_line_forecast_simple.pt
Current Straight-Line Forecasting policies have parameter to select dimension to show forecasted cost by. This change adds an additional dimension to this list for Billing Center.
Straight-Line Forecast Linear Regression Model policy incident here - 
- By Billing Center dimension - https://app.flexera.com/orgs/30105/automation/incidents/projects/133807?incidentId=64679efcce98fd0001ce5fdd
- By Vendor Account Name dimension - https://app.flexera.com/orgs/30105/automation/incidents/projects/133807?incidentId=64679ddece98fd0001ce5fdc
Straight-Line Forecast Simple Model policy incident here - 
- By Billing Center dimension - https://app.flexera.com/orgs/30105/automation/incidents/projects/133807?incidentId=64679ba20da9b30001e2be9e
- By Vendor Account Name dimension - …
=> POL-797 Update Straight-Line forecasting policies with BC Dimension

cost/superseded_instance/CHANGELOG.md, cost/superseded_instance/superseded_instance.pt
Added check if instance has been upgraded or not. 2 calls are made to optima, one for 30 days and one for 7 days. The data is then evaluated to see if the instance type has changed at all to the `new_instance_type`.
[]
(https://flexera.atlassian.net/browse/POL-796?search_id=ce79fdcd-cb6e-4a6f-b6c5-222fd3d4da60)
https://app.flexera.com/orgs/27018/automation/incidents/projects/116186?incidentId=646295fb0da9b30001e2ba1b
=> Pol 796 superseded policy detect upgrades

README_META_POLICIES.md, cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt, cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt, cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt, cost/aws/rightsize_compute_instances/rightsize_compute_instances_meta_parent.pt, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt, cost/aws/unused_ip_addresses/aws_unused_ip_addresses_meta_parent.pt, cost/aws/unused_rds/unused_rds_meta_parent.pt, cost/aws/unused_volumes/aws_delete_unused_volumes_meta_parent.pt
This modifies the meta parent policies to include a consolidated incident containing all of the incident results from all of the child policies, as well as optionally email that consolidated incident.
This should greatly improve the user experience, since it eliminates the need to navigate through several layers of the UI to get to each individual child incident.
I've also modified the template in the Meta Policy README to include these changes.
=> Meta Parent Policy: Consolidated Incidents

cost/aws/rightsize_compute_instances/CHANGELOG.md, cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
Fixed issue where savings would always be 0 if policy were executed at the end of the month.
The above.
Tested in customer environment. Fix works as expected.
=> AWS Rightsize Cost Gathering Date Fix

cost/oracle/oracle_cbi/README.md
Updated the README for the Oracle Bill Ingestion policy to place special emphasis on the policy frequency. I have run into multiple instances recently of users setting the frequency to "daily" instead of leaving it at the default of "15 minutes", and this causes the policy to never manage to upload all of the files and commit the bill upload.
=> Oracle Bill Ingestion README Update

cost/google/cud_recommendations/CHANGELOG.md, cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt
Somehow, multiple 3.0 versions of this policy have ended up in the catalog in various places. This is a version bump to get everything properly synced to the current version.
=> Google Committed Use Discount Recommender Catalog Fix

cost/google/idle_compute_instances/google_idle_compute_instances.pt, cost/google/instances_stackdriver_utilization/google_instances_stackdriver_utilization.pt, cost/google/unattached_volumes/google_delete_unattached_volumes.pt, cost/google/unused_cloudsql_instances/google_unused_cloudsql_instances.pt, cost/google/unutilized_ip_addresses/google_unutilized_ip_addresses.pt
Policy to unpublish:
Google Unutilized IP Addresses
Google Idle Compute Instances
Google Unused CloudSQL Instances
Google Unused Volumes
Google Inefficient Instance Utilization using StackDriver
[Jira Ticket FOPTS-835](https://flexera.atlassian.net/browse/FOPTS-835)
=> FOPTS-835 - Unpublish Google cost policy duplicates of Google Recommender policies

cost/google/idle_compute_instances/CHANGELOG.md, cost/google/idle_compute_instances/google_idle_compute_instances.pt
https://flexera.atlassian.net/browse/FOPTS-957
The policy *Google Idle Compute Instances* is timing out with client tenant, so some optimizations successfully applied and tested in other Google policies like *Google Idle VM recommender* (this policy is very similar) were applied to enhance the performance, now the policy makes less API calls and processes less data thanks to GCP Monitoring Query Language.
Optimized the execution time of the policy by using the following approaches:
- CPU utilization data is now retrieved using GCP Monitoring Query Language; before, the Flexera platform did the calculations, but now those are done faster on GCP resources.
- Memory utilization data is now retrieved using GCP Monitoring Query Language; before, the Flexera platform did the calculations, but …
=> FOPTS-957 Google Idle Compute Instances policy timing out

cost/turbonomics/credential_refresh/CHANGELOG.md, cost/turbonomics/credential_refresh/README.md, cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
This policy is designed to refresh the authentication cookie used to authenticate with Turbonomic APIs. It addresses the challenge of using a cookie-based authentication method in Turbonomic, which is not supported by Flexera due to its outdated nature and the industry trend of switching to newer and more secure authentication methods. As Turbonomic plans to implement bearer token authentication in the future, this policy serves as a temporary workaround for the integration to connect to Turbonomic APIs.
https://flexera.atlassian.net/browse/FOPTS-939
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6481f829a9fd7a0001706578
=> FOPTS-939 - Add policy to refresh Turbonomic authentication token

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt, cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Update and standardize Azure usage reduction policies (Azure Unused Compute Instances and Rightsize Compute Instances).
Standardized Azure Unused Compute Instances and Azure Rightsize Compute Instances policy templates.
- Azure Unused Compute Instances: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=648c9add4466b10001e212e1
- Azure Rightsize Compute Instances: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=648c99e24466b10001e212e0
=> FOPTS-1121 Azure Usage Reduction Policies (Azure Unused Compute Instances and Rightsize Compute Instances)

cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md, cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt, cost/google/idle_ip_address_recommendations/CHANGELOG.md, cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt
We are adding some fields for the normalization of the Google policies, the fields are the following:
**cloud_sql_idle_instance_recommendations**
- Added `Lookback Period In Days` incident field.
- Added `Platform` incident field.
**idle_ip_address_recommendations**
- Added `IP Address` incident field.
**idle_vm_recommendations**
- Added `Lookback Period In Days` incident field.
- https://flexera.atlassian.net/browse/FOPTS-1123
[cloud_sql_idle_instance_recommendations](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64909fbe99c555000141b076)
[idle_ip_address_recommendations](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64909c0a44e32e000102c6e5) …
=> FOPTS-1123 Add the required fields to 3 Google policies

cost/aws/rightsize_compute_instances/CHANGELOG.md, cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt
Fixes the object type for the Tags output
https://app.flexera.com/orgs/34608/automation/incidents/projects/136331?incidentId=64936925ac3de30001d10d14
and
https://app.flexera.com/orgs/34608/automation/incidents/projects/136331?incidentId=64936926ac3de30001d10d15
See the Tags output
=> Fix: AWS Rightsize Compute Instances Pt Tags output

cost/oracle/oracle_cbi/CHANGELOG.md, cost/oracle/oracle_cbi/oracle_cbi.pt
Fixes an issue where, if OCI actually removes files between runs of the policy, the policy would never commit the bill upload because the number of files uploaded would be greater than, rather than equal to, the number of files in the bucket for that month.
The policy now commits the upload if the number of files is greater than or equal to instead. Extremely simple fix.
=> Oracle Bill Upload Fix

data/azure/azure_vm_pricing.py
It was discovered that certain prices were wrong due to the inclusion of specialized pricing (such as spot pricing). This has been fixed; now every instance should be listed with its standard on-demand price.
In addition, a new field has been added containing the AHUB price. This was determined by looking at the DevTestConsumption price, which MS has confirmed is the same as AHUB pricing in the below URL. pricePerUnitAHUB is set to null for instance types that do not qualify for AHUB.
The script has also been updated to include the above changes.
https://learn.microsoft.com/en-us/answers/questions/1178829/can-i-consider-devtestconsumption-price-from-retai
=> Azure Price File Fix and AHUB Update

cost/cloud_cost_anomaly_alerts/CHANGELOG.md, cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Previously this template showed errors when `Billing Centers` was used as a value for the parameter `Cost Anomaly Dimensions`, now users can use that value.
Here are some screenshots of the previous behavior:
https://flexera.atlassian.net/browse/FOPTS-911
- Policy applied with `Cost Anomaly Dimensions` set to `Billing Centers=Unallocated`:
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=649dd60d48e0bd00019a35ae
=> FOPTS-911 Cost Anomaly Alerts Billing Center as Dimension

cost/google/cud_recommendations/CHANGELOG.md, cost/google/cud_recommendations/google_committed_use_discount_recommendations.pt, cost/google/idle_ip_address_recommendations/CHANGELOG.md, cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt, cost/google/idle_persistent_disk_recommendations/CHANGELOG.md, cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt, cost/google/recommender/CHANGELOG.md, cost/google/recommender/recommender.pt, cost/google/rightsize_vm_recommendations/CHANGELOG.md, cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt
This change homologates the number of requests done to GCP recommender API before waiting in order to prevent API quota limit errors.
Now the next three GCP recommender policies make 100 request to recommender API before waiting.
- Google Idle IP Address Recommender
- Google Idle Persistent Disk Recommender
- Google Idle VM Recommender
Request number was determined using the documentation: https://cloud.google.com/recommender/quotas
- [FOPTS-681 Google Recommender policies - optimize recommender API throttling](https://flexera.atlassian.net/browse/FOPTS-681)
- [Google Idle IP Address Recommender](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64a4958a4cfc2d000111c929)
- [Google Idle Persistent Disk …
=> FOPTS-681 Homologate the requests to GCP recommender API before waiting to prevent API limit quota errors

cost/low_account_usage/CHANGELOG.md, cost/low_account_usage/low_account_usage.pt
Enhancement request to make Billing Centers parameter optional for Low Account Usage Policy
Made the billing center parameter optional and reflected the UI Changes with Mock Data.
- Low Account Usage Policy (Mock Data): https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64a854701268830001676b4f
- Low Account Usage Policy: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64a853d91268830001676b4e
=> FOPTS-765 Low-usage Account Policy

.github/workflows/generate-meta-parent-policy-templates.yaml, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
On GitHub Actions the path to policy template included multiple matches for `policy_templates/` -- i.e. `/.../policy_templates/policy_templates/.../`.  This was causing the script to fail because it was using `split("policy_templates/")[1]` -- which is not correct.
This change uses regex to find and replace everything from the start of the fully expanded path, up to the last `policy_templates/` -- which should work better.
=> fix: Meta Parent Parser GitHub README URLs

cost/turbonomics/credential_refresh/CHANGELOG.md, cost/turbonomics/credential_refresh/README.md, cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
Refreshing a cookie causes Turbonomic applied policies to restart, so in case the refresh policy runs more often than the turbonomic policy, we get unnecessary runs. In this PR we try to minimize the number of refreshes based on the frequency of policy runs (the refresh policy will decide if update is needed based on its frequency and next scheduled run of the policy to update).
https://flexera.atlassian.net/browse/FOPTS-1072
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64a238374466b10001e23975
=> FOPTS-1072 - Turbonomic policies with token refreshed follow schedule

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/README.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
This adds support for memory metrics and brings over a bunch of the improvements being made for the AWS version of this policy to the Azure version.
Azure now supports memory usage ("Available Memory Bytes") via the Insights API, so this data is straightforwardly pulled from the same API that CPU data is pulled from. The percentage is calculated by finding the total memory of the instance's SKU via the Microsoft.Compute/skus API and then doing the appropriate calculations.
- Removed deprecated "Log to CM Audit Entries" parameter
- Added ability to only report recommendations that meet a minimum savings threshold
- Added support for memory metrics along with relevant parameters
- Added ability to …
=> POL-878: Azure Rightsize Compute Instances Memory Support and General Improvements

cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md, cost/google/cloud_sql_idle_instance_recommendations/README.md, cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt, cost/google/idle_ip_address_recommendations/CHANGELOG.md, cost/google/idle_ip_address_recommendations/README.md, cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations.pt, cost/google/idle_persistent_disk_recommendations/CHANGELOG.md, cost/google/idle_persistent_disk_recommendations/README.md, cost/google/idle_persistent_disk_recommendations/google_idle_persistent_disk_recommendations.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/README.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt
This change adds documentation about how the recommender API works to the GCP recommender policies:
- Google Cloud SQL Idle Instance Recommender
- Google Idle IP Address Recommender
- Google Idle Persistent Disk Recommender
- Google Idle VM Recommender
https://flexera.atlassian.net/browse/FOPTS-682
This change only updates the documentation of the policies.
=> FOPTS-682 Google recommender policies update readme

cost/google/cloud_sql_idle_instance_recommendations/CHANGELOG.md, cost/google/cloud_sql_idle_instance_recommendations/google_sql_idle_instance_recommendations.pt
The method used to match recommendations with SQL instances was copied from other recommender policies, this was making this policy not show any recommendation.
- https://flexera.atlassian.net/browse/FOPTS-1441
- https://flexera.atlassian.net/browse/SQ-3178
Currently I don't have any account where I could test this, but I tested with the following code:
https://flexera.atlassian.net/browse/FOPTS-1441?focusedCommentId=2133467
=> FOPTS-1441 Google Cloud SQL Idle Instance Recommender: fix the method to match the recommendations with the SQL instances at the 

cost/turbonomics/delete_unattached_volumes/aws/CHANGELOG.md, cost/turbonomics/delete_unattached_volumes/aws/turbonomics_delete_virtual_volumes.pt, cost/turbonomics/delete_unattached_volumes/azure/CHANGELOG.md, cost/turbonomics/delete_unattached_volumes/azure/turbonomics_delete_virtual_volumes.pt
Azure Unattached Volumes policy needs to show the following information: storage access IOPs, storage amount, last VM volumes was attached to, action nature: disruptive or not, reversible or not, system details URL.
- Azure delete unattached volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64bec383cd41360001891b08
- AWS delete unattached volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64bfff2285ab670001ff6c0f
=> FOPTS-1324 Turbonomic Unattached Volumes (Azure)

cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt, cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt, cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt, cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt, cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt, cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management_meta_parent.pt, cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt, cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt, cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt, operational/azure/azure_certificates/azure_certificates_meta_parent.pt, operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt, operational/azure/tag_cardinality/azure_tag_cardinality_meta_parent.pt, operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks_meta_parent.pt, tools/meta_parent_policy_compiler/azure_meta_parent.pt.template
This updates the Azure meta policy template (and meta parent policies) to have the dimension filtering that the AWS meta policies have. This is to facilitate use cases where the user may want to filter on a dimension other than Azure subscription name or ID and to keep functionality as similar as possible between AWS and Azure meta policies.
Since these changes require actual functional Azure billing data in the org to enable the policy to work correctly, I do not have an example policy. That said, I did test these changes in a client org that is hoping to benefit from these changes and they worked as expected.
=> Azure Meta Policies: Dimension Filtering

cost/turbonomics/delete_unattached_volumes/gcp/CHANGELOG.md, cost/turbonomics/delete_unattached_volumes/gcp/turbonomics_delete_virtual_volumes.pt
GCP Unattached Volumes policy needs to show the following information: storage access IOPs, storage amount, last VM volumes was attached to, action nature: disruptive or not, reversible or not, system details URL.
- GCP delete unattached volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64c31164cd41360001891b57
=> FOPTS-1325 Turbonomic Unattached Volumes (GCP) 

cost/google/cloud_sql_idle_instance_recommendations/README.md, cost/google/cud_recommendations/README.md, cost/google/idle_ip_address_recommendations/README.md, cost/google/idle_persistent_disk_recommendations/README.md, cost/google/idle_vm_recommendations/README.md
This updates the README files for several of our cost policies for GCP to more accurately reflect the permissions needed.
No changes are made to the policies themselves, so no testing or version changes are needed.
=> POL-861 Google Cost Policy README Permissions Updates

cost/azure/reserved_instances/utilization_mca/CHANGELOG.md, cost/azure/reserved_instances/utilization_mca/README.md, cost/azure/reserved_instances/utilization_mca/azure_reserved_instance_utilization_mca.pt
The Azure RI Utilization policy currently only supports Azure EA.  We should create a new version modeled after the Azure EA policy that supports the Azure MCA API.  
EA version: https://github.com/flexera-public/policy_templates/tree/master/cost/azure/reserved_instances/utilization
More details: [here](https://flexera.atlassian.net/browse/FOPTS-172).
Add support for MCA accounts to get a list of reserved instances with an utilization below a value using a full new policy template.
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/104308?policyId=64ca8480cd41360001891bed
=> FOPTS-172 Add: Azure MCA RI Utilization PT

cost/turbonomics/rightsize_databases_recommendations/aws/CHANGELOG.md, cost/turbonomics/rightsize_databases_recommendations/aws/turbonomics_rightsize_databases_recommendations.pt
AWS Rightsize DBs policy needs to show the following information: VM age, uptime, vCPU capacity before/after, vCPU utilization before/after, Memory capacity before/after, memory utilization before/after, IOPs capacity and utilization before/after, disk capacity and utilization before/after, connection capacity and utilization before/after, system details URL.
https://flexera.atlassian.net/browse/FOPTS-1333
[Applied policy ](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64cc3a95cd41360001891c1f)
=> FOPTS-1333 Turbonomic Rightsize DBs (AWS) - Bring recommendation supporting information

cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/CHANGELOG.md, cost/turbonomics/rightsize_virtual_volumes_recommendations/aws/turbonomics_rightsize_virtual_volumes_recommendations.pt
AWS Rightsize Volumes policy needs to show the following information: current and new storage access IOPs, current and new storage amount, VM volume is attached to, action nature: disruptive or not, reversible or not, current and new throughput capacity, IOPs utilization, disk utilization, throughput utilization, system details URL.
- AWS Turbonomic Rightsize Volumes: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64d16397cd41360001891c7f
=> FOPTS-1327 Turbonomic Rightsize Volumes (AWS)

automation/aws/aws_rbd_from_tag/CHANGELOG.md, automation/aws/aws_rbd_from_tag/README.md, automation/aws/aws_rbd_from_tag/aws_rbd_from_tag.pt
This is a modification of the AWS RBD from Tags policy to use the new API for getting AWS accounts and their tags. This eliminates the need for an AWS credential at all, and also eliminates any concerns around a credential not having access to all of the accounts.
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64d288ce126883000167b558
=> POL-899 Use New API for AWS RBD Policy

cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/CHANGELOG.md, cost/turbonomics/rightsize_virtual_volumes_recommendations/gcp/turbonomics_rightsize_virtual_volumes_recommendations.pt
GCP Rightsize Volumes is not supported on Turbonomic yet.
Unpublished policy from catalog since Turbonomic Rightsize Volumes does not support Google provider yet.
N/A
=> FOPTS-1329 Turbonomic Rightsize Volumes (GCP)

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt, cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt, cost/azure/old_snapshots/CHANGELOG.md, cost/azure/old_snapshots/azure_delete_old_snapshots.pt, cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt, cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt, cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt, cost/azure/unused_ip_addresses/CHANGELOG.md, cost/azure/unused_ip_addresses/azure_unused_ip_addresses.pt, cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt, cost/azure/unused_sql_databases/CHANGELOG.md, cost/azure/unused_sql_databases/azure_unused_sql_databases.pt, cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt, cost/azure/unused_volumes/CHANGELOG.md, cost/azure/unused_volumes/azure_unused_volumes.pt, cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
The casing and naming conventions of some dimensions, such as the Service field, are different between the old method of ingesting Azure bills and the new method. For example, “Microsoft.Compute” is now “microsoft.compute”. This update enables our cost optimization policies to pull this data regardless of casing.
https://flexera.atlassian.net/browse/POL-903
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=64e35fc94b956f0001f2864f
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=64e3694f2d830e000134c702
(Note: Since this is a test environment, the savings in the incident will be $0. This is just to demonstrate that the updated Optima API call itself works and does not result in any errors. I have also confirmed that this …
=> POL-903 Fixed Cost Data Issue with New Azure APIs

.github/workflows/test-policies.yaml
Fixes issue seen here related to fpt binary not being available.  Given the rightscale.com URL, I suspect this is a deprecation and so this proposed fix replaces that step with steps that build fpt binary from source and put it in the same location toplevel of the repo
https://github.com/flexera-public/policy_templates/actions/runs/5942493295/job/16115579747#step:3:8
=> fix: fpt install from source

cost/kubecost/sizing/CHANGELOG.md, cost/kubecost/sizing/README.md, cost/kubecost/sizing/kubecost_resizing_recommendation.pt
As a user I want to be able to configure Kubecost Request Rightsizing Recommendations policy to request recommendations per-cluster or overall, so that I can insure that the responses do not violate limits set up in my environment.
If per cluster mode is configured, policy will discover clusters, iterate the clusters and request recommendations for each one.
- https://flexera.atlassian.net/browse/FOPTS-1578
Per cluster: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64dbaaf453379b0001babd96
Overall: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=64dbab4453379b0001babd97
=> FOPTS-1578 Allow Retrieving Recommendations "per cluster"

.github/workflows/upload-files.yaml, tools/policy_sync/CHANGELOG.md, tools/policy_sync/policy_sync.pt
I updated the repository to use Github instead of S3 to publish the policy templates.
- https://flexera.atlassian.net/browse/POL-905
N/A
=> POL-905 Update policy_sync.pt to use Github instead of S3

.github/workflows/upload-files.yaml
I updated the repository to use Github instead of S3 to publish the policy templates. I fixed the name of the active policy list file.
- https://flexera.atlassian.net/browse/POL-905
N/A
=> POL-905 Fix the name of the active policy list file

.github/workflows/upload-files.yaml
I updated the repository to use Github instead of S3 to publish the policy templates. I fixed permissions of the Github workflow.
- https://flexera.atlassian.net/browse/POL-905
N/A
=> POL-905 Fix permissions of the GitHub workflow

cost/aws/old_snapshots/aws_delete_old_snapshots.pt
This is a simple fix to bump the version number for the AWS Old Snapshots policy. A fix was recently merged but the version number in the policy was not changed. It is now bumped to 7.2 to match the CHANGELOG.
=> Fix AWS Old Snapshots Version #

operational/itam/schedule_itam_report/CHANGELOG.md, operational/itam/schedule_itam_report/schedule-itam-report.pt
The link of the README for Schedule ITAM Report policy was fixed and now it redirects to the actual README page.
- https://flexera.atlassian.net/browse/FOPTS-1632
No changes were done to policy code, only the version number and description were updated, here's a proof that the policy still compiles:
- https://app.flexeratest.com/orgs/1105/automation/projects/107982/policy-templates/64e79d7032d8b40001fa4ef9
=> FOPTS-1632 Fix the broken link for the README for Schedule ITAM Report policy

cost/turbonomics/scale_virtual_machines_recommendations/aws/CHANGELOG.md, cost/turbonomics/scale_virtual_machines_recommendations/aws/turbonomics_scale_virtual_machines.pt
AWS Rightsize VMs policy needs to show the following information: RI coverage before/after, VM age, uptime, vCPU capacity before/after, vCPU utilization before/after, Memory capacity before/after, memory utilization before/after, storage throughput capacity before/after, storage throughput utilization before/after, NET throughput capacity and utilization before/after, system details URL.
- AWS Turbonomic Rightsize VMs: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64ee5c5c01dad60001bfe6e7
=> FOPTS-1330 Turbonomic Rightsize VMs (AWS)

cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt
Was added a step to parse the tags received using the Azure API to an array of tags
GUI was unable to parse a map of tags, so now the policy sends an array of tags with format ["key=value"]
[Applied Policy](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64f13e7a4b956f0001f2b4f9)
=> FOPTS-1542 Azure Idle Compute Instances - incident and recommendations showing error for tags

.github/workflows/generate-readme-policy-table-of-contents.yaml, tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Current workflow will error if a Changelog note contains double quotes (" ") due to how the Teams API payload is constructed. This change adds substitution logic to handle Changelog notes that contain double quotes.
Resolves the issue of the Teams API call failing due to the JSON payload structure being incorrect when a Changelog note contains double quotes.
N/A
=> POL-847 Policy Automated Updates On Releases 2

cost/turbonomics/scale_virtual_machines_recommendations/gcp/CHANGELOG.md, cost/turbonomics/scale_virtual_machines_recommendations/gcp/turbonomics_scale_virtual_machines.pt
GCP Rightsize VMs policy needs to show the following information: RI coverage before/after, VM age, uptime, vCPU capacity before/after, vCPU utilization before/after, Memory capacity before/after, memory utilization before/after, storage throughput capacity before/after, storage throughput utilization before/after, NET throughput capacity and utilization before/after, system details URL.
GCP Turbonomic Rightsize VMs: https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=64ef88ee01dad60001bfe702
=> FOPTS-1332 Turbonomic Rightsize VMs (GCP) 

.github/workflows/generate-policy-release-notifications.yaml, .github/workflows/generate-readme-policy-table-of-contents.yaml, tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Enhanced the GitHub Actions Workflow so that the Teams Notification now has the following:
- A hyperlink for each Policy Template Heading that takes the user to the Policy Template's README file.
- A hyperlink for a 'See full diff' action, which takes the user to the Commit details in GitHub, to view the full diff.
N/A
N/A
=> POL 847 Policy Automated Updates on Releases 2

cost/turbonomics/credential_refresh/CHANGELOG.md, cost/turbonomics/credential_refresh/turbonomic_cred_refresh.pt
- Bug fix: Previously this policy could only update applied policies (policies added using the Automation > Templates panel) but no aggregated policies like those executed from the Automation > Catalog, now this was fixed and the policy can work with both.
- https://flexera.atlassian.net/browse/FOPTS-1816
- Applied policy: https://app.flexera.com/orgs/33749/automation/applied-policies/projects/135147?policyId=65038359656c530001e16708
=> FOPTS-1816 Handle updating applied and aggregated policies

cost/azure/rightsize_sql_instances/CHANGELOG.md, cost/azure/rightsize_sql_instances/README.md, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
This is a revamp of the Azure Rightsize SQL Databases policy as part of the general audit on usage and rate reduction policies. In order to have parity with the Azure Rightsize Compute policy, and to avoid duplicate recommendations, this policy now reports on both unused and underutilized SQL databases via distinct incidents. A parameter allows the user, if desired, to report on only unused or only underutilized instances, retaining existing functionality.
The policy now also offers savings estimates for rightsizing opportunities. For underutilized resources, the cost of the instance is divided by the current capacity of the instance and then multiplied by the recommended capacity of the instance to determine the new cost if the instance were downsized. This is then subtracted from the …
=> POL-840 Azure Rightsize SQL Databases Revamp 

cost/azure/hybrid_use_benefit_linux/CHANGELOG.md, cost/azure/hybrid_use_benefit_linux/ahub_linux.pt, cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
Fixes erroneous README link in the metadata for the Azure AHUB Linux policy.
=> Azure AHUB Linux README Link Fix

operational/aws/long_running_instances/CHANGELOG.md, operational/aws/long_running_instances/README.md, operational/aws/long_running_instances/long_running_instances.pt, operational/aws/long_running_instances/long_running_instances_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a revamp of the AWS Long Running Instances policy that adds new functionality and meta policy support. From the CHANGELOG:
- Removed deprecated "Log to CM Audit Entries" parameter
- Added several fields to incident export to provide additional context
- Policy no longer raises new escalations for the same resource if incidental metadata has changed
- Added logic required for "Meta Policy" use-cases
- Policy now requires a valid Flexera credential to facilitate "Meta …
=> POL-911 AWS Long Running Instances Revamp

cost/aws/rightsize_ebs_volumes/CHANGELOG.md, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
- Reintroduced logic to filter out gp3 volumes from recommendations
- Changed data for policy incident to ensure a policy incident is not created when there are no recommendations
- Fixes issue with policy where $0 recommendations are returned for gp3 volumes, which are currently not supported for recommendations.
- Fixes issue with policy where some child policies have a single recommendation, and that recommendation is completely empty. This was caused by the 'message' field in the data, which is passed even if there are no recommendations.
SE NAM Architects Sandbox - https://app.flexera.com/orgs/32567/automation/applied-policies/projects/133743?policyId=650c09516a972a0001e51044 (example of policy returning 1 GP2 volume recommendation and filtering out GP3 volumes)
SE Sandbox EU - …
=> POL-910 AWS Rightsize EBS Volumes - Remove GP3 Recommendations and Empty Recommendations

operational/azure/azure_long_running_instances/CHANGELOG.md, operational/azure/azure_long_running_instances/README.md, operational/azure/azure_long_running_instances/azure_long_running_instances.pt, operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
This is a revamp of the Azure Long Running Instances policy that adds new functionality and meta policy support. From the CHANGELOG:
- Added several fields to incident export to provide additional context
- Policy no longer raises new escalations for the same resource if incidental metadata has changed
- Policy now requires a valid Flexera credential
- Added logic required for "Meta Policy" use-cases
The new functionality depends too much on valid Optima data to be easily …
=> POL-919 Azure Long Running Instances Revamp

cost/azure/unused_volumes/CHANGELOG.md, cost/azure/unused_volumes/README.md, cost/azure/unused_volumes/azure_unused_volumes.pt, cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt
The Azure Unused Volumes policy has been updated to consider read/write metrics when determining if a volume is unused, similar to the AWS version of the policy. The user can configure how far back to look at these metrics and whether or not to report on attached volumes in the resulting incident. Please see the README for more details.
New functionality has been thoroughly tested, including the Cloud Workflow to detach a volume from an attached instance before deleting it.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65099dd36a972a0001e50c56
=> POL-920 Azure Unused Volumes Read/Write Metrics Support

cost/oracle/oracle_cbi/CHANGELOG.md, cost/oracle/oracle_cbi/oracle_cbi.pt
If a file upload were to fail for some reason, such as the policy engine running out of memory or a network issue, that individual file would remain in an "in-progress" status indefinitely. This would result in the policy never being able to successfully commit the bill upload as a whole, resulting in the policy stalling out.
This is a fix for the issue. If such a broken file upload is found, the policy will simply abort the bill upload and create a new one, starting the entire process over.
This policy has been tested in a client environment that was experiencing the issue this update fixes and has been confirmed to work as expected.
=> POL-924 Oracle Cloud CBI Broken Upload Fix

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/README.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
This non-breaking update adds the ability to filter by region, similar to other Azure usage reduction policies. 
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=6509ac05656c530001e1762e
(Parameter is set to only allow instances in the eastus region, and this is reflected in the incident)
=> POL-921 Add Region Filtering to Azure Rightsizing Compute

cost/aws/superseded_instances/CHANGELOG.md, cost/aws/superseded_instances/README.md, cost/aws/superseded_instances/aws_superseded_instances.pt, cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a new AWS-specific version of the Superseded Instances policy. This policy requires an AWS credential with permissions similar to the AWS Rightsizing EC2 Instances policy, but offers several advantages over the cloud-agnostic version:
- Completely updated/rebuilt code based on the updated versions of other usage reduction policies with similar functionality where appropriate
- Since instance metadata is mostly pulled from AWS itself, any instances that are actioned should no longer appear in future incidents since their instance type will no longer be superseded and the policy is gathering this metadata in near real time from the AWS API directly
- Savings information is included based on AWS list prices for instance types with currency conversion (similar to AWS Unused IP policy) …
=> POL-922 AWS Superseded EC2 Instances

cost/azure/superseded_instances/CHANGELOG.md, cost/azure/superseded_instances/README.md, cost/azure/superseded_instances/azure_superseded_instances.pt, cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a new Azure-specific version of the Superseded Instances policy. This policy requires an Azure credential with permissions similar to the Azure Rightsizing Compute Instances policy, but offers several advantages over the cloud-agnostic version:
- Completely updated/rebuilt code based on the updated versions of other usage reduction policies with similar functionality where appropriate
- Since instance metadata is mostly pulled from Azure itself, any instances that are actioned should no longer appear in future incidents since their instance type will no longer be superseded and the policy is gathering this metadata in near real time from the Azure API directly
- Savings information is included based on Azure list prices for instance types with currency conversion (similar to AWS …
=> POL-923 Azure Superseded Compute Instances

cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
Azure Savings Realized policy is failing for customer with no RI coverage.
The failure happens on attempt to access an element of an empty array 
https://flexera.atlassian.net/browse/FOPTS-1858
Applied policy with report length 0
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=651482604e39ab00016cbf71
=> FOPTS-1858 Azure Savings Realized fails for customers with no RI coverage

cost/aws/rightsize_ebs_volumes/CHANGELOG.md, cost/aws/rightsize_ebs_volumes/README.md, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
This is a revamp of the AWS Rightsize EBS Volumes policy that adds new functionality and meta policy support. The most notable changes are:
- The API calls to CloudWatch, and subsequent calculations for IOPS percentage, were removed because they had no bearing on the recommendations produced and simply added unnecessary permissions requirements for the user.
- The ability to action on resources directly from the incident has been added. This functionality has been successfully tested.
- Added ability to only report recommendations that meet a minimum savings threshold
- Added ability to take automated actions to upgrade GP2 volumes …
=> POL-830 AWS Rightsize EBS Volumes Revamp

cost/superseded_instance/CHANGELOG.md, cost/superseded_instance/README.md, cost/superseded_instance/superseded_instance.pt
This policy only supports AWS and Azure, which both now have cloud-specific versions of this policy with much more functionality. This PR deprecates the old cloud-neutral version of the policy and directs users to the new policies in the associated README.
=> POL-926 Deprecate Superseded Instances Policy

cost/aws/savings_realized/CHANGELOG.md, cost/aws/savings_realized/aws_savings_realized.pt
The following dimensions were added to the average cost per hour calculation:
- operating_system
- database_engine
- database_edition
- license_model
- deployment_option
In addition, the way of obtaining the costs per hour for each type of instance was changed. Previously, all possible combinations of instances were obtained, obtaining a cost for each combination of instance_type and region (for example, if we have 100 different instances_type and 15 regions, we would obtain 1500 average costs, even though many were not necessary according to the records obtained from the API). By adding the 5 new dimensions, this approach becomes impractical, since it would increase exponentially for each combination of operating system, database engine, database edition, etc.
So it was decided to use a …
=> FOPTS-1503 Added new cost dimensions for savings calculations

cost/azure/azure_china_cbi/CHANGELOG.md, cost/azure/azure_china_cbi/README.md, cost/azure/azure_china_cbi/azure_china_cbi.pt
This is a change request for adding a parameter that gives the user the ability to specify a specific month to pull billing data for,. This is useful in the interest of retrieving historical data (i.e., billing data that is not the current month)
- Removed the `permission` declaration as it is deprecated. This fixes the issue which breaks the current policy if it is applied in a tenant from the Catalog.
~Testing this in a customer tenant, will update when confirmed as working~ Can confirm this policy is working as expected in customer tenant
=> POL-927 Azure China CBI - Add ability to choose specific billing month

cost/google/idle_ip_address_recommendations/google_idle_ip_address_recommendations_meta_parent.pt, cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt, tools/meta_parent_policy_compiler/google_meta_parent.pt.template
This fixes an issue with Google meta parent policies due to the vendor name in the Optima API being "GCP" instead of "Google"
=> Google Meta Policy Parent Fix

compliance/azure/instances_without_fnm_agent/azure_instances_not_running_flexnet_inventory_agent_meta_parent.pt, cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit_meta_parent.pt, cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt, cost/azure/hybrid_use_benefit_sql/ahub_sql_meta_parent.pt, cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt, cost/azure/old_snapshots/azure_delete_old_snapshots_meta_parent.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt, cost/azure/storage_account_lifecycle_management/storage_account_lifecycle_management_meta_parent.pt, cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt, cost/azure/unused_ip_addresses/azure_unused_ip_addresses_meta_parent.pt, cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt, cost/azure/unused_volumes/azure_unused_volumes_meta_parent.pt, operational/azure/azure_certificates/azure_certificates_meta_parent.pt, operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt, operational/azure/tag_cardinality/azure_tag_cardinality_meta_parent.pt, operational/azure/vms_without_managed_disks/azure_vms_without_managed_disks_meta_parent.pt, tools/meta_parent_policy_compiler/azure_meta_parent.pt.template
Currently Azure Meta Parent policies will not include subscriptions under an Azure MCA due to the filter.  This updates the filter to use `substring` instead of `equal` for identifying Azure Subscriptions
=> fix: update filter to include Azure MCA

cost/azure/hybrid_use_benefit_linux/CHANGELOG.md, cost/azure/hybrid_use_benefit_linux/ahub_linux.pt, cost/azure/hybrid_use_benefit_linux/ahub_linux_meta_parent.pt
This update fixes a bug where policy fails if an instance lacks Image Publisher metadata. The policy now verified that imagePublisher is a string before attempting to invoke the string method toLowerCase() on it.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6520013a99745e0001587a3d
=> POL-937 Fix String bug in Azure AHUB Linux Policy

cost/aws/rightsize_ebs_volumes/CHANGELOG.md, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing_meta_parent.pt
The policy was revamped with the assumption that the AWS Price List API would report hourly pricing for EBS volumes, similar to how it reports EC2 pricing. It turns out that this API reports monthly pricing, which means the math to convert it from hourly pricing resulted in highly inflated values.
The above described issue.
Tested in POC environment where problem was first discovered.
=> POL-940 Fix Pricing Info in AWS Rightsize EBS Volumes

operational/azure/azure_long_running_instances/CHANGELOG.md, operational/azure/azure_long_running_instances/azure_long_running_instances.pt, operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
Customers would like to have operating system shown as an additional incident field.
The policy already have this information, we need to expose it in the incident.
[FOPTS-2261 Jira](https://flexera.atlassian.net/browse/FOPTS-2261)
[Azure Long Running Instances policy template Applied](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6526fc0155d35d0001a8213a)
=> FOPTS-2261 Azure Long Running Instances - add OS incident field

cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
The month field of this policy, despite just reporting a month, includes a full timestamp with date and time, like so: 
2023-06-01T00:00:00Z
This modification makes it so that the Month field in the incident just contains the month, like so:
2023-06
Verified working in client account.
=> POL-780 Azure Savings Realized Date Change

operational/azure/azure_long_running_instances/CHANGELOG.md, operational/azure/azure_long_running_instances/azure_long_running_instances.pt, operational/azure/azure_long_running_instances/azure_long_running_instances_meta_parent.pt
This policy incorrectly reports on stopped instances when it should only report running instances. This PR is to fix this issue. It also fixes a minor language error in the detailed template of the incident output.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6537cd34e947000001d934e5
=> POL-955 Azure Long Running Instances Fix

cost/low_account_usage/CHANGELOG.md, cost/low_account_usage/low_account_usage.pt
Customers want account ID to be provided in the incident details for Low Account Usage policy
[FOPTS-2328 Jira](https://flexera.atlassian.net/browse/FOPTS-2328)
[Low Account Usage - Policy template applied](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=65332b9755d35d0001a84227)
=> FOPTS-2328 Low Account Usage Policy: add account ID to incident details

cost/aws/rightsize_ec2_instances/CHANGELOG.md, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt
This fixes several issues with how CloudWatch data is pulled that would occasionally cause incorrect results. Specifically, the date range we pull data for is now rounded down to the nearest hour. This is to ensure that the range is neatly sliced by the period we specify so that we only get one result back from CloudWatch for each metric.
Previously, it would sometimes imperfectly slice the data, giving us two results, the first being for less than an hour of time and the second being the number we actually needed, but when this happened, the policy grabbed the first number instead. As a backup, just in case somehow the above doesn't work, the policy now grabs the last item in the list of values instead of just grabbing [0] every time.
Additionally, I spotted a couple of issues where the …
=> POL-957 AWS Rightsize EC2 CloudWatch Fix

cost/aws/idle_compute_instances/CHANGELOG.md, cost/aws/idle_compute_instances/README.md, cost/aws/idle_compute_instances/idle_compute_instances.pt, cost/aws/idle_compute_instances/idle_compute_instances_meta_parent.pt, cost/azure/idle_compute_instances/CHANGELOG.md, cost/azure/idle_compute_instances/README.md, cost/azure/idle_compute_instances/azure_idle_compute_instances.pt, cost/azure/idle_compute_instances/azure_idle_compute_instances_meta_parent.pt, cost/azure/unused_sql_databases/CHANGELOG.md, cost/azure/unused_sql_databases/README.md, cost/azure/unused_sql_databases/azure_unused_sql_databases.pt, cost/azure/unused_sql_databases/azure_unused_sql_databases_meta_parent.pt, cost/google/idle_vm_recommendations/CHANGELOG.md, cost/google/idle_vm_recommendations/README.md, cost/google/idle_vm_recommendations/google_vm_recommendations.pt
The following policies should be flagged as deprecated, as their functionality is now included in other policies:
AWS Idle Compute Instances (functionality is now part of AWS Rightsize EC2 Instances)
Azure Idle Compute Instances (functionality is now part of Azure Rightsize Compute Instances)
Azure Unused SQL Databases (functionality is now part of Azure Rightsize SQL Databases)
Google Idle VM Recommender (functionality is now part of Google Rightsize VM Recommender)
This change does *not* remove the policies from the catalog or impact the functionality of existing meta policies that customers may be using. It simply directs users to the more updated and correct policies when browsing the catalog.
N/A. These changes don't impact policy execution.
=> POL-959 Deprecate Idle Usage Reduction Policies

cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
This policy did not work correctly for clients using the new Azure EA bill connect method. This corrects that issue. The policy now obtains a list of bill connections from Optima and tailors the requests to the Optima API based on which bill connections exist. The policy should now work with both old and new connections and collect costs from both if both are present.
I've done a pretty thorough investigation/testing of this in a client account, and I am confident that we are now pulling the correct data.
It's likely that this policy will be changed to use the savings value in Optima once that feature is available for Azure, but this PR will ensure the policy at least continues to work as expected for users using the new EA bill connections in the meantime. …
=> POL-944 Fix Azure Savings Realized for new Azure EA Connections

README_GUIDELINE.md, cost/aws/object_storage_optimization/README.md, cost/aws/s3_bucket_size/README.md
A small number of policy READMEs use invalid version numbers in their JSON examples for AWS permission policies. This updates them to instead use 2012-10-17, which is the latest valid version number.
N/A. This is just a documentation update.
=> POL-907 Fix AWS Permission Version in READMEs

cost/aws/reserved_instances/utilization/CHANGELOG.md, cost/aws/reserved_instances/utilization/README.md, cost/aws/reserved_instances/utilization/utilization_ris.pt
Adds functionality to the policy so that a user can filter current reservation purchases by Billing Center. 
As we cannot currently support RBAC on reserved instances within the platform, this will allow for owners of Billing Centers to only receive the list of reservations (and their respective utilizations) that are applicable to their BCs, and not see all reservations at a global level.
If the user does not specify a specific list of billing centers, the policy operates in the same way it did prior to this change.
- Fixes README title to reflect policy template name.
- Fixes README "Credential Configuration" section to reflect the credentials required to run the policy.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6545048599745e0001587f6b
=> POL-960 Update AWS Reserved Instances Utilization - add ability to filter by Billing Center

cost/aws/gp3_volume_upgrade/CHANGELOG.md, cost/aws/gp3_volume_upgrade/README.md, cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume.pt, cost/aws/gp3_volume_upgrade/aws_upgrade_to_gp3_volume_meta_parent.pt
This policy is no longer being updated. The [AWS Rightsize EBS Volumes](https://github.com/flexera-public/policy_templates/tree/master/cost/aws/rightsize_ebs_volumes/) policy should be used for these recommendations instead.
Note that, unlike the AWS Rightsize EBS Volumes policy, this policy reports on IO1 and IO2 volumes. These volumes are high performance volumes, so changing them to GP3 will result in a performance downgrade and may cause issues for workloads that rely on this performance.
Effectively, this policy was just recommending the above change without regard for actual usage data, which is a bit reckless and shouldn't be done. A future version of the AWS Rightsize EBS Volumes policy may include this functionality, but it would be alongside actual analysis of metrics to …
=> POL-967 Deprecate AWS GP3 Upgradeable Volumes Policy

cost/azure/rightsize_sql_instances/CHANGELOG.md, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
If the list of databases returned by the Azure API included entries without a valid 'sku' field, the policy would error out instead of completing. This is a fix for that; such entries are now filtered entirely, since it wouldn't be possible to provide meaningful recommendations without knowing the SKU anyway.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=654d2e7e99745e0001588027
Note: The above does not raise an incident and is just to confirm the policy completes. I have also tested this in the user environment where the issue was originally reported and verified the fix does work as intended.
=> POL-966 Azure Rightsize SQL Fix

cost/aws/object_storage_optimization/CHANGELOG.md, cost/aws/object_storage_optimization/README.md, cost/aws/object_storage_optimization/aws_object_storage_optimization.pt, cost/aws/object_storage_optimization/aws_object_storage_optimization_meta_parent.pt
Modify temporally a bucket list to prevent timeout from large buckets, and revert that changes once successfully results
Additionally, if user did specify exclude tags, retrieve tags only for objects we will be raising incident for, instead of making calls for all discovered objects
[FOPTS-2380](https://flexera.atlassian.net/browse/FOPTS-2380)
[Applied policy with all buckets](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=654b49063411070001af400a)
=> FOPTS-2380 Modify S3 Object Policy template to prevent tag calls if user don't input tags

saas/fsm/unsanctioned_apps_with_contract/CHANGELOG.md, saas/fsm/unsanctioned_apps_with_contract/README.md, saas/fsm/unsanctioned_apps_with_contract/fsm-unsanctioned_with_contract.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use the correct API endpoints for APAC. The policy itself has also been revamped along similar lines to other policies.
Note: This policy still uses the now-deprecated internal SaaS Manager API. This is because the new API does not yet support the requests this policy needs to make to function. This functionality will be brought to the new API before the old one is decommissioned, and this policy will need to be updated again at that time.
- `Currency` is now a separate incident field …
=> POL-745 SaaS Manager - Unsanctioned Applications with Existing Contract Revamp

saas/fsm/suspicious_users/CHANGELOG.md, saas/fsm/suspicious_users/README.md, saas/fsm/suspicious_users/fsm-suspicious_users.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use the correct API endpoints for APAC. The policy itself has also been revamped along similar lines to other policies.
Note: This policy still uses the now-deprecated internal SaaS Manager API. This is because the new API does not yet support the requests this policy needs to make to function. This functionality will be brought to the new API before the old one is decommissioned, and this policy will need to be updated again at that time.
https://app.flexera.com/orgs/27018/automation/applied-policie …
=> POL-745 SaaS Manager - Suspicious Users Revamp

saas/fsm/renewal_reminder/CHANGELOG.md, saas/fsm/renewal_reminder/README.md, saas/fsm/renewal_reminder/fsm-renewal_reminder.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use up to date APIs. The policy itself has also been revamped along similar lines to other policies.
- Updated policy to use public SaaS Manager API
- Added `Applications` parameter to allow user to filter results by application
- Incident now includes additional fields to provide more context
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=65526b4a99745e0001588087
=> POL-745 SaaS Manager - Renewal Reminder Revamp

saas/fsm/redundant_apps/CHANGELOG.md, saas/fsm/redundant_apps/README.md, saas/fsm/redundant_apps/fsm-redundant_apps.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use up to date APIs. The policy itself has also been revamped along similar lines to other policies.
- Updated policy to use public SaaS Manager API
- Incident now includes additional fields to provide more context
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=65522cc899745e0001588079
=> POL-745 SaaS Manager - Redundant Apps Revamp

saas/fsm/duplicate_users/CHANGELOG.md, saas/fsm/duplicate_users/README.md, saas/fsm/duplicate_users/duplicate_users.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use up to date APIs. The policy itself has also been revamped along similar lines to other policies.
- Updated policy to use public SaaS Manager API
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=654b8824e947000001d93727
=> POL-745 SaaS Manager - Duplicate User Accounts Revamp

saas/fsm/unsanctioned_spend/CHANGELOG.md, saas/fsm/unsanctioned_spend/README.md, saas/fsm/unsanctioned_spend/fsm-unsanctioned_spend.pt
This is part of a broader initiative to update our SaaS Manager FSM policies to use the correct API endpoints for APAC. The policy itself has also been revamped along similar lines to other policies.
Note: This policy still uses the now-deprecated internal SaaS Manager API. This is because the new API does not yet support the requests this policy needs to make to function. This functionality will be brought to the new API before the old one is decommissioned, and this policy will need to be updated again at that time.
- `Expense Sum` and `Currency` are now separate incident fields
- General code cleanup and …
=> POL-745 SaaS Manager - Unsanctioned Spend Revamp

cost/aws/rightsize_ebs_volumes/CHANGELOG.md, cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt, cost/aws/unused_ip_addresses/CHANGELOG.md, cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt
Added parameter to override the AWS Pricing API Endpoint.
This will enable us to change the API endpoint being used by the Policy Template in case a customer is using an AWS Service Control Policy to deny `us-east-1` which we previously had hard-coded.
https://app.flexera.com/orgs/35917/automation/applied-policies/projects/137860?noIndex=1&policyId=655bbca055d35d0001a8c051
=> feat: add param for AWS Pricing API Endpoint

tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Fixes generate readme script by adding a step to convert any `nil` values from the parsed policy template into an empty string (`""`)
Fixes broken workflow.  Example: https://github.com/flexera-public/policy_templates/actions/runs/6950317788
=> fix: convert nil values to empty string ""

cost/aws/unused_rds/CHANGELOG.md, cost/aws/unused_rds/README.md, cost/aws/unused_rds/unused_rds.pt, cost/aws/unused_rds/unused_rds_meta_parent.pt
The AWS Unused RDS policy is being deprecated due to the Rightsize RDS policy now containing identical functionality. This is similar to what has been done with other similar policies.
N/A. Changes do not impact policy execution.
=> POL-974 Deprecate AWS Unused RDS Policy

cost/google/old_snapshots/CHANGELOG.md, cost/google/old_snapshots/README.md, cost/google/old_snapshots/google_delete_old_snapshots.pt, cost/google/old_snapshots/google_delete_old_snapshots_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a revamp of the Google Old Snapshots policy that also adds meta policy support for it.
Note: This policy does not report savings (identical to previous version) because we do not ingest GCP billing data at a granular enough level to obtain costs for specific resources. This policy should be updated if/when that changes.
- Removed deprecated "Log to CM Audit Entries" parameter
- Added ability to filter resources by project
- Added ability to use wildcards when filtering resources by label
- Added additional fields to …
=> POL-975 Google Old Snapshots Revamp / Meta Policy

cost/aws/rightsize_rds_instances/CHANGELOG.md, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
This just changes the default value of the `Underutilized Instance CPU Threshold (%)` parameter to 40% to match other policies and ensure that our recommendations won't cause performance issues.
=> POL-977 AWS Rightsize RDS: Change Parameter Default Value

security/storage/aws/public_buckets/CHANGELOG.md, security/storage/aws/public_buckets/README.md, security/storage/aws/public_buckets/aws_public_buckets.pt, security/storage/aws/public_buckets/aws_public_buckets_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a revamp of the AWS Open Buckets policy to clean up the code/functionality and to enable meta policy support.
- Added ability to filter resources by region
- Policy no longer raises new escalations if bucket owner has changed but nothing else has
- Policy now requires a valid Flexera credential
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6568f20399745e0001588354
=> POL-889 AWS Open S3 Buckets Revamp / Meta

cost/aws/old_snapshots/README.md, cost/aws/unused_volumes/README.md
aws_delete_unused_volumes.pt uses "pagination_aws_getmetricdata" and therefore needs the  "cloudwatch:GetMetricData" permission:
- Updated Readme as permission "cloudwatch:GetMetricData" was missing.
- [x ] New functionality includes testing. 
(After adding the permission the template started working)
=> Updated Readme as permission "cloudwatch:GetMetricData" was missing

data/azure/instance_types.json
Vestas Wind Systems noticed that Azure Superseded Compute Instances policy recommends to upgrade **Standard_E16as_v4** machine to **Standard_E16as_v5**. Customer disputes this recommendation as incorrect due to current SKU provides temporary storage whilst the recommended SKU doesn’t. 
The correct recommendation would be to upgrade to SKU **Standard_E16ads_v5** with temporary storage:
**Standard_E16as_v4** = 16 vCPUs, 128 GB RAM, **256 GB** Temporary storage
**Standard_E16as_v5** = 16 vCPUs, 128 GB RAM, **0 GB** Temporary storage
**Standard_E16ads_v5** = 16 vCPUs, 128 GB RAM, **600 GB** Temporary storage
Azure instance_type.json needs to be corrected as Eas v4 instances are marked as superseded  by Eas v5 instead of Eads v5
https://flexera.atlassian.net/browse/POL-969
NA
=> POL-969 - Update Azure instance_type.json file for Eas series

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/README.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
This is intended to fix a couple of issues with this policy, as well as implement some improvements made to other revamped policies to ensure this one is fully up to date. While this policy should continue to function without issue for most customers, a change to the `Automatic Actions` parameter does technically constitute a breaking change, hence the major version number change.
- Fixed issue with resource count in incident subject being off by 1
- Fixed minor grammar issue if results only include 1 item
- Renamed policy actions to make it clear whether they are for underutilized or idle instances
- Added ability to filter resources by tag key via wildcard
- Added option to power off idle instances
- Added ability to indicate whether to do a graceful or forced …
=> POL-757 Azure Rightsize Compute Fixes/Improvements

cost/aws/reserved_instances/compute_purchase_recommendation/README.md, cost/aws/reserved_instances/coverage/README.md, cost/aws/savings_plan/utilization/README.md
Several READMEs listed ce:* permissions instead of more granular permissions. This aims to correct that.
=> POL-466 Remove ce:* Permissions from AWS READMEs

cost/google/idle_persistent_disk_recommendations/README.md
Two permissions are required for taking actions against disks raised in this policy that are not listed in the README. This adds them to the README.
=> POL-1006 Google Idle Persistent Disk Recommender Permissions Update

data/aws/instance_types.json
The Im4gn and Is4gen instance types, unlike all other types, were added to this file with the letter I capitalized. This caused issues for policies that expect consistent lowercase for this.
This is a simple fix to replace the above with their lowercase equivalents. I've searched the file for all capital letters in the alphabet and found no other instance types with this issue in this file.
N/A.
=> POL-817 AWS instance_types.json Casing Fix

cost/aws/rightsize_rds_instances/CHANGELOG.md, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
This fixes an issue where the policy was not correctly identifying unused instances if they had dashes in the name. The policy was incorrectly using the instance id, rather than the instance name, to find the instance in the Cloudwatch data.
https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=6581a75fd1dc74000182cdbb
=> POL-1012 AWS Rightsize RDS Dash Fix

cost/azure/hybrid_use_benefit/CHANGELOG.md, cost/azure/hybrid_use_benefit/azure_hybrid_use_benefit.pt
n the incident of Hybrid Use Benefit Policy, currency separator is shown as undefined:
[POL-982](https://flexera.atlassian.net/browse/POL-982)
[Applied policy](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=658230b65ec8620001b97922)
=> POL-982 Hybrid Use Benefit Policy - currency separator symbol shown as undefined

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
This non-breaking change updates the policy actions for the AWS Old Snapshots policy. Functionality is identical, but now the error logging is modernized and should work as expected in EU and APAC.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=658efa8f7cc18300018b4687
(Actions have been tested. The "failed" action for the above incident is because the snapshot was created via automation and thus does not qualify to be deleted, not because of any issue with the API call made by CWF)
=> POL-986 AWS Old Snapshots Policy Action Revamp

cost/azure/rightsize_sql_instances/CHANGELOG.md, cost/azure/rightsize_sql_instances/README.md, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt
Added optional `Minimum Age (Days)` parameter to filter results by age. This is for users that want to avoid reporting on freshly created databases that, as a result of their newness, have not had any connections and would therefore be seen as "unused" by the policy.
This is not a breaking change since the default value of this parameter is 0 and this functions just like the policy did without the parameter.
From the README:
- *Minimum Age (Days)* - The minimum age, in days, since a SQL database was created to produce recommendations for it. Set to 0 to ignore age entirely.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=659c1da07cc18300018b73f7
(Note: The above does not produce an incident because we don't have any old SQL servers in our test account. If …
=> POL-958 Add 'Minimum Age' to Azure Rightsize SQL

operational/itam/schedule_itam_report/CHANGELOG.md, operational/itam/schedule_itam_report/schedule-itam-report.pt
Replaced the jq function used from rt
[FOPTS-2229](https://flexera.atlassian.net/browse/FOPTS-2229)
https://app.flexera.com/orgs/28576/automation/applied-policies/projects/126887?policyId=659c762c9f8a200001ecef8a
If you don't have access to testing org 28576, you can watch the following GIF that shows the fixed error related to pagination:
=> FOPTS-2229 Added a way to url decode the skiptoken

compliance/aws/disallowed_regions/CHANGELOG.md, compliance/aws/disallowed_regions/README.md, compliance/aws/disallowed_regions/aws_disallowed_regions.pt, compliance/aws/disallowed_regions/aws_disallowed_regions_meta_parent.pt
This is a revamp of the AWS Disallowed Regions policy. Both the policy itself and CWF code for actions have been updated. Most of the code was adapted from similar policies that have received similar improvements. From the CHANGELOG:
- Policy no longer raises new escalations if tag data has changed for an instance
- Policy action error logging modernized and now works as expected in EU/APAC …
=> POL-991 AWS Disallowed Regions Revamp

compliance/google/unlabeled_resources/README.md
Updated Credential Permissions list in README
Current Permissions list is incorrect format, contains duplicate permissions, and contains a list of Roles (which are redundant in this case also) which is a legacy approach. This change fixes that.
=> POL-1057 Google Unlabeled Resources - Update Permissions in README

cost/google/schedule_instance/CHANGELOG.md, cost/google/schedule_instance/README.md, cost/google/schedule_instance/google_schedule_instance.pt, cost/google/schedule_instance/google_schedule_instance_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This is a full revamp of the Google Schedule Instance policy, including CWF actions. From the CHANGELOG:
- Added ability to specify custom tag keys for tracking instance schedules
- Added ability to filter resources by project
- Added ability to filter resources by region
- Added ability for user to start and stop instances directly
- Added additional fields to incident export for additional context
- Policy action error logging modernized and now works as expected in EU/APAC
- Added logic required for "Meta Policy" use-cases …
=> POL-1005 Google Schedule Instance Revamp

.github/workflows/generate-policy-master-permissions-json.yaml, Dangerfile, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml, tools/policy_master_permission_generation/generate_policy_master_permissions.rb, tools/policy_master_permission_generation/validated_policy_templates.yaml
* added policy permissions ruby script for parsing readmes for permissions
* added github workflow yaml file to automate running ruby script to create master policy permissions json file
* minor update to syntax to support older versions of ruby
* adding fileutils library to create the directory for the json file
* added exclude in gitignore for policy permissions json
* try using dist
* removed generated json file
* revert to ignoring the required "data/*" directory rather than dist
* test change
* add pull request in workflow
* Update Master Policy Permissions List (#1675)
* test revert back to original gitignore
* reverting as addition to .gitignore file is required for now
* Update Master Policy Permissions List (#1676)
* Update Master Policy Permissions List (#1680)
* Delete …
=> POL-918 Create Master Policy Permissions List (2) Continued

cost/azure/rightsize_managed_disks/CHANGELOG.md, cost/azure/rightsize_managed_disks/README.md, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
- Updated the descriptions and labels of the IOPS and throughput parameters in the README and policy template files.
- Updated the short description of the policy.
- Changed the functionality of `param_min_savings`: Before this version, the `param_min_savings` parameter was used to consider the total savings (the sum of all the savings per resource) and not the savings per resource to decide whether to recommend or not. In this new version, this parameter is used to recommend or not based on the savings of each resource, just as other policies do.
- https://flexera.atlassian.net/browse/FOPTS-3170
You can find the link to the applied policy in the following comment at Jira:
https://flexera.atlassian.net/browse/FOPTS-3170?focusedCommentId=2248041
=> FOPTS-3031 Update parameters of Azure Rightsize Managed Disk policy

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/README.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
This adds regex support to the AWS Old Snapshots policy. This is a breaking change, hence the major version number change, but anyone not currently using the tag filtering functionality should not be impacted by this change.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65d4d67160a6a60001794820
=> POL-1017 AWS Old Snapshots Regex Support

README_META_POLICIES.md
This adds detailed information about what roles the Flexera credential needs in order to use meta policies.
This is just a README change. No policies are modified.
=> POL-1067 Add Required Flexera Permissions to Meta Policy README

cost/cloud_cost_anomaly_alerts/CHANGELOG.md, cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
This fixes a bug where the link would render incorrectly if spaces were present. Spaces are now appropriately replaced with %20 in the link.
The change was tested in a customized version of this same policy. It also works in node:
❯ node
> filter = {'id': 'some stuff with spaces', 'value': 'even more spaces omg'}
{ id: 'some stuff with spaces', value: 'even more spaces omg' }
> value = "&filterBy=anomaly." + filter['id'] + "." + filter['value']
'&filterBy=anomaly.some stuff with spaces.even more spaces omg'
> while (value.split(' ')[1] != undefined) { value = value.replace(' ', '%20') }
'&filterBy=anomaly.some%20stuff%20with%20spaces.even%20more%20spaces%20omg'
>
=> POL-1068 Cloud Cost Anomaly Alerts Link Fix

cost/aws/instance_cloudwatch_utilization/CHANGELOG.md, cost/aws/instance_cloudwatch_utilization/README.md, cost/aws/instance_cloudwatch_utilization/aws_instance_cloudwatch_utilization.pt
The AWS Inefficient Instance Utilization using CloudWatch policy does basically the same thing as the existing Rightsize EC2 policy, so it is being deprecated.
=> POL-1070 Deprecate AWS Inefficient Instance Utilization using CloudWatch

cost/azure/rightsize_netapp_files/CHANGELOG.md, cost/azure/rightsize_netapp_files/azure_rightsize_netapp_files.pt
The short description of the policy Azure Rightsize NetApp Files was in sync with the Flexera documentation, this change updated the `short_description` of the policy so both descriptions match.
- https://flexera.atlassian.net/browse/FOPTS-3238
This did not updated any part of the code, only the short description, despite this I still applied the policy just in case:
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=65ddfce1f73314000135e2c4
It uploaded correctly, that means the code is fine. I attach this GIF if you are not able to log in Flexera test:
=> FOPTS-3238 Update `short_description` of the policy Azure Rightsize NetApp Files

cost/aws/rds_instance_license_info/CHANGELOG.md, cost/aws/rds_instance_license_info/README.md, cost/aws/rds_instance_license_info/rds_instance_license_info.pt, cost/aws/rds_instance_license_info/rds_instance_license_info_meta_parent.pt, cost/aws/rightsize_rds_instances/CHANGELOG.md, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
This modifies the AWS Rightsize RDS Instances policy to include Availability Zone, License Model, and vCPUs in the incident output, rendering the AWS RDS Instances policy obsolete.
Additionally, the AWS RDS Instances policy is flagged as deprecated, and users are directed to the AWS Rightsize RDS Instances policy in the README.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=65de53f71b78750001a4d0b1
=> POL-1071 Merge 'AWS RDS Instances' policy into 'AWS Rightsize RDS Instances'

cost/budget_v_actual_spend_report/CHANGELOG.md, cost/budget_v_actual_spend_report/budget_v_actual_spend_report.pt
Add links to documentation in the "Budget vs Actual Spend Report" policy short description
=> Add links to documentation in the policy short description

Dangerfile, cost/aws/old_snapshots/aws_delete_old_snapshots.pt
This is a total revamp of the Dangerfile that retains all existing functionality while also adding a couple of new checks around making sure policy blocks are in the correct order. The main purpose of this revamp is to clean up the file and get it neatly organized so that as we expand our testing, the file remains workable.
The Dangerfile is now split up into discrete neatly-labelled sections:
- **Required Libraries**: Contains require statements to include necessary Ruby libraries
- **File Sorting**: Sorts all of the files into neatly organized lists for later iteration.
- **Methods**: Most tests have now been moved into discrete methods for each test. This is where those are.
- **Github Pull Request Testing**: Run tests specific to Github and pull requests.
- **All Files Testing**: Run …
=> POL-1128 Dangerfile Revamp

cost/cloud_cost_anomaly_alerts/CHANGELOG.md, cost/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Fixed bug where incident showed dimensions from column `Grouping Dimensions` in random order.
https://flexera.atlassian.net/browse/SQ-6941
Latest version 3.1:
As you can see sometimes Azure appears at the beginning and sometimes at the middle
Incoming version 3.2:
Now they appear in the order specified by user.
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=65efef161909b512219a676e
=> SQ-6941 Sort the dimensions shown in the report

Rakefile, tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb
Moving the policy parser file inadvertently broke other automation. This is the fix.
=> Fix Issues with moved Policy Parser file

.dangerfile/policy_tests.rb, Dangerfile, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
The following tests have been added to the Dangerfile:
- Tests for whether the ordering of fields within a code block is correct.
- Test for whether recommendation policies have all of the required and recommended fields in the export block
The following bugs have been fixed:
- run_script order test now correctly expects val(iter_item, *string*) to come before other parameters. This is mostly revelent when run_script occurs within a request block.
=> POL-1140 Dangerfile Additions: Code Block Field Order and Recommendations Export

compliance/policy_update_notification/CHANGELOG.md, compliance/policy_update_notification/README.md, compliance/policy_update_notification/policy_update_notification.pt
This deprecates the Policy Update Notification policy and directs users to the more up to date and functional Flexera Automation Outdated Applied Policies policy.
=> POL-1156 Deprecate "Policy Update Notification" Policy

cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
Currently when `bill_source_expressions` is empty it creates an `or` condition with empty expressions, it causes that policy breaks in runtime, specifically with this error message:
`Invalid filter: invalid #4 AND expression: attribute 'expressions' must contain at least one expression for type \\\"or\\\": invalid argument\`
So we added a condition to validate if `bill_source_expressions` is empty, if so get rid to create that `or` condition.
SQ link: https://flexera.atlassian.net/browse/SQ-7053
CLONE link: https://flexera.atlassian.net/browse/FOPTS-3569
- Bug on empty `bill_source_expressions`.
[Previous version](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=65f9bf71d8f0b2e49c9c96f6)
[With …
=> FOPTS-3569 Fix: empty bill_source_expressions

operational/aws/tag_cardinality/README.md, tools/cloudformation-template/FlexeraAutomationPolicies.template, tools/cloudformation-template/releases/FlexeraAutomationPolicies_v0.8.0.template
This is an update to the AWS CloudFormation Template for Policies. The following changes were made:
- Updated permissions across the board to match our current documentation.
- Removed: Idle Compute policy since this policy is deprecated. 
- Removed: Unused RDS policy since this policy is deprecated. 
- Added: Rightsize RDS Instances
- Added: Rightsize EBS Volumes
- Added: Superseded Instances
- Added: Unused Classic Load Balancers (CLBs)
During review for this, a typo was discovered in the permissions for the AWS Tag Cardinality Report README. This has been fixed, as well as all other linting errors for this file.
This is the result of running this CFT, selecting for actions when possible, in our sales-sandbox account:
https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/ro …
=> POL-1172 Update AWS CloudFormation Template for Policies

cost/aws/rightsize_rds_instances/CHANGELOG.md, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt
This fixes an issue with the policy referencing an invalid API endpoint for the APAC shard. This was fixed in other policies already but somehow this specific policy slipped through the cracks.
Some other very minor tweaks around block names and ordering of fields were also made for the sake of conformity to other policies and to pass the new lint tests.
=> POL-1171 AWS Rightsize RDS Instances APAC Fix

data/azure/instance_types.json
Adds Instance Memory field to the existing instance_types.json for Azure. Memory Unit is in Gigabytes (GiB or 1024^3 bytes)
The Memory amount for some instances have been added to the file by hand through various sources. The list of instances is as follows:
-	Standard A8
-	Standard A9
-	Standard A10
-	Standard A11
-	Standard D2 v2 Promo
-	Standard D3 v2 Promo
-	Standard D4 v2 Promo
-	Standard D5 v2 Promo
-	Standard D11 v2 Promo
-	Standard D12 v2 Promo
-	Standard d13 v2 Promo
-	Standard D14 v2 Promo
-	Standard GS4-4
-	Standard GS4-8
-	Standard GS5-8
-	Standard GS5-16
-	Standard E64d v4
-	Standard H8
-	Standard H8m
-	Standard H16
-	Standard H16m
-	Standard H16r
-	Standard H16mr
-	Standard NV6 Promo
-	Standard NV12 Promo
-	Standard NV24 Promo 
Sources for memory data for each VM listed …
=> POL-1174 Update Azure Instance Types JSON to include Memory

data/aws/instance_types.json
Adds Instance Memory field to the existing instance_types.json for AWS. Memory Unit is in Gigabytes (GiB or 1024^3 bytes)
Some Instance Types don't have a Memory field in the updated instance_types.json file, however they did not have a vCPU field previously either. Those Instance Types are as follows:
- 'cc1.4xlarge'
- 'cg1.4xlarge'
- 'g4.large'
- 'g4.2xlarge'
- 'g4.4xlarge'
- 'g4.8xlarge'
- 'g4.16xlarge'
- 'hi1.4xlarge'
- 'm6g.24xlarge'
- 'm6gd.24xlarge'
We have customers asking to produce a report of amount of Instance Memory used, similar to the existing Instance vCPUs used policy. To achieve this it will require adding memory to the Instance Types JSON file.
=> POL-1173 Update AWS Instance Types JSON to include Memory

.dangerfile/policy_tests.rb, cost/azure/old_snapshots/azure_delete_old_snapshots.pt
Modifies Dangerfile indentation test for policies to only check indentation for EOS/EOF if it's for JavaScript code to avoid issues with lack of indentation due to a need to properly render markup/markdown languages for other fields.
=> POL-1180 Dangerfile Indentation Test Fix

.dangerfile/general_tests.rb
Updates Outdated Terminology test for Dangerfile to look only for instances of "rightscale" and "optima" surrounded by whitespace so that false positives are not raised for built-in policy constructs like `rs_optima_host` or for API endpoints that are still in active use.
Also updates test to ignore contents of data/ and tools/ since these are autogenerated assets. Issues should be corrected in the actual source files, not in generated assets and tools.
=> POL-1185 Dangerfile Outdated Terminology Update

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt, cost/aws/old_snapshots/aws_delete_old_snapshots_meta_parent.pt
The AWS API endpoint for gathering RDS snapshots will return a value for each instance of an iterative snapshot of a single RDS resource. This means a snapshot for a single RDS resource that only appears in the bill once would be returned by the API several times, even though each instance returned by the API was just a version of a single snapshot.
This fix adds new logic to account for this. When these iterative snapshots are found, only the most recent one is considered during the analysis instead of all of them. As a result, if someone has a daily backup of an RDS instance, the same instance with the same dollar value in the bill doesn't appear several times in the results, greatly inflating them. This also means that such snapshots will not be reported erroneously simply because …
=> POL-1183 AWS Old Snapshots RDS Duplicate Fix

tools/policy_master_permission_generation/validated_policy_templates.yaml, tools/policy_sync/CHANGELOG.md, tools/policy_sync/policy_sync.pt
Added parameters for the Policy Template Github Repo to enable this to be used for other repos without modifying Policy Template
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=6601da3c3ad5094c46961f0d
Example overriding defaults to use data from a public repo (this is for a customer PoC):
https://github.com/bryankaraffa/friendly-engine
- ~[ ] New functionality has been documented in the README if applicable~
=> feat: Add params for github repo for Policy Sync PT

operational/aws/total_instance_hours/CHANGELOG.md, operational/aws/total_instance_hours/README.md, operational/aws/total_instance_hours/aws_usage_instance_hours_used.pt, operational/aws/total_instance_memory/CHANGELOG.md, operational/aws/total_instance_memory/README.md, operational/aws/total_instance_memory/aws_usage_instance_memory_used.pt, operational/aws/total_instance_vcpus/CHANGELOG.md, operational/aws/total_instance_vcpus/README.md, operational/aws/total_instance_vcpus/aws_usage_instance_vcpus_used.pt
This is a change to add parameters which allow the user to filter (Allow or Deny) for a list of Billing Centers and a list of Regions to report on. This parameter will be added to the following Usage Report policies:
- AWS Usage Report - Number of Instance Hours Used
- AWS Usage Report - Number of Instance vCPUs Used
- AWS Usage Report - Amount of Instance Memory Used
- Adds functionality to make the policy more valuable to customers who may want to produce a Usage Report for specific Billing Centers and/or Regions.
- Brings these policies in line with their Azure counterparts.
- Resolves inaccuracies in the policy template Readme files regarding the listed input parameters.
Applied policy in customer tenant. Some examples:
No filters:
Allowing specific regions, denying specific BCs: …
=> POL-1196 Update AWS Usage Report policies to include BC Filter and Region Filter

cost/flexera/cco/cloud_cost_anomaly_alerts/CHANGELOG.md, cost/flexera/cco/cloud_cost_anomaly_alerts/cloud_cost_anomaly_alerts.pt
Currently when we click on the incident link of `cloud_cost_anomaly_alerts.pt` in mail, we get this error in the dashboard:
`Load Anomalies failed at this time`
The issue is happening because the link is including `)**` at the end of the url, once it's removed it returns the proper result to page.
Incident URL in mail.
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=66203f3be6626311ea1adc0b
=> FOPTS-3836 Fix: cloud_cost_anomaly_alerts.pt incident link

compliance/aws/untagged_resources/CHANGELOG.md, compliance/aws/untagged_resources/aws_untagged_resources.pt
Fixes error `ReferenceError: 'tag_dimension_tag_keys' is not defined`
https://flexera.atlassian.net/browse/POL-1214
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=662adbe9f5c05009ea60a63d
=> POL-1214 - fix: error for tag_dimension_tag_keys not defined

cost/azure/reserved_instances/utilization/CHANGELOG.md, cost/azure/reserved_instances/utilization/README.md, cost/azure/reserved_instances/utilization/azure_reserved_instance_utilization.pt, operational/azure/total_instance_hours/CHANGELOG.md, operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt, operational/azure/total_instance_memory/CHANGELOG.md, operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt, operational/azure/total_instance_vcpus/CHANGELOG.md, operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
Microsoft provides a CSV file which has a mapping of instance types, their respective Instance Families, and their respective normalization factor unit.
The CSV is available via a URL, however the current URL (https://isfratio.blob.core.windows.net/isfratio/ISFRatio.csv) no longer works and has been replaced with a new URL (https://aka.ms/isf)
This is causing several policies to fail.
This is a change to update the URL for all policies referencing this CSV file, thereby fixing the policies.
Tested in two customer tenants - policy is working as it previously did after the URL change.
=> POL-1219 Update policies referencing Microsoft ISF Ratio CSV

operational/aws/total_instance_hours/CHANGELOG.md, operational/aws/total_instance_hours/aws_usage_instance_hours_used.pt, operational/aws/total_instance_memory/CHANGELOG.md, operational/aws/total_instance_memory/aws_usage_instance_memory_used.pt, operational/aws/total_instance_vcpus/CHANGELOG.md, operational/aws/total_instance_vcpus/aws_usage_instance_vcpus_used.pt, operational/azure/total_instance_hours/CHANGELOG.md, operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt, operational/azure/total_instance_memory/CHANGELOG.md, operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt, operational/azure/total_instance_vcpus/CHANGELOG.md, operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt
Usage Reports for AWS and Azure (e.g., Amount of Instance Memory Used, Number of Instance vCPUs Used, etc.) currently allow the user to define a list of Billing Centers to report on which can either be allowed/filtered in or denied/filtered out.
The current logic only supports filtering on top-level billing centers, which means that child billing centers cannot be specifically reported on.
This is a change to add support for filtering on child billing centers when applying the policy to generate a report.
Fixes issue where only top-level billing centers could be filtered on. Policy now additionally supports filtering on child billing centers.
Tested in customer tenant, and working as expected. Some examples below of chart produced in policy incident:
AWS Instance vCPUs Used (all Billing …
=> POL-1221 Usage Report Policies - Update BC Filter to support Child Billing Centers

cost/azure/savings_realized/CHANGELOG.md, cost/azure/savings_realized/azure_savings_realized.pt
- Adds a new parameter that lets the user decide on the format for the currency shown in the incident's chart: code (e.g. USD) or symbol (e.g. $).
- Fixes a bug that showed inflated savings on the instances.
https://flexera.atlassian.net/browse/SQ-7228
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=66353ae2e2d700d7f57fe119
=> SQ-7228 Incorrect currency code and inflated savings bug

cost/scheduled_report_unallocated/CHANGELOG.md, cost/scheduled_report_unallocated/README.md, cost/scheduled_report_unallocated/scheduled_report_unallocated.pt
- Fixed bug that related to Summarized Unallocated amount and Unallocated Percent of Total in report
- Added filter for excluding rows that are below a certain percent of total costs
- Added Time Period and Filters to report output
- Added `unallocated` (bool) and `unallocated_details` (string) columns to report output
- Report column order will match the order user provided in parameter input
https://app.flexera.com/orgs/27915/automation/incidents/projects/123322?incidentId=663d36baaf700bfc2e0e190a
=> POL-1228 feat: Unallocated Cost Report enhancements

cost/flexera/cco/cheaper_regions/CHANGELOG.md, cost/flexera/cco/cheaper_regions/README.md, cost/flexera/cco/cheaper_regions/cheaper_regions.pt, data/aws/regions.json, data/azure/regions.json, data/google/regions.json, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml, tools/policy_master_permission_generation/validated_policy_templates.yaml
Issue reported in this support question: https://flexera.atlassian.net/browse/SQ-7976 by Albertsons.
Policy is returning empty results, checking the code it's because some regions for Azure and AWS are outdated, previously we had for example: `US West`, `US West 2`, etc. But now those are named `West US`, `West US 2`, etc. Also few `console.log` statements were removed.
Policy is returning empty results because of outdated regions for Azure and AWS vendors.
https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=663e4547ba767e47966578c9
=> FOPTS-3939 Update: List of cheaper regions for Azure and AWS vendors

data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml, operational/azure/total_instance_hours/CHANGELOG.md, operational/azure/total_instance_hours/README.md, operational/azure/total_instance_hours/azure_usage_instance_hours_used.pt, operational/azure/total_instance_memory/CHANGELOG.md, operational/azure/total_instance_memory/README.md, operational/azure/total_instance_memory/azure_usage_instance_memory_used.pt, operational/azure/total_instance_usage_report/CHANGELOG.md, operational/azure/total_instance_usage_report/README.md, operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt, operational/azure/total_instance_vcpus/CHANGELOG.md, operational/azure/total_instance_vcpus/README.md, operational/azure/total_instance_vcpus/azure_usage_instance_vcpus_used.pt, tools/policy_master_permission_generation/validated_policy_templates.yaml
This is a new policy, `Azure Usage Report - Instance Time Used`, that replaces the following policies that are being deprecated as part of this same change:
- `Azure Usage Report - Number of Instance Hours Used`
- `Azure Usage Report - Number of Instance vCPUs Used`
- `Azure Usage Report - Amount of Instance Memory Used`
This was done because these policies were almost identical; as a consequence, it really didn't make sense to maintain 3 separate policies for something that could be a simple user parameter. The READMEs of these policies have been updated to direct users to this policy.
The new policy contains all of the functionality of the above, allowing the user to simply select which unit they want to report against. Additionally, the following improvements have been made:
The user …
=> POL-1231 New Policy: Azure Usage Report - Instance Time Used

cost/flexera/cco/budget_v_actual_spend_report/CHANGELOG.md, cost/flexera/cco/budget_v_actual_spend_report/README.md, cost/flexera/cco/budget_v_actual_spend_report/budget_v_actual_spend_report.pt
This change address the request at [SQ-8125](https://flexera.atlassian.net/browse/SQ-8125)
- Added Cumulative report option 
- Cumulative chart should show cumulative monthly data
- Cumulative table should show cumulative based on groups
- For cumulative report shows a note to indicate that budget, Spend, OverSpend columns shows cumulative data
- Exclude future data in charts
- Not include currency sign in the table
- Chart axis shows accurate currency sign
The history of request changes and also proof of test could be found in the task : [FOPTS-4009](https://flexera.atlassian.net/jira/software/c/projects/FOPTS/boards/398?assignee=712020%3A90605881-06e4-4701-9150-efda16878a29&selectedIssue=FOPTS-4009)
1- [Cumulative report example](https://app.flexera.com/orgs/1105/automation/applied-polic …
=> FOPTS-4009 add cumulative report option

operational/aws/total_instance_usage_report/CHANGELOG.md, operational/aws/total_instance_usage_report/aws_total_instance_usage_report.pt, operational/azure/total_instance_usage_report/CHANGELOG.md, operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt
Current AWS and Azure Usage Report - Instance Time Used policies will fail when a user specifies a list of Billing Centers to Allow or Deny. This is a change to fix this issue.
- Fixed issue with Billing Center filter so users can now successfully allow/deny Billing Centers from the Usage Report.
Tested in customer tenant where the original policy error was found.
=> POL-1246 AWS/Azure Usage Reports - fix BC Allow/Deny Filter

compliance/aws/iam_role_audit/CHANGELOG.md, compliance/aws/iam_role_audit/aws_iam_role_audit.pt
Add default value for `IAM Role Names/IDs/ARNs` param
This is helpful so we can deploy using the Meta Parent Policy Template and no required user input parameters.
Value is the name of the role created by the recommended Cloud Formation Template
=> POL-1247 fix: Add default value for `IAM Role Names/IDs/ARNs` param

operational/aws/total_instance_usage_forecast/CHANGELOG.md, operational/aws/total_instance_usage_forecast/aws_total_instance_usage_forecast.pt, operational/aws/total_instance_usage_report/CHANGELOG.md, operational/aws/total_instance_usage_report/aws_total_instance_usage_report.pt, operational/azure/total_instance_usage_report/CHANGELOG.md, operational/azure/total_instance_usage_report/azure_total_instance_usage_report.pt
When creating a report for Instance Time Used it should render in emails. It works for Normalized Units/Instances and vCPUs, however it does not render correctly for Memory Used. 
This is likely being caused by the Chart Title, which in the case of Memory Used, contains parentheses. These parentheses are not being URL encoded.
This is a change to implement a fix.
- Fixes issue where parentheses are not encoded correctly in the image-charts URL
=> POL-1249 fix: AWS/Azure Usage Reports - fix chart not rendering in email for Memory Used

cost/azure/rightsize_managed_disks/CHANGELOG.md, cost/azure/rightsize_managed_disks/README.md, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
Users wanted a parameter to enable or disable recommendations that suggested switching disk tier to Standard HDD.
- https://flexera.atlassian.net/browse/POL-1271
Link can't be published since this is in private organization, but results look good, no HDD recommendations are being done:
=> POL-1271 Add parameter to decide recommending HDD or not

compliance/aws/untagged_resources/CHANGELOG.md, compliance/aws/untagged_resources/aws_untagged_resources.pt, operational/aws/tag_cardinality/CHANGELOG.md, operational/aws/tag_cardinality/aws_tag_cardinality.pt
Fixes an issue discovered when troubleshooting the `AWS Untagged Resources` Policy Template
- Use [`PaginationToken`](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html#API_GetResources_RequestSyntax) for paginating tagging API
=> POL-1300 - fix: use `PaginationToken` for paginating tagging API

cost/azure/rightsize_managed_disks/CHANGELOG.md, cost/azure/rightsize_managed_disks/README.md, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
I implemented the statistics P90, P95 and P99 for the parameters:
- IOPS Threshold Statistic
- Throughput Threshold Statistic
- https://flexera.attlassian.com/browse/POL-1169
Applied policy link cannot be shared, but here are some screenshots:
*New incident fields*
*Data used for validation*
```
EXAMPLE 1
console.log:
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,3.316666666666667,3.316666666666667,3.3333333333333335,3.35,3.35,3.3666666666666667,3.3833333333333333,3.4,3.433333333333333,3.45,3.466666666666667,3.4833333333333334,3.4833333333333334,3.5,3.5,3.5,3.5166666666666666,3.533333333333333,3. …
```
=> POL-1169 P90, P95 and P99 for Azure Rightsize Managed Disks

cost/aws/rightsize_ec2_instances/CHANGELOG.md, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt
Fix bug preventing Memory metrics from being included in result for some EC2 Instances created by Autoscaling Group
https://flexera.atlassian.net/browse/POL-1323
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=66c37967a79b5457a2816c0d
=> POL-1323 - fix: AWS Rightsize EC2 get memory metrics for Autoscaling groups

data/active_policy_list/generally_recommended_templates.json
Databricks has a prerequisite to create Tag Dimension and if a user deploys this PT (i.e. using Onboarding Policy Template) then the PT will error
=> task: remove Databricks from generally recommended

cost/azure/savings_plan/expiration/CHANGELOG.md, cost/azure/savings_plan/expiration/azure_savings_plan_expiration.pt
The policy_set field in the policy template metadata has been changed from its current value of "Savings Plan" to "Savings Plans" . 
This does not change the functionality of the policy but it does help us internally with reporting on templates in our repository.
=> POL-1364 Update Azure Savings Plan Expiration - Fix Policy Set value

cost/aws/superseded_ebs_volumes/README.md
Updated policy template name in readme from `AWS Rightsize EBS Volumes` to `AWS Superseded EBS Volumes`
Updates the Policy Template Name in the README doc from `AWS Rightsize EBS Volumes` to `AWS Superseded EBS Volumes`
Fixes the name in readme doc to be correct.
N/A
=> POL-1368 AWS Superseded EBS Volumes - Update Name in Readme

.dangerfile/policy_tests.rb, cost/aws/schedule_instance/CHANGELOG.md, cost/aws/schedule_instance/aws_schedule_instance.pt, cost/aws/schedule_instance/aws_schedule_instance_meta_parent.pt, cost/azure/schedule_instance/azure_schedule_instance_meta_parent.pt, cost/google/schedule_instance/CHANGELOG.md, cost/google/schedule_instance/google_schedule_instance.pt, cost/google/schedule_instance/google_schedule_instance_meta_parent.pt, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
https://github.com/flexera-public/policy_templates/actions/runs/11059501776
Workflow is currently failing on a PT
```
Writing parent policy template: ../../security/azure/sql_auditing_retention/sql_auditing_retention_meta_parent.pt
meta_parent_policy_compiler.rb:334:in `block in compile_meta_parent_policy': undefined method `scan' for nil (NoMethodError)
fields = export_block[0].scan(/(^.*field\s+\".*?\".*?end)/m).flatten
^^^^^
from meta_parent_policy_compiler.rb:314:in `each'
from meta_parent_policy_compiler.rb:314:in `compile_meta_parent_policy'
from meta_parent_policy_compiler.rb:467:in `block in <main>'
from meta_parent_policy_compiler.rb:466:in `each'
from meta_parent_policy_compiler.rb:466:in `<main>'
```
Modified Workflow Run Succesful: …
=> POL-1347 - fix: meta_parent_policy_compiler.rb no export block

data/aws/instance_types.json
- ~~C family (e.g., c4 → c5)~~ (already in file)
- ~~M family (e.g., m4 → m5)~~ (already in file)
- R family (e.g., r4 → r5)
- DB instances:
- M family (e.g., db.m4 → db.m5)
- R family (e.g., db.r4 → db.r5)
Resolves issue where AWS Superseded EC2 Instances policy does not report on the above instance types despite them being superseded.
=> POL-1370 Update AWS Instance Types JSON to include superseded instances for r, db.m, db.r families

cost/azure/rightsize_managed_disks/CHANGELOG.md, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt
This addresses the issue when calculating the IOPS and Bandwith of Premium SSD V2 disk recommendations.
https://flexera.atlassian.net/browse/POL-1329
Applied policy is in client environment but we received confirmation that new calculations are working well thanks to these changes, for more context please visit: https://flexera.atlassian.net/browse/POL-1329
=> POL-1329 Fix calculation of IOPS and Bandwith at Azure Rightsize Managed Disk

cost/aws/superseded_ebs_volumes/CHANGELOG.md, cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes.pt, cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes_meta_parent.pt, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml
This policy was previously showing incorrect values in the incident for "New Monthly List Price" and "Estimated Monthly Savings". 
This change improves the querying of the AWS Price List API to capture all prices associated with GP3 volumes to provide an accurate value for both these fields in the policy incident.
Policy incident now shows accurate values for "New Monthly List Price" and "Estimated Monthly Savings" to the user.
Tested in multiple customer tenants.
=> POL-1373 Update AWS Superseded EBS Volumes - fix incorrect "New Monthly List Price" value

data/aws/instance_types.json
- DB instances:
- M family (e.g., db.t2 → db.t3)
Potentially allows for testing the new AWS Superseded RDS Instances policy using RDS resources in existing Flexera One tenants.
=> POL-1381 Update AWS Instance Types JSON to include superseded instances for db.t family

data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml, operational/azure/azure_certificates/CHANGELOG.md, operational/azure/azure_certificates/azure_certificates.pt, operational/azure/azure_certificates/azure_certificates_meta_parent.pt
Regardless of the threshold set, the Azure Expiring Certificates policy returns (in the incident) certificate resources that will expire months and years from now. The reason for this is an incorrect calculation which makes the 'Days Until Expiration' a negative number. This is a change to fix this.
- 'Days Until Expiration' no longer produces a negative value in the policy incident.
- Certificate resources outside of the threshold set are no longer returned in the policy incident.
=> POL-1398 Azure Expiring Credentials - fix Days Until Expiration bug

cost/aws/superseded_ebs_volumes/CHANGELOG.md, cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes.pt, cost/aws/superseded_ebs_volumes/aws_superseded_ebs_volumes_meta_parent.pt, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml
This change fixes a bug in the policy incident of the AWS Superseded EBS Volumes policy in a customer's tenant.
This bug occurs when the customer’s native currency in the platform is not USD: 
> “Price and savings values are in USD due to a malfunction with Flexera's internal currency conversion API. Please contact Flexera support to report this issue.”
This message is incorrectly showing even though currency conversion was successful.
This change fixes this bug.
Fixes a bug where the Currency Conversion messaging in the policy incident is incorrectly showing.
Tested in customer tenant.
=> POL-1404 AWS Superseded EBS Volumes - Fix Currency Conversion Message in Policy Incident

cost/aws/rightsize_ebs_volumes/CHANGELOG.md, cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes.pt, cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt, cost/aws/rightsize_ec2_instances/CHANGELOG.md, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances.pt, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt, cost/aws/rightsize_elasticache/CHANGELOG.md, cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt, cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt, cost/aws/rightsize_rds_instances/CHANGELOG.md, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt, cost/aws/rightsize_redshift/CHANGELOG.md, cost/aws/rightsize_redshift/aws_rightsize_redshift.pt, cost/aws/rightsize_redshift/aws_rightsize_redshift_meta_parent.pt
Adding a new hide_skip_approvals field to the info section of policy templates that do not utilize the request approval option in any escalation. This field enables the UI to dynamically show or hide the "Skip Approval" option based on the policy configuration. Initially, these changes are applied to AWS Right Size policies, with plans to update additional policies in subsequent steps.
More context:[ Seeking Your Input: Proposed Solution for Conditional "Skip Approvals" Visibility](https://teams.microsoft.com/l/message/19:833373548e104af2a20b0216eda1ba7b@thread.skype/1728495063426?tenantId=91034d23-0b63-4943-b138-367d4dfac252&groupId=fb250818-e040-4a26-b207-61c3cd99fd6e&parentMessageId=1728495063426&teamName=Team%20Flexera%20One&channelName=Policy%20Support%20and%20Questions&createdTime=17 …
=> FOPTS-4819 Added `hide_skip_approvals` to AWS Right Size policies

Rakefile, cost/aws/rightsize_ebs_volumes/aws_rightsize_ebs_volumes_meta_parent.pt, cost/aws/rightsize_ec2_instances/aws_rightsize_ec2_instances_meta_parent.pt, cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt, cost/aws/rightsize_rds_instances/aws_rightsize_rds_instances_meta_parent.pt, cost/aws/rightsize_redshift/aws_rightsize_redshift_meta_parent.pt, tools/meta_parent_policy_compiler/aws_meta_parent.pt.template, tools/meta_parent_policy_compiler/azure_meta_parent.pt.template, tools/meta_parent_policy_compiler/google_meta_parent.pt.template, tools/meta_parent_policy_compiler/meta_parent_policy_compiler.rb
This pull request enhances the Meta Parent Policy Template Compiler to conditionally include the hide_skip_approvals field in the generated meta parent policy templates when it exists in the child policy templates.
It also removes prior manual modifications to meta parent policies : https://github.com/flexera-public/policy_templates/pull/2799
More context:[ Seeking Your Input: Proposed Solution for Conditional "Skip Approvals" Visibility](https://teams.microsoft.com/l/message/19:833373548e104af2a20b0216eda1ba7b@thread.skype/1728495063426?tenantId=91034d23-0b63-4943-b138-367d4dfac252&groupId=fb250818-e040-4a26-b207-61c3cd99fd6e&parentMessageId=1728495063426&teamName=Team%20Flexera%20One&channelName=Policy%20Support%20and%20Questions&createdTime=1728495063426) …
=> FLEX-5397 - Modify Meta Parent Compiler to Conditionally Include `hide_skip_approvals`

cost/google/rightsize_vm_recommendations/CHANGELOG.md, cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations.pt, cost/google/rightsize_vm_recommendations/google_rightsize_vm_recommendations_meta_parent.pt
We had an issue sorting recommendations when cpuAvergae. cpuMinimum or cpuMaximum are nulls. 
[FOPTS-5666](https://flexera.atlassian.net/browse/FOPTS-5666)
[SQ-10199](https://flexera.atlassian.net/browse/SQ-10199)
=> FOPTS-5666 Handle properly null values in Google Rightsize VM Recommender Policy

cost/kubecost/cluster/CHANGELOG.md, cost/kubecost/cluster/kubecost_cluster_rightsizing_recommendations.pt
This update introduces functionality to handle automatic currency conversion within Kubecost cluster rightsizing policy, ensuring that incidents reflect values across different currencies.
* Support for multiple currencies has been added to the system.
* If the kubecost config endpoint returns an empty currency, USD (United States Dollar) will be used as the default currency.
* A condition has been implemented where, if Kubecost's currency matches Flexera's, no currency conversion will take place.
Resolves the issue where currency discrepancies occurred between our template and Kubecost when they had different base currencies.
https://flexera.atlassian.net/browse/POL-1414
Link Applied policy: https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6751ebfb0f84 …
=> POL-1414 Currency Conversion Functionality on Kubecost cluster rightsizing policy

cost/aws/rightsize_elasticache/CHANGELOG.md, cost/aws/rightsize_elasticache/aws_rightsize_elasticache.pt, cost/aws/rightsize_elasticache/aws_rightsize_elasticache_meta_parent.pt, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml
This change rearranges the code so that the `savings` variable is no longer being referenced before it is declared/defined, meaning the policy no longer fails when it is run.
Fixed an issue with the `savings` variable causing the policy to fail.
Custom policy with these changes have been applied in the customer's tenant and they have confirmed it is now working again as expected.
=> POL-1443 AWS Rightsize Elasticache - Fix undeclared variable causing policy to fail

operational/azure/marketplace_new_products/CHANGELOG.md, operational/azure/marketplace_new_products/azure_marketplace_new_products.pt
We changed the method used to obtain the bill connections, now instead of calling the bill-connects API we fetch cost data and get the bill connections from there, this change is required since MSP customers have a different way of configuring their bill connects, and that method would make the policy fail.
This also adds support for MCA connections.
Code change used here is based on already tested code for policy template **Azure Savings Realized from Reservations**.
- https://flexera.atlassian.net/browse/FOPTS-6315 (Refactor  Azure New Marketplace Products policy)
- https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6786e49cc605973ecfa7a53f
Please ignore the following message:
The linter is not able to tell that the script that this datasource uses …
=> FOPTS-6034 Make Azure New Marketplace Products Policy Support MSP Configurations

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
This change skips memory recommendations when data from recently rightsized instances gets mixed with current data making negative values for memory usage.
Here's a much more detailed explanation of the problem: https://flexera.atlassian.net/browse/SQ-12222?focusedCommentId=2672680
- https://flexera.atlassian.net/browse/SQ-12222
Policy compiles well: https://app.flexeratest.com/orgs/1105/automation/projects/60073/policy-templates/648b803cfa3d220001edf8cf
BEFORE
NOW
=> FOPTS-6730 Fix negative memory statistics for recently rightsized resources | Policy: Azure Rightsize Compute Instances

operational/flexera/cco/bill_processing_errors_notification/CHANGELOG.md, operational/flexera/cco/bill_processing_errors_notification/README.md, operational/flexera/cco/bill_processing_errors_notification/bill_processing_errors_notification.pt
Added a new parameter (disable by default) to report connections with no bills. This is asked by one of the customers (Accenture) as they want to be able to identify misconfigured bill connection.
https://flexera.atlassian.net/browse/SQ-12286
Applied Policy (new version) : [link](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6792e3378687658d73c806e7)
Applied Policy (Old version) : [link](https://app.flexera.com/orgs/1105/automation/applied-policies/projects/60073?policyId=6792e31039f75cb7b51030d7)
- [* ] New functionality includes testing.
- [*] New functionality has been documented in the README if applicable
- [*] New functionality has been documented in CHANGELOG.MD
=> FOPTS-6822 Enhance "Cloud Bill Processing Error Notification" Policy to Report Connections with Zero Imported Bills

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
This PR changed the way to calculate "used memory" for Azure instances.
Previously the policy is trying to compute "used memory" by substracting "available memory" from "total memory".
This PR has changed to directly retrieving "available memory" from Azure metrics.
The previous method had flawed if the "total memory" is changed due to instance resizing.
- https://flexera.atlassian.net/browse/SQ-12222
https://app.flexeratest.com/orgs/1105/automation/projects/60073/policy-templates/67c1fc4249c80a0e0d6140d9
**BEFORE**
**NOW**
=> FOPTS-7572 Changed the way to calculate used memory | Policy: Azure Rightsize Compute Instances

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt
Memory stats were showing decimal numbers (such as `0.5` for half), instead of showing percentage (such as `50` for half).
Showing `50` for half and `100` for all is the expected behavior.
- https://flexera.atlassian.net/browse/SQ-12222
- https://flexera.atlassian.net/browse/FOPTS-7572
Before the change:
After the change:
=> FOPTS-7572 Fixed memory stats showing decimal instead of percentage | Policy: Azure Rightsize Compute Instances

cost/flexera/cco/cbi_ingestion_azure_blob/CHANGELOG.md, cost/flexera/cco/cbi_ingestion_azure_blob/cbi_ingestion_azure_blob.pt
Fixed OAuth2 authentication for `Common Bill Ingestion from Azure Blob Storage` policy.
This is caused by the request missing `x-ms-version` header.
(See section "**Requests that use an OAuth 2.0 token from Microsoft Entra**" in Microsoft documentation [Versioning for Azure Storage](https://learn.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services#specify-service-versions-in-requests))
https://flexera.atlassian.net/browse/FOPTS-8007
https://flexera.atlassian.net/browse/SQ-13259
**Policy log prior to this change:**
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=67d34fec81c5ea9238715455
**Policy log after this change:**
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=67d454 …
=> FOPTS-8007 Fixed OAuth authentication for `Common Bill Ingestion from Azure Blob Storage` policy

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Fixed incorrect calculation for "average used memory".
https://flexera.atlassian.net/browse/SQ-12222
[applied policy v6.1.1](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=67db1329ce3e463416cd6650)
[policy execution log for v6.1.1](https://github.com/user-attachments/files/19349592/6.1.1.txt)
[applied policy for this PR](https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/107982?policyId=67db12a9ce3e463416cd664e)
[policy execution log for this PR](https://github.com/user-attachments/files/19349594/6.1.2.txt)
The main difference is the `mem_average` field.
In previous version, the `mem_average` field was showing "average **available** memory".
In current version, the `mem_average` field is showing "average **used** memory".
=> SQ-12222 Fixed incorrect calculation for "average used memory"

compliance/flexera/fnms/fnms_licenses_expiring/CHANGELOG.md, compliance/flexera/fnms/fnms_licenses_expiring/expiring_licenses.pt
Fixed issue with retired status not being filtered out of the results
Fixed issue with retired status not being filtered out of the results
Test: (also verified in customer tenant)
https://app.flexera.com/orgs/36084/automation/incidents/projects/138037?incidentId=67e42fe1b9cfdee216feadb4
=> POL-1468  Bug/fixing retired status in results ITAM Expiring Licenses

cost/azure/schedule_instance/CHANGELOG.md, cost/azure/schedule_instance/README.md, cost/azure/schedule_instance/azure_schedule_instance.pt
- Added retry mechanism in case of failed actions or timeout waiting for the expected status change
- Fixed issue preventing schedules being enforced when first action attempt fails
- Added "Last Stop Status", "Last Stop Time", "Last Start Status", "Last Start Time" details to instance list
https://flexera.atlassian.net/browse/POL-1435
https://flexera.atlassian.net/browse/POL-1436
https://flexera.atlassian.net/browse/POL-1437
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954
=> POL-1435 POL-1436 POL-1437 - feat: Schedule Instance PT Enhancements

tools/cloudformation-template/FlexeraAutomationPolicies.template, tools/cloudformation-template/FlexeraAutomationPoliciesReadOnly.template, tools/cloudformation-template/aws_cft_generator.rb
Fixed issue with the AWS CloudFormation Template generator script that was causing it to include deprecated policies and not remove deleted policies.
=> POL-1511 CloudFormation Generator Fix

cost/flexera/cco/scheduled_report_unallocated/CHANGELOG.md, cost/flexera/cco/scheduled_report_unallocated/scheduled_report_unallocated.pt
This change fixes the error that costs/select API returns when the parameter date range is set to 30 days.
- https://flexera.atlassian.net/browse/SQ-14908
Policy compiles ok https://app.flexeratest.com/orgs/1105/automation/projects/107982/policy-templates/681ceebfeaab44c2bb166f83
Customer confirmed it worked
=> SQ-14908 Fix the error with Last 30 days parameter

cost/aws/old_snapshots/CHANGELOG.md, cost/aws/old_snapshots/aws_delete_old_snapshots.pt
This PR addresses an issue in the policy template's RDS snapshot filtering logic that was causing some snapshots to be incorrectly excluded from policy evaluation.
The js_describe_db_snapshots script was incorrectly filtering RDS snapshots. It was grouping snapshots by ParentId (the RDS instance identifier), sorting them by StartTime, and then only retaining the most recent snapshot for each ParentId. This meant that older snapshots, even if they met other policy criteria (like age), were being ignored. This behavior could lead to:
* Data Governance Gaps: Older snapshots, which might be needed for compliance or audit purposes, were not being properly managed by the policy.
* Cost Optimization Inefficiencies: Opportunities to identify and manage older, potentially costly snapshots were …
=> FOPTS-9434 Correctly include all RDS snapshots in policy evaluation

cost/flexera/cco/currency_conversion/CHANGELOG.md, cost/flexera/cco/currency_conversion/currency_conversion.pt, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml
This fixes an issue with the Currency Conversion policy template where execution would fail if the user built off of the adjustment created by this policy template.
The currency conversion adjustment is now always first in the list being sent into the API, ensuring no issues if later adjustment rules build off of it.
Fix tested in client environment where issue was reported.
=> POL-1524 Currency Conversion Fix

cost/aws/schedule_instance/README.md, cost/aws/unused_volumes/README.md, cost/azure/schedule_instance/README.md, cost/google/schedule_instance/README.md, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml, tools/cloudformation-template/FlexeraAutomationPolicies.template, tools/cloudformation-template/FlexeraAutomationPoliciesReadOnly.template, tools/policy_master_permission_generation/generate_policy_master_permissions.rb
Read-only CFT for AWS contained some write permissions that appear to be related to how the AWS Schedule Instance policy template README.md file was being scraped.
- Added * with comment "These permissions enable taking actions against cloud resources." to the READMEs for all 3 Schedule Instance policy templates.
- Modified permissions scraper to account for the above.
- Modified permissions scraper to check permission for words that indicate a permission is not read-only, such as "write" and "create", as a failsafe in case the README is not properly configured.
- Reran the permissions scraper and CFT generation to confirm that the issue is now resolved.
=> POL-1529 Fixed Write Permissions in AWS Read Only CFT

cost/azure/rightsize_compute_instances/CHANGELOG.md, cost/azure/rightsize_compute_instances/README.md, cost/azure/rightsize_compute_instances/azure_compute_rightsizing.pt, cost/azure/rightsize_compute_instances/azure_compute_rightsizing_meta_parent.pt
Migrated from "Metrics" API to "Metrics getBatch" API, improving policy performance.
https://flexera.atlassian.net/browse/FOPTS-9865
https://flexera.atlassian.net/browse/SQ-12222
Stage environment:
https://app.flexeratest.com/orgs/1105/automation/applied-policies/projects/60073?policyId=68276c51a41ab021c0742496
Also made multiple runs on customer UAT environment to compare performance with current policy.
https://app.flexera.com/orgs/32682/automation/applied-policies/projects/133896?policyId=68256506ecdd6efd5e309aa7
https://app.flexera.com/orgs/32682/automation/applied-policies/projects/133896?policyId=682541ac045a90c67da137f8
https://app.flexera.com/orgs/32682/automation/applied-policies/projects/133896?policyId=682524c5c092e0cdbfd3a8b0
The most granular "Statistic Interval" that current …
=> FOPTS-9865 Performance improvement -- migrated to Metrics getBatch API call

cost/azure/rightsize_sql_instances/CHANGELOG.md, cost/azure/rightsize_sql_instances/README.md, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances.pt, cost/azure/rightsize_sql_instances/azure_rightsize_sql_instances_meta_parent.pt, data/policy_permissions_list/master_policy_permissions_list.json, data/policy_permissions_list/master_policy_permissions_list.yaml
Azure Rightsize SQL Databases changes:
- Policy template now distinguishes between vCore-model and DTU-model databases and checks CPU and DTU metrics to determine usage for each purchase model respectively.
- Fixed issue where policy template would report new recommendations if a metric other than cpuAverage had changed for an existing recommendation.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=682e33dafb0915fc14dcc30a
(Also tested in client environment with actual incident results)
=> POL-1528 DTU support for Azure Rightsize SQL Databases

.github/workflows/generate-policy-release-notifications.yaml, tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
Updates the Ruby script and Github Workflow for sending release notifications to Teams.
Workflow now completes execution as expected. I tested it with some mock data and it now sends a notification.
=> POL-1532 Catalog Update Teams Notifications Failing

cost/azure/rightsize_managed_disks/CHANGELOG.md, cost/azure/rightsize_managed_disks/README.md, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks.pt, cost/azure/rightsize_managed_disks/azure_rightsize_managed_disks_meta_parent.pt
Azure Rightsize Managed Disks
- Policy template no longer raises an incident if user does not set any thresholds for determining underutilization.
- Defaults changed for `IOPS Threshold (%)` and `Throughput Threshold (%)` parameters to something a typical user would expect.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=684c757c25dc071c491c91e0
=> POL-1545 Azure Rightsize Managed Disks Fixes

cost/azure/superseded_instances/CHANGELOG.md, cost/azure/superseded_instances/azure_superseded_instances.pt, cost/azure/superseded_instances/azure_superseded_instances_meta_parent.pt
A ReferenceError is being caused:
```
ReferenceError: 'instance_type_price_map' is not defined\nLocation:\n datasource \"ds_superseded_instances\"\n script \"js_superseded_instances\
```
This is caused because the variable instance_type_price_map is not always declared, so instead of being undefined it's causing a reference error.
To fix this we declare the variable before accessing it.
There's a support question related to this PR: https://flexera.atlassian.net/browse/SQ-15559
Policy compiles well: https://app.flexeratest.com/orgs/1105/automation/projects/60073/policy-templates/68656ecb0e188e7b223c41b0
- [] New functionality has been documented in the README if applicable
=> SQ-15559 Azure Superseded Compute Instances Reference Error

cost/flexera/cco/cbi_ingestion_aws_s3/CHANGELOG.md, cost/flexera/cco/cbi_ingestion_aws_s3/README.md, cost/flexera/cco/cbi_ingestion_aws_s3/cbi_ingestion_aws_s3.pt, cost/flexera/cco/cbi_ingestion_azure_blob/CHANGELOG.md, cost/flexera/cco/cbi_ingestion_azure_blob/README.md, cost/flexera/cco/cbi_ingestion_azure_blob/cbi_ingestion_azure_blob.pt
Updates the "Common Bill Ingestion from AWS S3 Object Storage" and "Common Bill Ingestion from Azure Blob Storage" policy templates to support billing data stored at a daily, rather than a monthly, granularity. From the READMEs:
- *Granularity* - Whether there will be one file per month of billing data, or one file per day of billing data.
- If set to "Daily", file names will be expected to end with a full date like "2024-10-03.csv". The policy template will grab all of the files for a given month to upload to Flexera.
- If set to "Monthly", file names will be expected to end with a year and month like "2024-10.csv". The policy template will grab one file for the month to upload to Flexera.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=686d7beb86eaa86268 …
=> POL-1557 CBI Policy Daily Granularity Support

cost/flexera/cco/cbi_ingestion_aws_s3_iterating/CHANGELOG.md, cost/flexera/cco/cbi_ingestion_aws_s3_iterating/README.md, cost/flexera/cco/cbi_ingestion_aws_s3_iterating/cbi_ingestion_aws_s3_iterating.pt, cost/flexera/cco/cbi_ingestion_azure_blob_iterating/CHANGELOG.md, cost/flexera/cco/cbi_ingestion_azure_blob_iterating/README.md, cost/flexera/cco/cbi_ingestion_azure_blob_iterating/cbi_ingestion_azure_blob_iterating.pt, tools/policy_master_permission_generation/validated_policy_templates.yaml
Adds two new unpublished policy templates for sending CSV files from AWS S3 or Azure Blob Storage to Flexera CBI.
Unpublished because these policy templates require some extra knowhow to use, since they send in CSV files over multiple executions, similar to the Oracle CBI policy template. They should generally only be used as a fallback, with guidance from Flexera, when the published policy templates that work in a much more straight-forward and user-friendly way are not able to be used due to the amount of data being sent to CBI.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=686fb68486eaa862688b28ff
=> POL-1558 New Unpublished CBI Policy Templates

tools/meta_parent_policy_compiler/aws_meta_parent.pt.template, tools/meta_parent_policy_compiler/azure_meta_parent.pt.template, tools/meta_parent_policy_compiler/google_meta_parent.pt.template
Added "hourly" and "15 minutes" options to meta parent policies. This is primarily for policies like the scheduled instance policies where these options are needed.
=> POL-1570 Meta Parent: Added Hourly/15 Minute Options

data/azure/azure_compute_instance_types.json, tools/cloud_data/azure/azure_compute_instance_types.py
Fixed PR #3356.
The data type of "nfu" field is changed back to string.
=> FOPTS-12555 Fixed inconsistent type for "nfu" field.

cost/flexera/spot/ocean_cbi/CHANGELOG.md, cost/flexera/spot/ocean_cbi/spot_ocean_cbi.pt
Adds support for AKS and GKE (previously AWS EKS only)
https://flexera.atlassian.net/browse/FOAA-327
https://app.flexera.com/orgs/36084/automation/applied-policies/projects/138037?policyId=68a62841d071d7debca44608
=> FOAA-327 - Spot Ocean CBI - Add support for collecting Azure and GCP cluster cost data

cost/aws/superseded_instances/CHANGELOG.md, cost/aws/superseded_instances/README.md, cost/aws/superseded_instances/aws_superseded_instances.pt, cost/aws/superseded_instances/aws_superseded_instances_meta_parent.pt, cost/azure/superseded_instances/README.md
Similar to #3393, but this PR is for AWS.
Changed how savings is calculated.
Savings will be calculated using actual cost, multiplied by the percentage difference between the "list price" (or "NFU" if "list price" does not exists) of the current instance type and the recommended instance type.
This new calculation method aligns with [AWS Rightsize RDS](https://github.com/flexera-public/policy_templates/blob/master/cost/aws/rightsize_rds_instances/README.md#policy-savings-details).
----
Also fixed a bug related to "fallback instance type".
https://flexera.atlassian.net/browse/FOPTS-12555
https://flexera.atlassian.net/browse/SQ-16042
=> FOPTS-12555 Use actual cost to calculate savings for AWS superseded instance policy

cost/aws/savings_plan/recommendations/CHANGELOG.md, cost/aws/savings_plan/recommendations/aws_savings_plan_recommendations.pt
`AWS Savings Plan Recommendations`
- Changed incident field "Recommendeded Quantity to Purchase" to "Recommended Hourly Commitment" to both correct a spelling error and make the field clearer.
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=68bb29ad9ebedfa88031973a
=> POL-1588 AWS Savings Plan Recommendations: Rename Incident Field

cost/aws/unused_albs/CHANGELOG.md, cost/aws/unused_albs/aws_unused_albs.pt, cost/aws/unused_clbs/CHANGELOG.md, cost/aws/unused_clbs/aws_unused_clbs.pt, cost/aws/unused_nlbs/CHANGELOG.md, cost/aws/unused_nlbs/aws_unused_nlbs.pt
`AWS Unused Application Load Balancers`
- Fixed issue where estimated savings would sometimes be reported as 0 inaccurately.
`AWS Unused Classic Load Balancers`
- Fixed issue where estimated savings would sometimes be reported as 0 inaccurately.
- Fixed issue where `Resource ARN` field was malformed.
`AWS Unused Network Load Balancers`
- Fixed issue where estimated savings would sometimes be reported as 0 inaccurately.
(Also verified savings stuff works as expected in a user environment)
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=68d68e4daeb3e5d723f126c1
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=68d68e77aeb3e5d723f126c3
https://app.flexera.com/orgs/6/automation/applied-policies/projects/7954?policyId=68d68ea157a …
=> POL-1631 AWS Load Balancer Savings Fixes

cost/aws/savings_realized/CHANGELOG.md, cost/aws/savings_realized/README.md, cost/aws/savings_realized/aws_savings_realized.pt
Deprecates `AWS Savings Realized From Rate Reduction Purchases` in favor of more accurate, native product functionality.
No testing needed, as no meaningful code changes were made.
=> POL-1589 Deprecate AWS Savings Realized From Rate Reduction Purchases Policy Template
